import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.Schwartz.Spectral.Nonlinear.Forcing.Duhamel.Frechet.Second.Endpoint.Quarter.Heat.SecondMomentIncrement
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.Schwartz.Spectral.Nonlinear.Forcing.Duhamel.Frechet.Second.Endpoint.Forcing.HalfHolder

/-!
# Second-moment control of nonlinear forcing state variation

For a fixed positive heat lag, two Fourier moments are paid entirely by the
heat multiplier.  Therefore the second-moment L1 distance between the heated
diagonal nonlinear forcings generated by `U` and `V` is controlled by the
ordinary unheated forcing L1 distance.

The existing diagonal bilinear estimate then converts that forcing distance
into the H3 state difference `||U-V||`.  This is the state-variation half of
the continuity estimate for the selected second-moment profile.
-/

namespace PrimeTensor
namespace Bridge
namespace Euclidean

open MeasureTheory Set
open scoped ENNReal NNReal

noncomputable section

noncomputable local instance axisFintypeH3SchwartzQuarterForcingProfileStateVariation
    (d : Depth) :
    Fintype (PrimeTensor.Axis d) :=
  Fintype.ofFinite (PrimeTensor.Axis d)

/-- At a fixed positive heat lag, the second Fourier moment of a forcing
difference is bounded by the second-moment heat coefficient times its raw L1
mass. -/
theorem h3RawFinLerayOuterProductDivergenceHeat_diagonalDifference_secondMoment_integral_le
    {ν a : ℝ}
    (hν : 0 < ν)
    (ha : 0 < a)
    (U V : H3SpectralFinVectorState)
    (i : Fin 3) :
    (∫ ξ : H3FourierPoint3,
        ‖ξ‖ ^ 2 *
          ‖h3HeatFourierSymbol ν a ξ *
            (h3RawFinLerayOuterProductDivergence U U i ξ -
              h3RawFinLerayOuterProductDivergence V V i ξ)‖)
      ≤
    ((Real.sqrt (ν * (a / 3)))⁻¹) ^ 2 *
      (∫ ξ : H3FourierPoint3,
        ‖h3RawFinLerayOuterProductDivergence U U i ξ -
          h3RawFinLerayOuterProductDivergence V V i ξ‖) := by
  let C : ℝ := (Real.sqrt (ν * (a / 3)))⁻¹
  let D : H3FourierPoint3 → ℂ :=
    fun ξ =>
      h3RawFinLerayOuterProductDivergence U U i ξ -
        h3RawFinLerayOuterProductDivergence V V i ξ

  have hD :
      Integrable D (volume : Measure H3FourierPoint3) := by
    dsimp only [D]
    exact
      (h3RawFinLerayOuterProductDivergence_integrable U U i).sub
        (h3RawFinLerayOuterProductDivergence_integrable V V i)

  have hMajorantInt :
      Integrable
        (fun ξ : H3FourierPoint3 => C ^ 2 * ‖D ξ‖)
        (volume : Measure H3FourierPoint3) :=
    hD.norm.const_mul (C ^ 2)

  have hTargetMeas :
      AEStronglyMeasurable
        (fun ξ : H3FourierPoint3 =>
          ‖ξ‖ ^ 2 *
            ‖h3HeatFourierSymbol ν a ξ * D ξ‖)
        (volume : Measure H3FourierPoint3) := by
    exact
      ((continuous_norm.pow 2).aestronglyMeasurable).mul
        ((continuous_h3HeatFourierSymbol ν a).aestronglyMeasurable.mul
          hD.aestronglyMeasurable).norm

  have hTargetInt :
      Integrable
        (fun ξ : H3FourierPoint3 =>
          ‖ξ‖ ^ 2 *
            ‖h3HeatFourierSymbol ν a ξ * D ξ‖)
        (volume : Measure H3FourierPoint3) := by
    refine hMajorantInt.mono' hTargetMeas ?_
    filter_upwards with ξ
    have hMoment :=
      h3HeatFourierMomentMultiplier_le_three
        hν ha 2 (by norm_num) ξ
    have hTargetNonneg :
        0 ≤
          ‖ξ‖ ^ 2 *
            ‖h3HeatFourierSymbol ν a ξ * D ξ‖ := by
      positivity
    rw [Real.norm_eq_abs, abs_of_nonneg hTargetNonneg]
    rw [norm_mul]
    calc
      ‖ξ‖ ^ 2 *
          (‖h3HeatFourierSymbol ν a ξ‖ * ‖D ξ‖)
          =
        (‖ξ‖ ^ 2 * ‖h3HeatFourierSymbol ν a ξ‖) * ‖D ξ‖ := by
        ring
      _ ≤ C ^ 2 * ‖D ξ‖ := by
        exact
          mul_le_mul_of_nonneg_right
            hMoment
            (norm_nonneg (D ξ))

  calc
    (∫ ξ : H3FourierPoint3,
        ‖ξ‖ ^ 2 *
          ‖h3HeatFourierSymbol ν a ξ *
            (h3RawFinLerayOuterProductDivergence U U i ξ -
              h3RawFinLerayOuterProductDivergence V V i ξ)‖)
        =
      ∫ ξ : H3FourierPoint3,
        ‖ξ‖ ^ 2 *
          ‖h3HeatFourierSymbol ν a ξ * D ξ‖ := by
      rfl
    _ ≤
      ∫ ξ : H3FourierPoint3, C ^ 2 * ‖D ξ‖ := by
      refine integral_mono_ae hTargetInt hMajorantInt ?_
      filter_upwards with ξ
      have hMoment :=
        h3HeatFourierMomentMultiplier_le_three
          hν ha 2 (by norm_num) ξ
      rw [norm_mul]
      calc
        ‖ξ‖ ^ 2 *
            (‖h3HeatFourierSymbol ν a ξ‖ * ‖D ξ‖)
            =
          (‖ξ‖ ^ 2 * ‖h3HeatFourierSymbol ν a ξ‖) * ‖D ξ‖ := by
          ring
        _ ≤ C ^ 2 * ‖D ξ‖ := by
          exact
            mul_le_mul_of_nonneg_right
              hMoment
              (norm_nonneg (D ξ))
    _ =
      C ^ 2 * (∫ ξ : H3FourierPoint3, ‖D ξ‖) := by
      rw [integral_const_mul]
    _ =
      ((Real.sqrt (ν * (a / 3)))⁻¹) ^ 2 *
        (∫ ξ : H3FourierPoint3,
          ‖h3RawFinLerayOuterProductDivergence U U i ξ -
            h3RawFinLerayOuterProductDivergence V V i ξ‖) := by
      rfl

/-- Bilinear H3-state version of the fixed-lag second-moment forcing
difference estimate. -/
theorem h3RawFinLerayOuterProductDivergenceHeat_diagonalDifference_secondMoment_integral_le_stateDifference
    {ν a : ℝ}
    (hν : 0 < ν)
    (ha : 0 < a)
    (U V : H3SpectralFinVectorState)
    (i : Fin 3) :
    (∫ ξ : H3FourierPoint3,
        ‖ξ‖ ^ 2 *
          ‖h3HeatFourierSymbol ν a ξ *
            (h3RawFinLerayOuterProductDivergence U U i ξ -
              h3RawFinLerayOuterProductDivergence V V i ξ)‖)
      ≤
    ((Real.sqrt (ν * (a / 3)))⁻¹) ^ 2 *
      (h3NonlinearForcingL1Coefficient * ‖U - V‖ * ‖U‖ +
        h3NonlinearForcingL1Coefficient * ‖V‖ * ‖U - V‖) := by
  have hMoment :=
    h3RawFinLerayOuterProductDivergenceHeat_diagonalDifference_secondMoment_integral_le
      hν ha U V i

  have hDifference :=
    h3RawFinLerayOuterProductDivergence_diagonal_differenceL1Mass_le
      U V i

  exact
    hMoment.trans
      (mul_le_mul_of_nonneg_left
        hDifference
        (sq_nonneg ((Real.sqrt (ν * (a / 3)))⁻¹)))

end

end Euclidean
end Bridge
end PrimeTensor
