import PrimeTensor.Algebra
import PrimeTensor.Analysis.Chain
import PrimeTensor.Analysis.Control
import PrimeTensor.Analysis.Derivative
import PrimeTensor.Analysis.Examples
import PrimeTensor.Analysis.Growth
import PrimeTensor.Analysis.Limit
import PrimeTensor.Analysis.Near.Laws
import PrimeTensor.Analysis.Power.Growth
import PrimeTensor.Analysis.Rules
import PrimeTensor.Bridge.Approx
import PrimeTensor.Bridge.Bag.ClosedForm
import PrimeTensor.Bridge.Bag.Semantics
import PrimeTensor.Bridge.Cauchy
import PrimeTensor.Bridge.Convergence
import PrimeTensor.Bridge.Encode
import PrimeTensor.Bridge.Euclidean.Advection.Product
import PrimeTensor.Bridge.Euclidean.Classical
import PrimeTensor.Bridge.Euclidean.Curl.Advection
import PrimeTensor.Bridge.Euclidean.Curl.Advection.X
import PrimeTensor.Bridge.Euclidean.Curl.Laplacian
import PrimeTensor.Bridge.Euclidean.Curl.Laplacian.X
import PrimeTensor.Bridge.Euclidean.Curl.Linear
import PrimeTensor.Bridge.Euclidean.Differential
import PrimeTensor.Bridge.Euclidean.NavierStokes
import PrimeTensor.Bridge.Euclidean.Partials.Mixed
import PrimeTensor.Bridge.Euclidean.Partials.Third
import PrimeTensor.Bridge.Euclidean.Vorticity
import PrimeTensor.Bridge.Euclidean.Vorticity.Equation
import PrimeTensor.Bridge.Euclidean.Vorticity.Equation.X
import PrimeTensor.Bridge.Euclidean.Vorticity.Native
import PrimeTensor.Bridge.Euclidean.Vorticity.Native.X
import PrimeTensor.Bridge.Euclidean.Vorticity.Regularity
import PrimeTensor.Bridge.Euclidean.Vorticity.Stretching
import PrimeTensor.Bridge.Finite.Semantics
import PrimeTensor.Bridge.Fluid.Kernel
import PrimeTensor.Bridge.Fluid.Log.Semantics
import PrimeTensor.Bridge.Kernel.Agreement
import PrimeTensor.Bridge.Kernel.Asymptotic
import PrimeTensor.Bridge.Kernel.Descent
import PrimeTensor.Bridge.Kernel.Final
import PrimeTensor.Bridge.Kernel.Normalized.Completion
import PrimeTensor.Bridge.Kernel.Semantics
import PrimeTensor.Bridge.Kernel.Sequential.Control
import PrimeTensor.Bridge.Kernel.Sequential.Reduction
import PrimeTensor.Bridge.Kernel.Stream.Finite
import PrimeTensor.Bridge.Kernel.Tail.Input.Reduction
import PrimeTensor.Bridge.Log.Cauchy
import PrimeTensor.Bridge.Log.Concrete.Differential
import PrimeTensor.Bridge.Log.Product.Continuity
import PrimeTensor.Bridge.Log.Scale
import PrimeTensor.Bridge.Log.Surjective
import PrimeTensor.Bridge.Log.Tangent.Space
import PrimeTensor.Bridge.MulReal.Derivative.Semantics
import PrimeTensor.Bridge.MulReal.Log
import PrimeTensor.Bridge.MulReal.Log.Algebra
import PrimeTensor.Bridge.MulReal.Log.Embedding
import PrimeTensor.Bridge.MulReal.Negligible.Semantics
import PrimeTensor.Bridge.MulReal.Scalar.Derivative.Semantics
import PrimeTensor.Bridge.MulReal.Scale.Semantics
import PrimeTensor.Bridge.Multiset.Semantics
import PrimeTensor.Bridge.NormalizedTarget.Approx
import PrimeTensor.Bridge.Ratio.Semantics
import PrimeTensor.Bridge.Rational
import PrimeTensor.Bridge.Real
import PrimeTensor.Bridge.Real.Log.LittleO
import PrimeTensor.Bridge.Real.Tangent.Classification
import PrimeTensor.Bridge.Real.Tangent.Continuity
import PrimeTensor.Bridge.Real.Tangent.Space
import PrimeTensor.Bridge.Scale
import PrimeTensor.Completion
import PrimeTensor.Depth
import PrimeTensor.Fluid.Basic
import PrimeTensor.Fluid.Coupling
import PrimeTensor.Fluid.Coupling.Asymptotic
import PrimeTensor.Fluid.Coupling.Asymptotic.Completion
import PrimeTensor.Fluid.Coupling.Completion
import PrimeTensor.Fluid.Coupling.Control
import PrimeTensor.Fluid.Coupling.Descent
import PrimeTensor.Fluid.Coupling.Finite
import PrimeTensor.Fluid.Coupling.Normalize
import PrimeTensor.Fluid.Coupling.Prime
import PrimeTensor.Fluid.Coupling.Sequential.Control
import PrimeTensor.Fluid.Coupling.Stream.Agreement
import PrimeTensor.Fluid.Coupling.Stream.Finite
import PrimeTensor.Fluid.Coupling.Tail.Control
import PrimeTensor.Fluid.Coupling.Tail.Input
import PrimeTensor.Fluid.Coupling.UFD
import PrimeTensor.Fluid.Vorticity.Asymptotic.Stretching
import PrimeTensor.Fluid.Vorticity.BKM.Energy.Endpoint
import PrimeTensor.Fluid.Vorticity.BKM.Growth.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.Cascade
import PrimeTensor.Fluid.Vorticity.Continuation.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.Handoff
import PrimeTensor.Fluid.Vorticity.Continuation.Landau
import PrimeTensor.Fluid.Vorticity.Continuation.Restart
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Lifespan
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Bridge
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Bridge.Energy
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Heat.Fourier
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Heat.Path
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.HeatLeray
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.PathSpace
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.FourierCompatibility
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.FourierDerivative
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.FourierDerivativeAE
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.HeatSmoothing
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.Plancherel
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.Spectral
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.SpectralEncoder
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.Transport
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.WeakDerivative
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.State
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Picard
import PrimeTensor.Fluid.Vorticity.Coupling.Continuity
import PrimeTensor.Fluid.Vorticity.Diffusion.Branch
import PrimeTensor.Fluid.Vorticity.Extension.Locality
import PrimeTensor.Fluid.Vorticity.Field.Scale
import PrimeTensor.Fluid.Vorticity.H3.Axis.Sum
import PrimeTensor.Fluid.Vorticity.H3.Energy.Class.Split.Regularity
import PrimeTensor.Fluid.Vorticity.H3.Energy.Closure
import PrimeTensor.Fluid.Vorticity.H3.Energy.Closure.Landau
import PrimeTensor.Fluid.Vorticity.H3.Energy.Closure.Landau.Endpoint
import PrimeTensor.Fluid.Vorticity.H3.Energy.Derivative
import PrimeTensor.Fluid.Vorticity.H3.Energy.Diffusion
import PrimeTensor.Fluid.Vorticity.H3.Energy.Divergence
import PrimeTensor.Fluid.Vorticity.H3.Energy.Estimate
import PrimeTensor.Fluid.Vorticity.H3.Energy.Estimate.Landau.Closure
import PrimeTensor.Fluid.Vorticity.H3.Energy.Estimate.Landau.Tail
import PrimeTensor.Fluid.Vorticity.H3.Energy.Functional
import PrimeTensor.Fluid.Vorticity.H3.Energy.PDE.Decomposition
import PrimeTensor.Fluid.Vorticity.H3.Energy.PDE.Split
import PrimeTensor.Fluid.Vorticity.H3.Energy.Pressure
import PrimeTensor.Fluid.Vorticity.H3.Energy.Pressure.Class
import PrimeTensor.Fluid.Vorticity.H3.Energy.Regularity
import PrimeTensor.Fluid.Vorticity.H3.Energy.Spatial.Linearity
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Cancellation
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.IntegrationByParts.Closure
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.One
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.One.Bound
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.One.Integral
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.One.Pairing.Integrability.Closure
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.One.Sum
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.One.Total.Bound
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Expansion
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Gradient.Bound
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Gradient.Energy
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Gradient.Integrability.Closure
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Gradient.Integral
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Gradient.Sum
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Gradient.Total.Bound
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Interpolation.Atom
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Interpolation.Closure
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Interpolation.Frontier
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Interpolation.Holder.Core
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Interpolation.Holder.Landau
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Interpolation.Holder.Pairing
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Interpolation.Holder.Real
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Interpolation.Landau.Algebra
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Interpolation.Landau.Analytic.Closure
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Interpolation.Landau.Cancel
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Interpolation.Landau.Cauchy
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Interpolation.Landau.Direct.Closure
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Interpolation.Landau.Energy.Bookkeeping
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Interpolation.Landau.Holder.Closure
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Interpolation.Landau.IBP
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Interpolation.Landau.L2.Bridge
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Interpolation.Landau.Monomials
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Interpolation.Landau.Norm.Bridge
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Interpolation.Landau.Pairing.Integrability
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Interpolation.Monomials
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Interpolation.Reduction
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Landau.Closure
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Pairing.Integrability.Closure
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Regularity.Closure
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Split
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Two
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Two.Bound
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Two.Expansion
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Two.Integral
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Two.Sum
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Two.Total.Bound
import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Total.Closure
import PrimeTensor.Fluid.Vorticity.Jet.Failure
import PrimeTensor.Fluid.Vorticity.Jet.First.Continuity
import PrimeTensor.Fluid.Vorticity.Jet.Second.Continuity
import PrimeTensor.Fluid.Vorticity.Jet.Third.Continuity
import PrimeTensor.Fluid.Vorticity.L1Linf.Control
import PrimeTensor.Fluid.Vorticity.MovingTime
import PrimeTensor.Fluid.Vorticity.MovingTime.Leaves
import PrimeTensor.Fluid.Vorticity.Persistent.Forks
import PrimeTensor.Fluid.Vorticity.Pointwise.Diffusion
import PrimeTensor.Fluid.Vorticity.Preterminal.Equation
import PrimeTensor.Fluid.Vorticity.Preterminal.Extension
import PrimeTensor.Fluid.Vorticity.Primitive.Leaves
import PrimeTensor.Fluid.Vorticity.Refinement.Diffusion
import PrimeTensor.Fluid.Vorticity.Scale.Demand
import PrimeTensor.Fluid.Vorticity.Stretching.Demand
import PrimeTensor.Fluid.Vorticity.Time.Continuity
import PrimeTensor.MulRat
import PrimeTensor.Order
import PrimeTensor.Prime
import PrimeTensor.Ratio
import PrimeTensor.Scale
import PrimeTensor.Scale.Laws
import PrimeTensor.Structure
import PrimeTensor.Tensor.Basic
import PrimeTensor.Tensor.Calculus
import PrimeTensor.Tensor.Contract
import PrimeTensor.Tensor.Laws
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.SpectralL1

import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.SpectralWeightSplit

import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.YoungConvolution

import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.SobolevAlgebra

import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.YoungConvolutionRepresentatives

import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.YoungConvolutionDuality

import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.YoungConvolutionPairing

import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.RawFourierL2

import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.WeightedConvolutionIntegrand

import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.WeightedConvolutionPointwise

import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.WeightedConvolutionDomination

import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.WeightedConvolutionMajorants

import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.YoungConvolutionReal

import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.WeightedConvolutionMajorantStates

import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.WeightedConvolutionMajorantLocal

import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.WeightedConvolutionMajorantRepresentatives

import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.WeightedConvolutionL2

import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.VorticityFlux

import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.HeatDivergence

import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.HeatTimeKernel

import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.FinVorticityFlux

import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.FinDuhamelBound

import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.FinVelocityKernel
