import PrimeTensor.Fluid.Basic

/-!
# Intrinsic multiplicative coupling and advection

Native multiplication on `MulReal` plays the role of addition after logarithmic
conjugation:

    log (a * b) = log a + log b.

The Navier--Stokes transport term needs another operation whose logarithm plays
the role of multiplication:

    log (couple a b) = (log a) * (log b).

This file introduces that second operation abstractly and uses it to construct
the material/advection response.  No additive operation is added to the native
language.
-/

namespace PrimeTensor

/--
A second binary operation on multiplicative magnitudes.

Its intended bridge semantics is multiplication in logarithmic coordinates.
-/
structure MulCoupling where
  couple : MulReal → MulReal → MulReal

/--
Law-only bilinearity of the coupling with respect to native multiplicative
composition.

These are the multiplicative-language counterparts of distributivity of
ordinary multiplication over addition after logarithmic conjugation.
-/
structure IsMulCoupling (C : MulCoupling) : Prop where

  couple_one_left :
    ∀ a : MulReal,
      C.couple 1 a = 1

  couple_one_right :
    ∀ a : MulReal,
      C.couple a 1 = 1

  couple_mul_left :
    ∀ a b c : MulReal,
      C.couple (a * b) c =
        C.couple a c * C.couple b c

  couple_mul_right :
    ∀ a b c : MulReal,
      C.couple a (b * c) =
        C.couple a b * C.couple a c

namespace MulCoupling

/--
Symmetry is separated from bilinearity because advection only requires scalar
action in the first slot.  The eventual logarithmic model should satisfy it.
-/
def Symmetric (C : MulCoupling) : Prop :=
  ∀ a b : MulReal,
    C.couple a b = C.couple b a

end MulCoupling

namespace MulAdvection

/--
One directional contribution to material transport.

`i` supplies the velocity coefficient; `j` selects the transported component.
-/
def directional
    {X : Type} {dim : Depth}
    (D : Differential X MulReal dim)
    (C : MulCoupling)
    (u : VectorField X MulReal dim)
    (i j : Axis dim)
    (x : Point X dim) : MulReal :=
  C.couple
    ((u x).component i)
    (D.d i (fun y => (u y).component j) x)

/--
Spatial multiplicative advection.

For transported component `j`, contract all directional contributions by the
native positive-dimensional product.
-/
def spatial
    {X : Type} {dim : Depth}
    (D : Differential X MulReal dim)
    (C : MulCoupling)
    (u : VectorField X MulReal dim) :
    VectorField X MulReal dim :=
  fun x =>
    ⟨fun j =>
      Axis.fold (· * ·) dim
        (fun i =>
          directional D C u i j x)⟩

@[simp] theorem spatial_component
    {X : Type} {dim : Depth}
    (D : Differential X MulReal dim)
    (C : MulCoupling)
    (u : VectorField X MulReal dim)
    (x : Point X dim)
    (j : Axis dim) :
    (spatial D C u x).component j =
      Axis.fold (· * ·) dim
        (fun i =>
          C.couple
            ((u x).component i)
            (D.d i
              (fun y => (u y).component j)
              x)) := rfl

/-- Spacetime advection is the spatial construction applied at each time. -/
def spacetime
    {T X : Type} {dim : Depth}
    (D : Differential X MulReal dim)
    (C : MulCoupling)
    (u : SpaceTimeVectorField T X MulReal dim) :
    SpaceTimeVectorField T X MulReal dim :=
  fun t => spatial D C (u t)

end MulAdvection

namespace MulTransport

/--
The formerly abstract transport interface now has a canonical realization once
an intrinsic coupling operation is supplied.
-/
def ofCoupling
    {T X : Type} {dim : Depth}
    (D : Differential X MulReal dim)
    (C : MulCoupling) :
    MulTransport T X dim where
  act := MulAdvection.spacetime D C

@[simp] theorem ofCoupling_apply
    {T X : Type} {dim : Depth}
    (D : Differential X MulReal dim)
    (C : MulCoupling)
    (u : SpaceTimeVectorField T X MulReal dim)
    (t : T)
    (x : Point X dim)
    (j : Axis dim) :
    ((ofCoupling D C).act u t x).component j =
      Axis.fold (· * ·) dim
        (fun i =>
          C.couple
            ((u t x).component i)
            (D.d i
              (fun y => (u t y).component j)
              x)) := rfl

end MulTransport

namespace MulFluid

/--
Momentum balance with the transport operator constructed from intrinsic
coupling rather than supplied opaquely.
-/
def CoupledMomentumBalance
    {T X : Type} {dim : Depth}
    (Dt : TemporalDifferential T MulReal)
    (D : Differential X MulReal dim)
    (C : MulCoupling)
    (u : SpaceTimeVectorField T X MulReal dim)
    (p : SpaceTimeScalarField T X MulReal dim) : Prop :=
  MomentumBalance
    Dt D
    (MulTransport.ofCoupling D C)
    u p

/--
A fluid solution whose nonlinear transport is explicitly generated by the
multiplicative coupling operation.
-/
structure CoupledSolution
    {T X : Type} {dim : Depth}
    (Dt : TemporalDifferential T MulReal)
    (D : Differential X MulReal dim)
    (C : MulCoupling) where

  velocity :
    SpaceTimeVectorField T X MulReal dim

  pressure :
    SpaceTimeScalarField T X MulReal dim

  incompressible :
    Incompressible D velocity

  momentum :
    CoupledMomentumBalance
      Dt D C velocity pressure

/--
The coupled momentum equation written componentwise.

This theorem is intentionally just an unfolding theorem: it exposes the exact
native equation that future bridge proofs must conjugate to classical
Navier--Stokes.
-/
theorem coupledMomentum_component
    {T X : Type} {dim : Depth}
    (Dt : TemporalDifferential T MulReal)
    (D : Differential X MulReal dim)
    (C : MulCoupling)
    (u : SpaceTimeVectorField T X MulReal dim)
    (p : SpaceTimeScalarField T X MulReal dim)
    (h :
      CoupledMomentumBalance Dt D C u p)
    (t : T)
    (x : Point X dim)
    (j : Axis dim) :
    (Dt.vectorDerivative u t x).component j *
        Axis.fold (· * ·) dim
          (fun i =>
            C.couple
              ((u t x).component i)
              (D.d i
                (fun y => (u t y).component j)
                x)) =
      (pressureForce D p t x).component j *
        (laplacianVector D u t x).component j := by
  exact h t x j

end MulFluid

end PrimeTensor
