import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.Schwartz.Spectral.Classicalization.Physical.Tail.Endpoint.Canonical.Physical.L2.Admissible.Closure.Leray.Reduction

/-!
# Classicalization: split physical Leray density from temporal admissibility

The preceding Leray reduction identifies the exact remaining endpoint-evolution
frontier as

    physical Leray-fixed L² submodule
      ≤
    closed span of currently admissible weak tests.

The currently admissible test set contains two logically independent
restrictions:

* the test vector is compactly supported, smooth, and divergence-free;
* the test vector satisfies the endpoint-specific temporal local-domination
  condition needed by the weak FTC argument.

Those restrictions should not be mixed into one density theorem.

This file therefore introduces the parameter-free closed Hilbert span generated
by **all** compactly supported smooth divergence-free weak test vectors.  The
existing admissible closed span is automatically contained in this larger
closed span.

The old remaining inclusion then separates into two analytic questions:

1. **Leray density:** every physical Leray-fixed `L²` state belongs to the
   closed span of compact smooth divergence-free test vectors.
2. **Temporal admissibility saturation:** for the particular endpoint problem,
   the unrestricted divergence-free weak-test closed span is already contained
   in the closed span of tests satisfying the local-domination condition.

Their composition is exactly sufficient for the previous Leray-density
frontier.  Conversely, the previous frontier already implies the parameter-free
Leray-density statement because the admissible span is contained in the
unrestricted divergence-free span.

No density, mollification, cutoff, Bogovskii, or local-domination theorem is
claimed here.  The point of this checkpoint is to expose the two genuinely
different analytic obligations with no hidden coupling between them.
-/

namespace PrimeTensor
namespace Bridge
namespace Euclidean

open MeasureTheory Filter Set
open scoped BigOperators ENNReal NNReal Interval Topology InnerProductSpace

noncomputable section

noncomputable local instance axisFintypeH3PhysicalTailEndpointCanonicalPhysicalL2AdmissibleClosureLerayDensityReduction
    (d : Depth) :
    Fintype (PrimeTensor.Axis d) :=
  Fintype.ofFinite (PrimeTensor.Axis d)

noncomputable local instance point3MeasureSpaceH3PhysicalTailEndpointCanonicalPhysicalL2AdmissibleClosureLerayDensityReduction :
    MeasureSpace Point3 :=
  @MeasureTheory.MeasureSpace.pi
    (PrimeTensor.Axis Depth.three)
    (Fintype.ofFinite (PrimeTensor.Axis Depth.three))
    (fun _ : PrimeTensor.Axis Depth.three => ℝ)
    (fun _ : PrimeTensor.Axis Depth.three => Real.measureSpace)

/-! ## Parameter-free divergence-free weak-test closure -/

/-- Physical `L²` Hilbert states represented by arbitrary compactly supported
smooth divergence-free weak test vectors.  Unlike the endpoint-specific
admissible set, no temporal local-domination condition appears here. -/
noncomputable def h3DivergenceFreeWeakTestPhysicalL2Set :
    Set H3PhysicalRealFinVectorL2Hilbert :=
  { Φ |
    ∃ φ : H3WeakTestVector,
      H3WeakTestVectorDivergenceFree φ
        ∧
      Φ = h3WeakTestVectorPhysicalL2Hilbert φ }

/-- Algebraic real span of all compactly supported smooth divergence-free
physical weak-test states. -/
noncomputable def h3DivergenceFreeWeakTestPhysicalL2Span :
    Submodule ℝ H3PhysicalRealFinVectorL2Hilbert :=
  Submodule.span ℝ h3DivergenceFreeWeakTestPhysicalL2Set

/-- Closed Hilbert submodule generated by all compactly supported smooth
divergence-free physical weak-test states. -/
noncomputable def h3DivergenceFreeWeakTestPhysicalL2ClosedSpan :
    Submodule ℝ H3PhysicalRealFinVectorL2Hilbert :=
  h3DivergenceFreeWeakTestPhysicalL2Span.topologicalClosure

/-! ## The current admissible closure lies inside the unrestricted one -/

/-- Every endpoint-admissible weak test is, after forgetting temporal local
domination, an unrestricted compact smooth divergence-free weak test. -/
theorem h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2Set_subset_divergenceFreeWeakTestPhysicalL2Set
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail) :
    h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2Set
        hNS ht htau hEnd hE hTail hEndpoint
      ⊆
    h3DivergenceFreeWeakTestPhysicalL2Set := by
  intro Φ hΦ
  rcases hΦ with ⟨φ, hDiv, _hDom, hEq⟩
  exact ⟨φ, hDiv, hEq⟩

/-- The endpoint-admissible algebraic span is contained in the unrestricted
compact smooth divergence-free algebraic span. -/
theorem h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2Span_le_divergenceFreeWeakTestPhysicalL2Span
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail) :
    h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2Span
        hNS ht htau hEnd hE hTail hEndpoint
      ≤
    h3DivergenceFreeWeakTestPhysicalL2Span := by
  unfold
    h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2Span
    h3DivergenceFreeWeakTestPhysicalL2Span

  exact
    Submodule.span_mono
      (h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2Set_subset_divergenceFreeWeakTestPhysicalL2Set
        hNS ht htau hEnd hE hTail hEndpoint)

/-- Taking topological closures preserves the preceding inclusion. -/
theorem h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2ClosedSpan_le_divergenceFreeWeakTestPhysicalL2ClosedSpan
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail) :
    h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2ClosedSpan
        hNS ht htau hEnd hE hTail hEndpoint
      ≤
    h3DivergenceFreeWeakTestPhysicalL2ClosedSpan := by
  unfold
    h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2ClosedSpan
    h3DivergenceFreeWeakTestPhysicalL2ClosedSpan

  exact
    Submodule.topologicalClosure_mono
      (h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2Span_le_divergenceFreeWeakTestPhysicalL2Span
        hNS ht htau hEnd hE hTail hEndpoint)

/-! ## The two independent remaining analytic frontiers -/

/-- Parameter-free solenoidal density frontier: compact smooth divergence-free
weak tests are dense in the physical Leray-fixed `L²` submodule. -/
def H3PhysicalL2LerayFixedSubmoduleContainedInDivergenceFreeWeakTestClosedSpan :
    Prop :=
  h3PhysicalRealFinVectorL2HilbertLerayFixedSubmodule
    ≤
  h3DivergenceFreeWeakTestPhysicalL2ClosedSpan

/-- Endpoint-specific temporal-admissibility frontier: imposing the local
domination condition used by the weak FTC does not shrink the closed
divergence-free weak-test span. -/
def H3PreterminalTailCanonicalDivergenceFreeWeakTestClosedSpanContainedInAdmissibleWeakTestClosedSpan
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail) :
    Prop :=
  h3DivergenceFreeWeakTestPhysicalL2ClosedSpan
    ≤
  h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2ClosedSpan
    hNS ht htau hEnd hE hTail hEndpoint

/-- Leray density followed by temporal-admissibility saturation gives exactly
the single inclusion required by the preceding endpoint-evolution reduction. -/
theorem h3PreterminalTailCanonicalPhysicalL2LerayFixedSubmoduleContainedInAdmissibleWeakTestClosedSpan_of_density_of_temporalAdmissibility
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail)
    (hDensity :
      H3PhysicalL2LerayFixedSubmoduleContainedInDivergenceFreeWeakTestClosedSpan)
    (hTemporal :
      H3PreterminalTailCanonicalDivergenceFreeWeakTestClosedSpanContainedInAdmissibleWeakTestClosedSpan
        hNS ht htau hEnd hE hTail hEndpoint) :
    H3PreterminalTailCanonicalPhysicalL2LerayFixedSubmoduleContainedInAdmissibleWeakTestClosedSpan
      hNS ht htau hEnd hE hTail hEndpoint := by
  exact hDensity.trans hTemporal

/-- The preceding endpoint-specific inclusion already forces the parameter-free
Leray-density statement, because the admissible closed span is contained in the
unrestricted divergence-free closed span. -/
theorem H3PhysicalL2LerayFixedSubmoduleContainedInDivergenceFreeWeakTestClosedSpan_of_admissible
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail)
    (hContained :
      H3PreterminalTailCanonicalPhysicalL2LerayFixedSubmoduleContainedInAdmissibleWeakTestClosedSpan
        hNS ht htau hEnd hE hTail hEndpoint) :
    H3PhysicalL2LerayFixedSubmoduleContainedInDivergenceFreeWeakTestClosedSpan := by
  exact
    hContained.trans
      (h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2ClosedSpan_le_divergenceFreeWeakTestPhysicalL2ClosedSpan
        hNS ht htau hEnd hE hTail hEndpoint)

/-- Once temporal admissibility is known not to shrink the divergence-free
closed span, the old endpoint-specific inclusion is equivalent to the pure
parameter-free Leray-density theorem. -/
theorem h3PreterminalTailCanonicalPhysicalL2LerayFixedSubmoduleContainedInAdmissibleWeakTestClosedSpan_iff_density_of_temporalAdmissibility
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail)
    (hTemporal :
      H3PreterminalTailCanonicalDivergenceFreeWeakTestClosedSpanContainedInAdmissibleWeakTestClosedSpan
        hNS ht htau hEnd hE hTail hEndpoint) :
    H3PreterminalTailCanonicalPhysicalL2LerayFixedSubmoduleContainedInAdmissibleWeakTestClosedSpan
        hNS ht htau hEnd hE hTail hEndpoint
      ↔
    H3PhysicalL2LerayFixedSubmoduleContainedInDivergenceFreeWeakTestClosedSpan := by
  constructor

  · intro hContained
    exact
      H3PhysicalL2LerayFixedSubmoduleContainedInDivergenceFreeWeakTestClosedSpan_of_admissible
        hNS ht htau hEnd hE hTail hEndpoint hContained

  · intro hDensity
    exact
      h3PreterminalTailCanonicalPhysicalL2LerayFixedSubmoduleContainedInAdmissibleWeakTestClosedSpan_of_density_of_temporalAdmissibility
        hNS ht htau hEnd hE hTail hEndpoint
        hDensity hTemporal

end

end Euclidean
end Bridge
end PrimeTensor
