import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.Schwartz.Spectral.Nonlinear.Forcing.Duhamel.Frechet.Induction.Moment.Successor.Slab

/-!
# Fréchet endpoint induction: composed natural successor

The two analytic half-steps are now closed separately:

    M_n on [b/2,t]  ->  M_{n+3/4} on [b,t],

and

    M_n on [b,t] + M_{n+3/4} on [b,t]
      -> M_{n+1} on [2b,t].

This file composes them with `b = a/2`.  Consequently a natural `n`-moment
slab on `[a/4,t]` produces the natural successor moment on `[a,t]`.

There is no new Fourier estimate here.  The only work is interval bookkeeping:

* reinterpret `[a/4,t]` as `[(a/2)/2,t]`;
* restrict the natural slab to `[a/2,t]`;
* build the intermediate slab on `[a/2,t]`;
* feed both common-interval slabs to the successor theorem;
* normalize `2 * (a/2) = a`.

This is the complete reusable `n -> n+1` bootstrap step.
-/

namespace PrimeTensor
namespace Bridge
namespace Euclidean

open MeasureTheory Set Filter
open scoped BigOperators ENNReal NNReal Interval Topology InnerProductSpace

noncomputable section

/-!
## Budgets generated by one complete natural successor step
-/

/-- State budget of the intermediate `n+3/4` slab generated at lower
endpoint `a/2`. -/
noncomputable def h3SelectedNatSuccessorIntermediateStateBudget
    (n : ℕ)
    (ν A a t BState BDuhamel B0 : ℝ) : ℝ :=
  h3SelectedIntermediateSlabStateBudget
    n ν A (a / 2) t BState BDuhamel B0

/-- Duhamel budget of the intermediate `n+3/4` slab generated at lower
endpoint `a/2`. -/
noncomputable def h3SelectedNatSuccessorIntermediateDuhamelBudget
    (n : ℕ)
    (ν a t BState BDuhamel B0 : ℝ) : ℝ :=
  h3SelectedIntermediateSlabDuhamelBudget
    n ν (a / 2) t BState BDuhamel B0

/-- State budget after the complete composed `n -> n+1` step. -/
noncomputable def h3SelectedNatSuccessorStateBudget
    (n : ℕ)
    (ν A a t BState BDuhamel B0 : ℝ) : ℝ :=
  h3SelectedSuccessorSlabStateBudget
    n ν A (a / 2) t
    (h3SelectedNatSuccessorIntermediateStateBudget
      n ν A a t BState BDuhamel B0)
    BDuhamel B0

/-- Duhamel budget after the complete composed `n -> n+1` step. -/
noncomputable def h3SelectedNatSuccessorDuhamelBudget
    (n : ℕ)
    (ν A a t BState BDuhamel B0 : ℝ) : ℝ :=
  h3SelectedSuccessorSlabDuhamelBudget
    n ν (a / 2) t
    (h3SelectedNatSuccessorIntermediateStateBudget
      n ν A a t BState BDuhamel B0)
    BDuhamel B0

/-!
## Complete natural successor
-/

/-- Complete generic natural-moment successor.

For `1 ≤ n`, a uniform natural `n`-moment slab beginning at `a/4` yields a
uniform natural `n+1`-moment slab beginning at `a`.  The factor four in the
lower endpoint is exactly the composition of the two terminal-half
requirements; no extra analytic loss is introduced here. -/
theorem h3SelectedMomentSlab_nat_to_natSucc
    {ν A a t BState BDuhamel B0 : ℝ}
    (n : ℕ)
    (hn : 1 ≤ n)
    (hν : 0 < ν)
    (U₀ : H3SpectralVelocityState)
    (hA : 0 < A)
    (hU₀ : ‖U₀‖ ≤ A)
    (ha : 0 < a)
    (hat : a ≤ t)
    (htR : t ≤ h3FinHeatLerayRestartRadius ν A)
    (hSlab :
      H3SelectedMomentSlab
        (n : ℝ) ν A (a / 4) t
        BState BDuhamel B0
        hν U₀ hA hU₀) :
    H3SelectedMomentSlab
      ((n : ℝ) + 1)
      ν A a t
      (h3SelectedNatSuccessorStateBudget
        n ν A a t BState BDuhamel B0)
      (h3SelectedNatSuccessorDuhamelBudget
        n ν A a t BState BDuhamel B0)
      B0
      hν U₀ hA hU₀ := by
  have hHalf0 : 0 < a / 2 := by
    positivity

  have hHalfT : a / 2 ≤ t := by
    linarith

  have hQuarterEq :
      (a / 2) / 2 = a / 4 := by
    ring

  have hInput :
      H3SelectedMomentSlab
        (n : ℝ) ν A ((a / 2) / 2) t
        BState BDuhamel B0
        hν U₀ hA hU₀ := by
    rw [hQuarterEq]
    exact hSlab

  have hNatCommon :
      H3SelectedMomentSlab
        (n : ℝ) ν A (a / 2) t
        BState BDuhamel B0
        hν U₀ hA hU₀ := by
    exact
      H3SelectedMomentSlab.restrict
        hInput
        (by linarith)
        le_rfl

  have hIntermediate :
      H3SelectedMomentSlab
        ((n : ℝ) + (3 : ℝ) / 4)
        ν A (a / 2) t
        (h3SelectedIntermediateSlabStateBudget
          n ν A (a / 2) t BState BDuhamel B0)
        (h3SelectedIntermediateSlabDuhamelBudget
          n ν (a / 2) t BState BDuhamel B0)
        B0
        hν U₀ hA hU₀ := by
    exact
      h3SelectedMomentSlab_nat_to_natAddThreeQuarter
        (a := a / 2)
        n hn hν U₀ hA hU₀
        hHalf0 hHalfT htR hInput

  have hSecond :
      H3SelectedMomentSlab
        ((n : ℝ) + 1)
        ν A (2 * (a / 2)) t
        (h3SelectedSuccessorSlabStateBudget
          n ν A (a / 2) t
          (h3SelectedIntermediateSlabStateBudget
            n ν A (a / 2) t BState BDuhamel B0)
          BDuhamel B0)
        (h3SelectedSuccessorSlabDuhamelBudget
          n ν (a / 2) t
          (h3SelectedIntermediateSlabStateBudget
            n ν A (a / 2) t BState BDuhamel B0)
          BDuhamel B0)
        B0
        hν U₀ hA hU₀ := by
    exact
      h3SelectedMomentSlab_natAddThreeQuarter_to_natSucc
        (a := a / 2)
        (BState := BState)
        (BDuhamel := BDuhamel)
        (B0 := B0)
        (BIntermediateState :=
          h3SelectedIntermediateSlabStateBudget
            n ν A (a / 2) t BState BDuhamel B0)
        (BIntermediateDuhamel :=
          h3SelectedIntermediateSlabDuhamelBudget
            n ν (a / 2) t BState BDuhamel B0)
        n hn hν U₀ hA hU₀
        hHalf0
        (by linarith)
        htR
        hNatCommon
        hIntermediate

  have hLowerEq :
      2 * (a / 2) = a := by
    ring

  unfold
    h3SelectedNatSuccessorStateBudget
    h3SelectedNatSuccessorDuhamelBudget
    h3SelectedNatSuccessorIntermediateStateBudget

  rw [hLowerEq] at hSecond
  exact hSecond

end
end Euclidean
end Bridge
end PrimeTensor
