import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.Schwartz.Spectral.Classicalization.Physical.Tail.Endpoint.Canonical.Physical.L2.Admissible.Closure.Leray.Density.Temporal.Endpoint.Family.Closure.Curl
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.Schwartz.Spectral.Classicalization.Physical.Tail.Endpoint.Canonical.Physical.L2.Admissible.Closure.Leray.Density.Dual.Curl.Pairing
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.Schwartz.Spectral.Classicalization.Physical.Tail.Endpoint.Canonical.Physical.L2.Admissible.Closure.Leray.Density.Temporal.Endpoint.Family.Closure.WeakDerivative

/-!
# Reduce weak curl-freeness of the evolution defect to three integrated curl tests

`Closure.Curl` showed that physical endpoint evolution follows as soon as every
shortened defect

    D_q = (W(q) - W(0)) - ∫₀^q R(s) ds

is weakly curl-free.

Weak curl-freeness is only three scalar identities.  The existing compact curl
tests generated by one scalar weak test `ψ` are

    curl01(ψ) = ( ∂₁ψ, -∂₀ψ,      0 ),
    curl02(ψ) = ( ∂₂ψ,      0, -∂₀ψ ),
    curl12(ψ) = (     0,  ∂₂ψ, -∂₁ψ ).

Therefore we do not need the integrated weak momentum identity for every
divergence-free test.  It is enough to know it for exactly these three tests.

This file proves that reduction.  It contains no product-space Fubini argument,
no joint continuity assumption, and no new PDE estimate.  The next analytic
target is now precisely the three vorticity pairings represented by the above
curl tests.
-/

namespace PrimeTensor
namespace Bridge
namespace Euclidean

open MeasureTheory Filter Set FourierTransform
open scoped BigOperators ENNReal NNReal Interval Topology InnerProductSpace

noncomputable section

/-- Exact integrated weak-time frontier needed by the curl route: for every
scalar compact weak test and every shortened target, the three elementary curl
tests satisfy the integrated projected-RHS identity. -/
def H3PreterminalTailCanonicalCurlWeakVelocityPairingsSatisfyIntegratedProjectedRHSOnElapsed
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail) : Prop :=
  ∀ ψ : H3WeakTestFunction,
    ∀ q : Set.Icc (0 : ℝ) tau,
      let q0 : Set.Icc (0 : ℝ) tau :=
        ⟨0, ⟨le_rfl, htau.le⟩⟩
      (
        h3PreterminalTailCanonicalVelocityWeakPairingOnElapsed
            hNS ht hEnd hTail (h3WeakTestCurl01 ψ) q
          -
        h3PreterminalTailCanonicalVelocityWeakPairingOnElapsed
            hNS ht hEnd hTail (h3WeakTestCurl01 ψ) q0
          =
        ∫ s in (0 : ℝ)..(q : ℝ),
          h3PreterminalTailCanonicalWeakProjectedRHSPairingReal
            hNS ht htau hEnd hE hTail hEndpoint
            (h3WeakTestCurl01 ψ) s
      )
      ∧
      (
        h3PreterminalTailCanonicalVelocityWeakPairingOnElapsed
            hNS ht hEnd hTail (h3WeakTestCurl02 ψ) q
          -
        h3PreterminalTailCanonicalVelocityWeakPairingOnElapsed
            hNS ht hEnd hTail (h3WeakTestCurl02 ψ) q0
          =
        ∫ s in (0 : ℝ)..(q : ℝ),
          h3PreterminalTailCanonicalWeakProjectedRHSPairingReal
            hNS ht htau hEnd hE hTail hEndpoint
            (h3WeakTestCurl02 ψ) s
      )
      ∧
      (
        h3PreterminalTailCanonicalVelocityWeakPairingOnElapsed
            hNS ht hEnd hTail (h3WeakTestCurl12 ψ) q
          -
        h3PreterminalTailCanonicalVelocityWeakPairingOnElapsed
            hNS ht hEnd hTail (h3WeakTestCurl12 ψ) q0
          =
        ∫ s in (0 : ℝ)..(q : ℝ),
          h3PreterminalTailCanonicalWeakProjectedRHSPairingReal
            hNS ht htau hEnd hE hTail hEndpoint
            (h3WeakTestCurl12 ψ) s
      )

/-- One integrated scalar weak-pairing identity is already enough to identify
the Hilbert pairing of the velocity increment with the shortened projected-RHS
Bochner integral for that same test.

No differentiability assumption is needed here because the integrated identity
is supplied directly. -/
theorem inner_h3WeakTestVectorPhysicalL2Hilbert_velocityIncrementTo_eq_bochnerProjectedRHSTo_of_integratedWeakPairing
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail)
    (φ : H3WeakTestVector)
    (q : Set.Icc (0 : ℝ) tau)
    (hIntegrated :
      h3PreterminalTailCanonicalVelocityWeakPairingOnElapsed
          hNS ht hEnd hTail φ q
        -
      h3PreterminalTailCanonicalVelocityWeakPairingOnElapsed
          hNS ht hEnd hTail φ
          ⟨0, ⟨le_rfl, htau.le⟩⟩
        =
      ∫ s in (0 : ℝ)..(q : ℝ),
        h3PreterminalTailCanonicalWeakProjectedRHSPairingReal
          hNS ht htau hEnd hE hTail hEndpoint φ s) :
    inner ℝ
        (h3WeakTestVectorPhysicalL2Hilbert φ)
        (h3PreterminalTailCanonicalVelocityIncrementPhysicalL2HilbertTo
          hNS ht htau hEnd hTail q)
      =
    inner ℝ
        (h3WeakTestVectorPhysicalL2Hilbert φ)
        (h3PreterminalTailCanonicalProjectedRHSPhysicalL2BochnerIntegralHilbertTo
          hNS ht htau hEnd hE hTail hEndpoint q) := by
  have hRhsEq :
      h3PreterminalTailCanonicalProjectedRHSPhysicalL2WeakPairingReal
          hNS ht htau hEnd hE hTail hEndpoint φ
        =
      h3PreterminalTailCanonicalWeakProjectedRHSPairingReal
        hNS ht htau hEnd hE hTail hEndpoint φ :=
    h3PreterminalTailCanonicalProjectedRHSPhysicalL2WeakPairingReal_eq_weakProjectedRHSPairingReal
      hNS ht htau hEnd hE hTail hEndpoint φ

  have hWeak := hIntegrated
  rw [← hRhsEq] at hWeak

  calc
    inner ℝ
        (h3WeakTestVectorPhysicalL2Hilbert φ)
        (h3PreterminalTailCanonicalVelocityIncrementPhysicalL2HilbertTo
          hNS ht htau hEnd hTail q)
        =
      h3PreterminalTailCanonicalVelocityWeakPairingOnElapsed
          hNS ht hEnd hTail φ q
        -
      h3PreterminalTailCanonicalVelocityWeakPairingOnElapsed
          hNS ht hEnd hTail φ
          ⟨0, ⟨le_rfl, htau.le⟩⟩ :=
      inner_h3WeakTestVectorPhysicalL2Hilbert_velocityIncrementTo
        hNS ht htau hEnd hTail φ q
    _ =
      ∫ s in (0 : ℝ)..(q : ℝ),
        h3PreterminalTailCanonicalProjectedRHSPhysicalL2WeakPairingReal
          hNS ht htau hEnd hE hTail hEndpoint φ s :=
      hWeak
    _ =
      ∑ i : Fin 3,
        inner ℝ
          (h3WeakTestFunctionPhysicalL2 (φ i))
          (h3PreterminalTailCanonicalProjectedRHSPhysicalL2BochnerIntegralTo
            hNS ht htau hEnd hE hTail hEndpoint q i) :=
      intervalIntegral_h3PreterminalTailCanonicalProjectedRHSPhysicalL2WeakPairingReal_to_eq_sum_inner_bochnerTo
        hNS ht htau hEnd hE hTail hEndpoint φ q
    _ =
      inner ℝ
        (h3WeakTestVectorPhysicalL2Hilbert φ)
        (h3PreterminalTailCanonicalProjectedRHSPhysicalL2BochnerIntegralHilbertTo
          hNS ht htau hEnd hE hTail hEndpoint q) :=
      (inner_h3WeakTestVectorPhysicalL2Hilbert_bochnerProjectedRHSTo
        hNS ht htau hEnd hE hTail hEndpoint φ q).symm

/-- The three integrated curl-test identities force one shortened evolution
defect to be weakly curl-free. -/
theorem h3PreterminalTailCanonicalPhysicalL2EvolutionDefectTo_weakCurlFree_of_integratedCurlPairings
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail)
    (hCurlIntegrated :
      H3PreterminalTailCanonicalCurlWeakVelocityPairingsSatisfyIntegratedProjectedRHSOnElapsed
        hNS ht htau hEnd hE hTail hEndpoint)
    (q : Set.Icc (0 : ℝ) tau) :
    H3PhysicalRealFinVectorL2HilbertWeakCurlFree
      (h3PreterminalTailCanonicalPhysicalL2EvolutionDefectTo
        hNS ht htau hEnd hE hTail hEndpoint q) := by
  let D : H3PhysicalRealFinVectorL2Hilbert :=
    h3PreterminalTailCanonicalPhysicalL2EvolutionDefectTo
      hNS ht htau hEnd hE hTail hEndpoint q

  intro ψ

  rcases hCurlIntegrated ψ q with
    ⟨h01Integrated, h02Integrated, h12Integrated⟩

  have h01Eq :=
    inner_h3WeakTestVectorPhysicalL2Hilbert_velocityIncrementTo_eq_bochnerProjectedRHSTo_of_integratedWeakPairing
      hNS ht htau hEnd hE hTail hEndpoint
      (h3WeakTestCurl01 ψ) q h01Integrated

  have h02Eq :=
    inner_h3WeakTestVectorPhysicalL2Hilbert_velocityIncrementTo_eq_bochnerProjectedRHSTo_of_integratedWeakPairing
      hNS ht htau hEnd hE hTail hEndpoint
      (h3WeakTestCurl02 ψ) q h02Integrated

  have h12Eq :=
    inner_h3WeakTestVectorPhysicalL2Hilbert_velocityIncrementTo_eq_bochnerProjectedRHSTo_of_integratedWeakPairing
      hNS ht htau hEnd hE hTail hEndpoint
      (h3WeakTestCurl12 ψ) q h12Integrated

  have h01Test :
      inner ℝ
          (h3WeakTestVectorPhysicalL2Hilbert (h3WeakTestCurl01 ψ))
          D
        =
      0 := by
    dsimp only [D]
    unfold h3PreterminalTailCanonicalPhysicalL2EvolutionDefectTo
    rw [inner_sub_right]
    exact sub_eq_zero.mpr h01Eq

  have h02Test :
      inner ℝ
          (h3WeakTestVectorPhysicalL2Hilbert (h3WeakTestCurl02 ψ))
          D
        =
      0 := by
    dsimp only [D]
    unfold h3PreterminalTailCanonicalPhysicalL2EvolutionDefectTo
    rw [inner_sub_right]
    exact sub_eq_zero.mpr h02Eq

  have h12Test :
      inner ℝ
          (h3WeakTestVectorPhysicalL2Hilbert (h3WeakTestCurl12 ψ))
          D
        =
      0 := by
    dsimp only [D]
    unfold h3PreterminalTailCanonicalPhysicalL2EvolutionDefectTo
    rw [inner_sub_right]
    exact sub_eq_zero.mpr h12Eq

  have h01 :
      inner ℝ
          (D 0)
          (h3WeakTestFunctionPhysicalL2
            (h3WeakTestFunctionSpatialDerivative
              (h3AxisOfFin3 1) ψ))
        -
      inner ℝ
          (D 1)
          (h3WeakTestFunctionPhysicalL2
            (h3WeakTestFunctionSpatialDerivative
              (h3AxisOfFin3 0) ψ))
        =
      0 := by
    have hPair :
        inner ℝ
            D
            (h3WeakTestVectorPhysicalL2Hilbert (h3WeakTestCurl01 ψ))
          =
        0 := by
      simpa only [real_inner_comm] using h01Test

    rw [
      inner_h3PhysicalRealFinVectorL2Hilbert_weakTestVector,
      Fin.sum_univ_three
    ] at hPair

    simpa only [
      h3WeakTestCurl01_apply_zero,
      h3WeakTestCurl01_apply_one,
      h3WeakTestCurl01_apply_two,
      h3WeakTestFunctionPhysicalL2_neg,
      h3WeakTestFunctionPhysicalL2_zero,
      inner_neg_right,
      inner_zero_right,
      add_zero,
      sub_eq_add_neg
    ] using hPair

  have h02 :
      inner ℝ
          (D 0)
          (h3WeakTestFunctionPhysicalL2
            (h3WeakTestFunctionSpatialDerivative
              (h3AxisOfFin3 2) ψ))
        -
      inner ℝ
          (D 2)
          (h3WeakTestFunctionPhysicalL2
            (h3WeakTestFunctionSpatialDerivative
              (h3AxisOfFin3 0) ψ))
        =
      0 := by
    have hPair :
        inner ℝ
            D
            (h3WeakTestVectorPhysicalL2Hilbert (h3WeakTestCurl02 ψ))
          =
        0 := by
      simpa only [real_inner_comm] using h02Test

    rw [
      inner_h3PhysicalRealFinVectorL2Hilbert_weakTestVector,
      Fin.sum_univ_three
    ] at hPair

    simpa only [
      h3WeakTestCurl02_apply_zero,
      h3WeakTestCurl02_apply_one,
      h3WeakTestCurl02_apply_two,
      h3WeakTestFunctionPhysicalL2_neg,
      h3WeakTestFunctionPhysicalL2_zero,
      inner_neg_right,
      inner_zero_right,
      zero_add,
      add_zero,
      sub_eq_add_neg
    ] using hPair

  have h12 :
      inner ℝ
          (D 1)
          (h3WeakTestFunctionPhysicalL2
            (h3WeakTestFunctionSpatialDerivative
              (h3AxisOfFin3 2) ψ))
        -
      inner ℝ
          (D 2)
          (h3WeakTestFunctionPhysicalL2
            (h3WeakTestFunctionSpatialDerivative
              (h3AxisOfFin3 1) ψ))
        =
      0 := by
    have hPair :
        inner ℝ
            D
            (h3WeakTestVectorPhysicalL2Hilbert (h3WeakTestCurl12 ψ))
          =
        0 := by
      simpa only [real_inner_comm] using h12Test

    rw [
      inner_h3PhysicalRealFinVectorL2Hilbert_weakTestVector,
      Fin.sum_univ_three
    ] at hPair

    simpa only [
      h3WeakTestCurl12_apply_zero,
      h3WeakTestCurl12_apply_one,
      h3WeakTestCurl12_apply_two,
      h3WeakTestFunctionPhysicalL2_neg,
      h3WeakTestFunctionPhysicalL2_zero,
      inner_neg_right,
      inner_zero_right,
      zero_add,
      sub_eq_add_neg
    ] using hPair

  exact ⟨h01, h02, h12⟩

/-- Hence the three integrated curl-test identities are sufficient for genuine
physical `L²` evolution at every shortened target. -/
theorem h3PreterminalTailCanonicalVelocityIncrementPhysicalL2HilbertTo_eq_BochnerProjectedRHSTo_of_integratedCurlPairings
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail)
    (hCurlIntegrated :
      H3PreterminalTailCanonicalCurlWeakVelocityPairingsSatisfyIntegratedProjectedRHSOnElapsed
        hNS ht htau hEnd hE hTail hEndpoint)
    (q : Set.Icc (0 : ℝ) tau) :
    h3PreterminalTailCanonicalVelocityIncrementPhysicalL2HilbertTo
        hNS ht htau hEnd hTail q
      =
    h3PreterminalTailCanonicalProjectedRHSPhysicalL2BochnerIntegralHilbertTo
      hNS ht htau hEnd hE hTail hEndpoint q := by
  apply
    h3PreterminalTailCanonicalVelocityIncrementPhysicalL2HilbertTo_eq_BochnerProjectedRHSTo_of_all_defects_weakCurlFree
      hNS ht htau hEnd hE hTail hEndpoint

  intro r
  exact
    h3PreterminalTailCanonicalPhysicalL2EvolutionDefectTo_weakCurlFree_of_integratedCurlPairings
      hNS ht htau hEnd hE hTail hEndpoint hCurlIntegrated r

end

end Euclidean
end Bridge
end PrimeTensor
