#!/usr/bin/env bash
# Render prose fragments under proof/ to PDF, with LuaLaTeX.
#
# LuaLaTeX, not pdfLaTeX: the fragments quote Lean's Unicode literally and
# preamble.tex is built on fontspec/unicode-math.
#
#   ./build.sh Depth              -> proof/Depth.pdf
#   ./build.sh Bridge/Log/Scale   -> proof/Bridge/Log/Scale.pdf
#   ./build.sh --all              -> one PDF per fragment
#   ./build.sh --main             -> proof/main.pdf (the aggregate document)
#
# Module names are given relative to proof/, without the .tex extension,
# and mirror the paths under PrimeTensor/.
set -euo pipefail

cd "$(dirname "$0")"
AUX="$(mktemp -d)"
trap 'rm -rf "$AUX"' EXIT

render() {
  local module="$1"
  if [ ! -f "$module.tex" ]; then
    echo "build.sh: no such fragment: $module.tex" >&2
    return 1
  fi
  # Snippets verbatim, labels namespaced, references local.
  python3 check_fragment.py "$module" || return 1
  echo "  $module.tex -> $module.pdf"
  local jobname
  jobname="$(printf '%s' "$module" | tr '/' '_')"
  for _ in 1 2; do
    lualatex -interaction=nonstopmode -halt-on-error \
      -output-directory "$AUX" -jobname "$jobname" \
      "\\def\\ProofFile{$module}\\input{standalone.tex}" >/dev/null
  done
  mkdir -p "$(dirname "$module.pdf")"
  mv "$AUX/$jobname.pdf" "$module.pdf"
}

# Regenerate modules.tex: every entry of order.txt whose fragment exists,
# in order.  Keeps per-module changes to a single added file.
generate_module_list() {
  local n=0
  : > modules.tex
  {
    echo "% Generated by build.sh from order.txt.  Do not edit; do not commit."
    while IFS= read -r module; do
      case "$module" in ''|'#'*) continue ;; esac
      if [ -f "$module.tex" ]; then
        echo "\\input{$module}"
        n=$((n + 1))
      fi
    done < order.txt
  } > modules.tex
  echo "  order.txt -> modules.tex ($n of $(grep -c . order.txt) modules written)"
}

render_main() {
  python3 check_fragment.py --all || return 1
  generate_module_list
  echo "  main.tex -> main.pdf"
  for _ in 1 2; do
    lualatex -interaction=nonstopmode -halt-on-error \
      -output-directory "$AUX" main.tex >/dev/null
  done
  mv "$AUX/main.pdf" main.pdf
}

case "${1:-}" in
  "")
    echo "usage: build.sh <module> | --all | --main" >&2
    exit 2
    ;;
  --main)
    render_main
    ;;
  --all)
    while IFS= read -r f; do
      render "${f#./}"
    done < <(find . -name '*.tex' \
               ! -name 'main.tex' ! -name 'preamble.tex' \
               ! -name 'standalone.tex' | sed 's/\.tex$//' | sort)
    ;;
  *)
    for m in "$@"; do render "${m%.tex}"; done
    ;;
esac
