#!/usr/bin/env python3
"""Maintain a deterministic source index and map existing prose fragments."""
import argparse
import graphlib
import hashlib
import json
from pathlib import Path
import subprocess
import sys

sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT/'tools/audit'))
from inspect_source import strip_comments
import re


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument('--check', action='store_true')
    mode.add_argument('--inputs', action='store_true')
    args = parser.parse_args()
    proof = ROOT/'proof'
    files = {p.relative_to(ROOT/'PrimeTensor').with_suffix('').as_posix(): p
             for p in sorted((ROOT/'PrimeTensor').rglob('*.lean'))}
    graph = {}
    digest = hashlib.sha256()
    for name, path in files.items():
        data = path.read_bytes()
        digest.update(name.encode()+b'\0'+data+b'\0')
        imports = [m for line in re.findall(r'^\s*import\s+([^\n]+)', strip_comments(data.decode()), re.M) for m in line.split()]
        graph[name] = sorted({m[len('PrimeTensor.'):].replace('.', '/') for m in imports
                              if m.startswith('PrimeTensor.') and m[len('PrimeTensor.'):].replace('.', '/') in files})
    order = list(graphlib.TopologicalSorter(graph).static_order())
    mapping = json.loads((proof/'source-map.json').read_text())
    fragments = sorted(p.relative_to(proof).with_suffix('').as_posix() for p in proof.rglob('*.tex')
                       if p.name not in {'main.tex','preamble.tex','standalone.tex','modules.tex'})
    by_source = {}
    for fragment in fragments:
        source = mapping.get(fragment, fragment)
        if source not in files: raise ValueError(f'No source for fragment {fragment}: {source}')
        if source in by_source: raise ValueError(f'Two fragments map to {source}')
        by_source[source] = fragment
    for fragment in mapping:
        if fragment not in fragments: raise ValueError(f'Stale fragment mapping: {fragment}')
    if args.inputs:
        print('% Generated by generate_index.py; source digest '+digest.hexdigest())
        for name in order:
            if name in by_source: print('\\input{'+by_source[name]+'}')
        return 0
    header = '# Source SHA-256: '+digest.hexdigest()
    lines = [header, '# Existing project import edges only; excluded/missing sources are tracked in tools/audit/known-source-gaps.json.', *order]
    target = proof/'order.txt'
    if args.check:
        existing = target.read_text().splitlines()
        normalized = [line for line in existing if not line.startswith('# Generated from revision:')]
        if normalized != lines:
            print('Source index is stale. Run python3 proof/generate_index.py.', file=sys.stderr)
            return 1
        print(f'Source index current: {len(order)} modules; {len(fragments)} prose fragments.')
    else:
        revision = subprocess.check_output(['git','-C',str(ROOT),'rev-parse','HEAD'],text=True).strip()
        target.write_text('\n'.join(['# Generated from revision: '+revision,*lines])+'\n')
        print(f'Wrote source index: {len(order)} modules; {len(fragments)} prose fragments.')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
