import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Interpolation.Landau.Analytic.Quartic.BoundaryNorm

/-!
# Hölder partner for the quartic cutoff boundary term

The cutoff boundary derivative is now controlled in `L⁴`.  Its Hölder partner is

    v g³.

The frontier assumptions give exactly the complementary exponent:

* `g ∈ L⁴` implies `g³ ∈ L^(4/3)`;
* the scalar envelope makes `v` an `L∞` multiplier;
* therefore `v g³ ∈ L^(4/3)`.

This factor is independent of the cutoff radius.  Combined with the previous
`L⁴` estimate on `Dχ_R`, the next increment can bound the boundary integral by

    ‖Dχ_R‖₄ ‖v g³‖_(4/3)

and send it to zero.
-/

namespace PrimeTensor
namespace Bridge
namespace Euclidean

open Set Function MeasureTheory Filter
open scoped ENNReal NNReal Topology ContDiff

noncomputable section

noncomputable local instance axisFintypeH3LandauQuarticBoundaryHolder
    (d : Depth) :
    Fintype (PrimeTensor.Axis d) :=
  Fintype.ofFinite (PrimeTensor.Axis d)

/-- The exponent generated by cubing an `L⁴` function is `4/3`. -/
theorem ennreal_four_div_three :
    (ENNReal.ofReal 4) / (ENNReal.ofReal 3)
      =
    ENNReal.ofReal (4 / 3 : ℝ) := by
  exact
    (
      ENNReal.ofReal_div_of_pos
        (show (0 : ℝ) < 3 by norm_num)
    ).symm

/-- Cubing an `L⁴` real field puts it in `L^(4/3)`. -/
theorem memLp_four_thirds_cube_of_memLp_four
    {g : ScalarField3}
    (hg4 :
      MeasureTheory.MemLp
        g
        (ENNReal.ofReal 4)
        volume) :
    MeasureTheory.MemLp
      (fun x : Point3 =>
        (g x) ^ 3)
      (ENNReal.ofReal (4 / 3 : ℝ))
      volume := by
  have hAbsCube :=
    hg4.norm_rpow_div
      (ENNReal.ofReal 3)

  rw [ennreal_four_div_three] at hAbsCube

  have hAbsCube' :
      MeasureTheory.MemLp
        (fun x : Point3 =>
          abs (g x) ^ 3)
        (ENNReal.ofReal (4 / 3 : ℝ))
        volume := by
    simpa [Real.norm_eq_abs] using
      hAbsCube

  have hCubeMeas :
      MeasureTheory.AEStronglyMeasurable
        (fun x : Point3 =>
          (g x) ^ 3)
        volume :=
    hg4.aestronglyMeasurable.pow 3

  apply
    hAbsCube'.congr_norm
      hCubeMeas

  filter_upwards with x

  simp [
    Real.norm_eq_abs,
    abs_pow
  ]

/-- A scalar envelope makes `v` an `L∞` field, with no finite-volume
assumption on `Point3`. -/
theorem memLp_top_of_landauScalarEnvelope
    {v : ScalarField3}
    {h : ℝ}
    (hVMeas :
      MeasureTheory.AEStronglyMeasurable
        v
        volume)
    (hEnv :
      LandauScalarEnvelope
        v h) :
    MeasureTheory.MemLp
      v
      (⊤ : ℝ≥0∞)
      volume := by
  rcases hEnv with
    ⟨hh, hPointwise⟩

  refine
    ⟨
      hVMeas,
      ?_
    ⟩

  rw [
    eLpNorm_exponent_top
  ]

  apply
    eLpNormEssSup_lt_top_of_ae_bound

  filter_upwards with x

  simpa [Real.norm_eq_abs] using
    hPointwise x

/-- The bounded cubic factor belongs to the Hölder-conjugate space
`L^(4/3)`. -/
theorem memLp_four_thirds_bounded_cube
    {v g : ScalarField3}
    {h : ℝ}
    (hVMeas :
      MeasureTheory.AEStronglyMeasurable
        v
        volume)
    (hEnv :
      LandauScalarEnvelope
        v h)
    (hg4 :
      MeasureTheory.MemLp
        g
        (ENNReal.ofReal 4)
        volume) :
    MeasureTheory.MemLp
      (fun x : Point3 =>
        v x * (g x) ^ 3)
      (ENNReal.ofReal (4 / 3 : ℝ))
      volume := by
  let p : ℝ≥0∞ :=
    ENNReal.ofReal (4 / 3 : ℝ)

  let cube : Point3 → ℝ :=
    fun x : Point3 =>
      (g x) ^ 3

  have hCube :
      MeasureTheory.MemLp
        cube
        p
        volume := by
    dsimp [cube, p]

    exact
      memLp_four_thirds_cube_of_memLp_four
        hg4

  have hVTop :
      MeasureTheory.MemLp
        v
        (⊤ : ℝ≥0∞)
        volume :=
    memLp_top_of_landauScalarEnvelope
      hVMeas
      hEnv

  have hProdMeas :
      MeasureTheory.AEStronglyMeasurable
        (fun x : Point3 =>
          v x * cube x)
        volume :=
    hVMeas.mul
      hCube.aestronglyMeasurable

  have hNormBound :
      eLpNorm
          (fun x : Point3 =>
            v x * cube x)
          p
          volume
        ≤
      eLpNorm
          v
          (⊤ : ℝ≥0∞)
          volume
        *
      eLpNorm
          cube
          p
          volume := by
    have hRaw :=
      eLpNorm_le_eLpNorm_top_mul_eLpNorm
        (μ := volume)
        (p := p)
        v
        hCube.aestronglyMeasurable
        (fun a b : ℝ => a * b)
        (1 : ℝ≥0)
        (
          Filter.Eventually.of_forall
            (fun x : Point3 => by
              simp)
        )

    simpa using
      hRaw

  refine
    ⟨
      hProdMeas,
      ?_
    ⟩

  calc
    eLpNorm
        (fun x : Point3 =>
          v x * cube x)
        p
        volume
        ≤
      eLpNorm
          v
          (⊤ : ℝ≥0∞)
          volume
        *
      eLpNorm
          cube
          p
          volume :=
        hNormBound

    _ < ⊤ :=
      ENNReal.mul_lt_top
        hVTop.eLpNorm_lt_top
        hCube.eLpNorm_lt_top

end

end Euclidean
end Bridge
end PrimeTensor
