import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.ComplementEndpointFactorBKMNativeFullTailBalanceAmplitudeMinimalVorticityPhysicalLongitudinalEquatorialVorticityPhysicalDissipationConcentrationCompactnessDichotomy

/-!
# Frequency escape versus dissipation-density blowup

The preceding concentration--compactness checkpoint gives two possible analytic
obstructions under hypothetical nonextension:

* fixed positive H³ dissipation mass can escape to arbitrarily large radial
  frequencies; or
* fixed positive H³ dissipation mass can concentrate on sets whose
  Fourier-space volume tends to zero.

This file converts those measure-level alternatives into pointwise frequency
statements without adding any higher-regularity hypothesis.

In the radial-escape branch we select actual frequencies `ξₙ` with

    n + 1 ≤ |D(ξₙ)|

and strictly positive physical H³ dissipation density.  Hence the selected
radial frequencies tend to infinity.

In the small-volume branch, mass at least `δ` inside a set of volume below
`1/(n+1)` forces some point of that set to have dissipation density strictly
larger than

    δ (n + 1).

Thus that selected density tends to infinity.

The resulting alternative is a frequency-escape versus density-amplification
statement.  It remains conditional on hypothetical nonextension and does not
assert existence of a singular solution.
-/

namespace PrimeTensor
namespace Bridge
namespace Euclidean

open Set Filter MeasureTheory FourierTransform Function
open scoped BigOperators ENNReal NNReal Interval Topology

noncomputable section

noncomputable local instance axisFintypeH3TerminalPhysicalDissipationFrequencyEscapeDensityBlowup
    (d : Depth) :
    Fintype (PrimeTensor.Axis d) :=
  Fintype.ofFinite (PrimeTensor.Axis d)

noncomputable local instance point3MeasureSpaceH3TerminalPhysicalDissipationFrequencyEscapeDensityBlowup :
    MeasureSpace Point3 :=
  @MeasureTheory.MeasureSpace.pi
    (PrimeTensor.Axis Depth.three)
    (Fintype.ofFinite (PrimeTensor.Axis Depth.three))
    (fun _ : PrimeTensor.Axis Depth.three => ℝ)
    (fun _ : PrimeTensor.Axis Depth.three => Real.measureSpace)

/-! ## Point-sequence packages -/

/--
Pointwise frequency escape of physical H³ dissipation.

The selected frequencies move to arbitrarily large radial derivative scale and
carry strictly positive dissipation density.
-/
def H3TerminalPhysicalDissipationFrequencyEscapePointSequence
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T a : ℝ}
    (hH3 : LoggedPreterminalH3PathAdmissible u T)
    (hClass : PreterminalH3EnergyClass u a T) : Prop :=
  ∃ δ : ℝ,
    0 < δ
      ∧
    ∃ τ : ℕ → ℝ,
      ∃ ξ : ℕ → H3FourierPoint3,
        ∃ hτ : ∀ n : ℕ, τ n ∈ Set.Ioo a T,
          (
            ∀ n : ℕ,
              dist (τ n) T
                  <
                (1 : ℝ) / ((n : ℝ) + 1)
                ∧
              (n : ℝ) + 1
                  ≤
                h3FourierGradientMagnitude (ξ n)
                ∧
              0
                  <
                h3TerminalSpectralDissipationSingleDensity
                  (h3TerminalVelocitySpectralStateAt
                    hH3
                    (τ n)
                    ⟨
                      lt_trans hClass.terminal_start.1 (hτ n).1,
                      (hτ n).2
                    ⟩)
                  (ξ n)
          )
            ∧
          Tendsto τ atTop (𝓝 T)
            ∧
          Tendsto
            (fun n : ℕ =>
              h3FourierGradientMagnitude (ξ n))
            atTop
            atTop

/--
Pointwise blowup of the physical H³ spectral dissipation density generated by
small-volume concentration.
-/
def H3TerminalPhysicalDissipationDensityBlowupPointSequence
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T a : ℝ}
    (hH3 : LoggedPreterminalH3PathAdmissible u T)
    (hClass : PreterminalH3EnergyClass u a T) : Prop :=
  ∃ δ : ℝ,
    0 < δ
      ∧
    ∃ τ : ℕ → ℝ,
      ∃ ξ : ℕ → H3FourierPoint3,
        ∃ hτ : ∀ n : ℕ, τ n ∈ Set.Ioo a T,
          (
            ∀ n : ℕ,
              dist (τ n) T
                  <
                (1 : ℝ) / ((n : ℝ) + 1)
                ∧
              δ * ((n : ℝ) + 1)
                  <
                h3TerminalSpectralDissipationSingleDensity
                  (h3TerminalVelocitySpectralStateAt
                    hH3
                    (τ n)
                    ⟨
                      lt_trans hClass.terminal_start.1 (hτ n).1,
                      (hτ n).2
                    ⟩)
                  (ξ n)
          )
            ∧
          Tendsto τ atTop (𝓝 T)
            ∧
          Tendsto
            (fun n : ℕ =>
              h3TerminalSpectralDissipationSingleDensity
                (h3TerminalVelocitySpectralStateAt
                  hH3
                  (τ n)
                  ⟨
                    lt_trans hClass.terminal_start.1 (hτ n).1,
                    (hτ n).2
                  ⟩)
                (ξ n))
            atTop
            atTop

/-! ## Elementary sequence utilities -/

private theorem tendsto_atTop_of_natSucc_le
    {f : ℕ → ℝ}
    (hf :
      ∀ n : ℕ,
        (n : ℝ) + 1 ≤ f n) :
    Tendsto f atTop atTop := by

  refine tendsto_atTop.2 ?_

  intro M

  obtain ⟨N : ℕ, hN⟩ :=
    exists_nat_gt M

  filter_upwards [eventually_ge_atTop N] with n hn

  have hCast :
      (N : ℝ) ≤ n := by
    exact_mod_cast hn

  have hM :
      M < (n : ℝ) + 1 := by
    linarith

  exact
    le_trans
      hM.le
      (hf n)

private theorem tendsto_atTop_of_pos_mul_natSucc_lt
    {δ : ℝ}
    (hδ : 0 < δ)
    {f : ℕ → ℝ}
    (hf :
      ∀ n : ℕ,
        δ * ((n : ℝ) + 1) < f n) :
    Tendsto f atTop atTop := by

  refine tendsto_atTop.2 ?_

  intro M

  obtain ⟨N : ℕ, hN⟩ :=
    exists_nat_gt (M / δ)

  filter_upwards [eventually_ge_atTop N] with n hn

  have hCast :
      (N : ℝ) ≤ n := by
    exact_mod_cast hn

  have hMND :
      M < (N : ℝ) * δ :=
    (div_lt_iff₀ hδ).1 hN

  have hNDle :
      (N : ℝ) * δ
        ≤
      ((n : ℝ) + 1) * δ := by
    exact
      mul_le_mul_of_nonneg_right
        (by linarith)
        hδ.le

  have hMScale :
      M < δ * ((n : ℝ) + 1) := by
    have h :=
      lt_of_lt_of_le
        hMND
        hNDle
    simpa only [mul_comm] using h

  exact
    le_of_lt
      (lt_trans hMScale (hf n))

/-! ## Positive mass contains a positive-density frequency -/

/--
A measurable set carrying strictly positive physical H³ dissipation mass
contains a frequency where the canonical dissipation density is strictly
positive.
-/
theorem exists_mem_positive_spectralDissipationDensity_of_positive_setMass
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T a t : ℝ}
    (hH3 : LoggedPreterminalH3PathAdmissible u T)
    (hClass : PreterminalH3EnergyClass u a T)
    (ht : t ∈ Set.Ioo a T)
    (S : Set H3FourierPoint3)
    (hSMeas : MeasurableSet S)
    (hMass :
      0 <
        h3TerminalPhysicalDissipationSetMassAt
          hH3 hClass t ht S) :
    ∃ ξ : H3FourierPoint3,
      ξ ∈ S
        ∧
      0 <
        h3TerminalSpectralDissipationSingleDensity
          (h3TerminalVelocitySpectralStateAt
            hH3
            t
            ⟨
              lt_trans hClass.terminal_start.1 ht.1,
              ht.2
            ⟩)
          ξ := by

  let f : H3FourierPoint3 → ℝ :=
    fun ξ =>
      h3TerminalSpectralDissipationSingleDensity
        (h3TerminalVelocitySpectralStateAt
          hH3
          t
          ⟨
            lt_trans hClass.terminal_start.1 ht.1,
            ht.2
          ⟩)
        ξ

  have hInt :
      Integrable f volume := by
    dsimp only [f]
    simpa only using
      (h3TerminalSpectralDissipationSingleDensity_integrable
        hH3 hClass ht)

  have hNonneg :
      0 ≤ᵐ[volume.restrict S] f := by
    filter_upwards with ξ
    exact
      h3TerminalSpectralDissipationSingleDensity_nonneg
        (h3TerminalVelocitySpectralStateAt
          hH3
          t
          ⟨
            lt_trans hClass.terminal_start.1 ht.1,
            ht.2
          ⟩)
        ξ

  have hMass' :
      0 < ∫ ξ in S, f ξ ∂volume := by
    simpa only [
      h3TerminalPhysicalDissipationSetMassAt,
      f
    ] using hMass

  have hSupportMeasure :
      0 < volume (Function.support f ∩ S) :=
    (setIntegral_pos_iff_support_of_nonneg_ae
      hNonneg
      hInt.integrableOn).1
      hMass'

  obtain ⟨ξ, hξSupport, hξS⟩ :=
    nonempty_of_measure_ne_zero
      hSupportMeasure.ne'

  have hξNe :
      f ξ ≠ 0 := by
    exact hξSupport

  have hξNonneg :
      0 ≤ f ξ :=
    h3TerminalSpectralDissipationSingleDensity_nonneg
      (h3TerminalVelocitySpectralStateAt
        hH3
        t
        ⟨
          lt_trans hClass.terminal_start.1 ht.1,
          ht.2
        ⟩)
      ξ

  refine
    ⟨
      ξ,
      hξS,
      ?_
    ⟩

  dsimp only [f] at hξNe hξNonneg ⊢

  exact
    lt_of_le_of_ne
      hξNonneg
      hξNe.symm

/-! ## Radial mass escape gives frequency escape -/

/--
Every radial-escape mass sequence contains a pointwise radial-frequency escape
sequence with positive dissipation density.
-/
theorem physicalDissipationFrequencyEscapePointSequence_of_radialEscapeSequence
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T a : ℝ}
    (hH3 : LoggedPreterminalH3PathAdmissible u T)
    (hClass : PreterminalH3EnergyClass u a T)
    (hEscape :
      H3TerminalPhysicalDissipationRadialEscapeSequence
        hH3 hClass) :
    H3TerminalPhysicalDissipationFrequencyEscapePointSequence
      hH3 hClass := by

  classical

  obtain
    ⟨
      δ,
      hδ,
      τ,
      S,
      hData,
      hτTendsto
    ⟩ :=
    hEscape

  have hChoice :
      ∀ n : ℕ,
        ∃ ξ : H3FourierPoint3,
          ∃ ht : τ n ∈ Set.Ioo a T,
            dist (τ n) T
                <
              (1 : ℝ) / ((n : ℝ) + 1)
              ∧
            (n : ℝ) + 1
                ≤
              h3FourierGradientMagnitude ξ
              ∧
            0
                <
              h3TerminalSpectralDissipationSingleDensity
                (h3TerminalVelocitySpectralStateAt
                  hH3
                  (τ n)
                  ⟨
                    lt_trans hClass.terminal_start.1 ht.1,
                    ht.2
                  ⟩)
                ξ := by

    intro n

    obtain
      ⟨
        ht,
        hNear,
        hSMeas,
        hSSubset,
        hMass
      ⟩ :=
      hData n

    have hMassPos :
        0 <
          h3TerminalPhysicalDissipationSetMassAt
            hH3 hClass (τ n) ht (S n) :=
      lt_of_lt_of_le
        hδ
        hMass

    obtain
      ⟨ξ, hξS, hξPositive⟩ :=
      exists_mem_positive_spectralDissipationDensity_of_positive_setMass
        hH3
        hClass
        ht
        (S n)
        hSMeas
        hMassPos

    have hOutside :=
      hSSubset hξS

    have hRadial :
        (n : ℝ) + 1
          ≤
        h3FourierGradientMagnitude ξ := by
      change
        ¬
          h3FourierGradientMagnitude ξ
            <
          (n : ℝ) + 1
        at hOutside
      exact le_of_not_gt hOutside

    exact
      ⟨
        ξ,
        ht,
        hNear,
        hRadial,
        hξPositive
      ⟩

  choose ξ hτ hPoint using hChoice

  have hRadialTendsto :
      Tendsto
        (fun n : ℕ =>
          h3FourierGradientMagnitude (ξ n))
        atTop
        atTop :=
    tendsto_atTop_of_natSucc_le
      (fun n => (hPoint n).2.1)

  refine
    ⟨
      δ,
      hδ,
      τ,
      ξ,
      hτ,
      ?_,
      hτTendsto,
      hRadialTendsto
    ⟩

  intro n

  exact hPoint n

/-! ## Small-volume mass concentration gives density blowup -/

/--
If a measurable set has volume below `1/(n+1)` but carries mass at least
`δ > 0`, then its physical H³ dissipation density exceeds `δ(n+1)` at some
frequency.
-/
theorem exists_mem_spectralDissipationDensity_gt_linear_of_smallVolume_setMass
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T a t : ℝ}
    (hH3 : LoggedPreterminalH3PathAdmissible u T)
    (hClass : PreterminalH3EnergyClass u a T)
    (ht : t ∈ Set.Ioo a T)
    (S : Set H3FourierPoint3)
    (hSMeas : MeasurableSet S)
    {δ : ℝ}
    (hδ : 0 < δ)
    (n : ℕ)
    (hVolume :
      volume S
        <
      ENNReal.ofReal
        ((1 : ℝ) / ((n : ℝ) + 1)))
    (hMass :
      δ
        ≤
      h3TerminalPhysicalDissipationSetMassAt
        hH3 hClass t ht S) :
    ∃ ξ : H3FourierPoint3,
      ξ ∈ S
        ∧
      δ * ((n : ℝ) + 1)
        <
      h3TerminalSpectralDissipationSingleDensity
        (h3TerminalVelocitySpectralStateAt
          hH3
          t
          ⟨
            lt_trans hClass.terminal_start.1 ht.1,
            ht.2
          ⟩)
        ξ := by

  let f : H3FourierPoint3 → ℝ :=
    fun ξ =>
      h3TerminalSpectralDissipationSingleDensity
        (h3TerminalVelocitySpectralStateAt
          hH3
          t
          ⟨
            lt_trans hClass.terminal_start.1 ht.1,
            ht.2
          ⟩)
        ξ

  have hScale :
      0 < (1 : ℝ) / ((n : ℝ) + 1) := by
    positivity

  have hVolumeLtTop :
      volume S < ∞ :=
    hVolume.trans
      (by simp)

  have hVolumeNeTop :
      volume S ≠ ∞ :=
    ne_of_lt hVolumeLtTop

  have hVolumeReal :
      volume.real S
        <
      (1 : ℝ) / ((n : ℝ) + 1) := by
    have hToReal :=
      (ENNReal.toReal_lt_toReal
        hVolumeNeTop
        ENNReal.ofReal_ne_top).2
        hVolume
    simpa only [
      measureReal_def,
      ENNReal.toReal_ofReal hScale.le
    ] using hToReal

  by_contra hNoPoint
  push Not at hNoPoint

  have hPointwiseNorm :
      ∀ ξ : H3FourierPoint3,
        ξ ∈ S
          →
        ‖f ξ‖
          ≤
        δ * ((n : ℝ) + 1) := by

    intro ξ hξ

    have hBound :=
      hNoPoint ξ hξ

    have hNonneg :
        0 ≤ f ξ :=
      h3TerminalSpectralDissipationSingleDensity_nonneg
        (h3TerminalVelocitySpectralStateAt
          hH3
          t
          ⟨
            lt_trans hClass.terminal_start.1 ht.1,
            ht.2
          ⟩)
        ξ

    rw [
      Real.norm_eq_abs,
      abs_of_nonneg hNonneg
    ]

    exact hBound

  have hIntegralNormLe :
      ‖∫ ξ in S, f ξ ∂volume‖
        ≤
      (δ * ((n : ℝ) + 1))
        *
      volume.real S :=
    norm_setIntegral_le_of_norm_le_const
      hVolumeLtTop
      hPointwiseNorm

  have hIntegralNonneg :
      0 ≤ ∫ ξ in S, f ξ ∂volume := by
    exact
      setIntegral_nonneg
        hSMeas
        (fun ξ _ =>
          h3TerminalSpectralDissipationSingleDensity_nonneg
            (h3TerminalVelocitySpectralStateAt
              hH3
              t
              ⟨
                lt_trans hClass.terminal_start.1 ht.1,
                ht.2
              ⟩)
            ξ)

  have hIntegralLe :
      (∫ ξ in S, f ξ ∂volume)
        ≤
      (δ * ((n : ℝ) + 1))
        *
      volume.real S := by
    rw [← Real.norm_of_nonneg hIntegralNonneg]
    exact hIntegralNormLe

  have hCoefficientPos :
      0 < δ * ((n : ℝ) + 1) := by
    positivity

  have hProductLt :
      (δ * ((n : ℝ) + 1))
          *
        volume.real S
        <
      δ := by

    have hMul :=
      mul_lt_mul_of_pos_left
        hVolumeReal
        hCoefficientPos

    calc
      (δ * ((n : ℝ) + 1))
          *
        volume.real S
          <
        (δ * ((n : ℝ) + 1))
          *
        ((1 : ℝ) / ((n : ℝ) + 1)) :=
          hMul
      _ = δ := by
        have hDen :
            ((n : ℝ) + 1) ≠ 0 := by
          positivity
        field_simp

  have hMass' :
      δ ≤ ∫ ξ in S, f ξ ∂volume := by
    simpa only [
      h3TerminalPhysicalDissipationSetMassAt,
      f
    ] using hMass

  have hContradiction :
      (∫ ξ in S, f ξ ∂volume) < δ :=
    lt_of_le_of_lt
      hIntegralLe
      hProductLt

  exact
    (not_lt_of_ge hMass')
      hContradiction

/--
Every small-volume concentration sequence contains a pointwise dissipation
density blowup sequence.
-/
theorem physicalDissipationDensityBlowupPointSequence_of_smallVolumeConcentrationSequence
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T a : ℝ}
    (hH3 : LoggedPreterminalH3PathAdmissible u T)
    (hClass : PreterminalH3EnergyClass u a T)
    (hConcentration :
      H3TerminalPhysicalDissipationSmallVolumeConcentrationSequence
        hH3 hClass) :
    H3TerminalPhysicalDissipationDensityBlowupPointSequence
      hH3 hClass := by

  classical

  obtain
    ⟨
      δ,
      hδ,
      τ,
      S,
      hData,
      hτTendsto
    ⟩ :=
    hConcentration

  have hChoice :
      ∀ n : ℕ,
        ∃ ξ : H3FourierPoint3,
          ∃ ht : τ n ∈ Set.Ioo a T,
            dist (τ n) T
                <
              (1 : ℝ) / ((n : ℝ) + 1)
              ∧
            δ * ((n : ℝ) + 1)
                <
              h3TerminalSpectralDissipationSingleDensity
                (h3TerminalVelocitySpectralStateAt
                  hH3
                  (τ n)
                  ⟨
                    lt_trans hClass.terminal_start.1 ht.1,
                    ht.2
                  ⟩)
                ξ := by

    intro n

    obtain
      ⟨
        ht,
        hNear,
        hSMeas,
        hVolume,
        hMass
      ⟩ :=
      hData n

    obtain
      ⟨ξ, hξS, hDensity⟩ :=
      exists_mem_spectralDissipationDensity_gt_linear_of_smallVolume_setMass
        hH3
        hClass
        ht
        (S n)
        hSMeas
        hδ
        n
        hVolume
        hMass

    exact
      ⟨
        ξ,
        ht,
        hNear,
        hDensity
      ⟩

  choose ξ hτ hPoint using hChoice

  have hDensityTendsto :
      Tendsto
        (fun n : ℕ =>
          h3TerminalSpectralDissipationSingleDensity
            (h3TerminalVelocitySpectralStateAt
              hH3
              (τ n)
              ⟨
                lt_trans hClass.terminal_start.1 (hτ n).1,
                (hτ n).2
              ⟩)
            (ξ n))
        atTop
        atTop :=
    tendsto_atTop_of_pos_mul_natSucc_lt
      hδ
      (fun n => (hPoint n).2)

  refine
    ⟨
      δ,
      hδ,
      τ,
      ξ,
      hτ,
      ?_,
      hτTendsto,
      hDensityTendsto
    ⟩

  intro n

  exact hPoint n

/-! ## Final pointwise concentration--compactness alternative -/

/--
Under the retained endpoint hypotheses and hypothetical nonextension, physical
H³ dissipation either escapes to frequencies whose radial derivative scale
tends to infinity, or its spectral density itself tends to infinity along a
terminal point sequence.
-/
theorem physicalDissipationFrequencyEscape_or_densityBlowup_of_velocityRawFourierL2Cauchy_of_actualVorticityStrongH3EndpointPath_of_noH3PathExtension
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T a : ℝ}
    (hH3 : LoggedPreterminalH3PathAdmissible u T)
    (hNoExtension :
      ¬ ∃ v : SpaceTimeVectorField ℝ ℝ MulReal Depth.three,
          SmoothContinuationExtension u v T)
    (hClass : PreterminalH3EnergyClass u a T)
    {i : Fin 3}
    (hPhysical :
      H3TerminalActualVorticityStrongH3EndpointPath hH3 i)
    (hCauchy :
      H3TerminalVelocityRawFourierL2CauchyAtEndpoint hH3) :
    H3TerminalPhysicalDissipationFrequencyEscapePointSequence
        hH3 hClass
      ∨
    H3TerminalPhysicalDissipationDensityBlowupPointSequence
        hH3 hClass := by

  rcases
      physicalDissipationRadialEscape_or_smallVolumeConcentration_of_velocityRawFourierL2Cauchy_of_actualVorticityStrongH3EndpointPath_of_noH3PathExtension
        hH3
        hNoExtension
        hClass
        hPhysical
        hCauchy
    with hEscape | hConcentration

  · exact
      Or.inl
        (physicalDissipationFrequencyEscapePointSequence_of_radialEscapeSequence
          hH3 hClass hEscape)

  · exact
      Or.inr
        (physicalDissipationDensityBlowupPointSequence_of_smallVolumeConcentrationSequence
          hH3 hClass hConcentration)

/--
Neutral formulation: under the retained endpoint hypotheses, either the path
extends smoothly through `T`, or physical H³ dissipation has a pointwise
frequency-escape sequence, or its spectral dissipation density has a pointwise
blowup sequence.
-/
theorem smoothContinuationExtension_or_physicalDissipationFrequencyEscape_or_densityBlowup
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T a : ℝ}
    (hH3 : LoggedPreterminalH3PathAdmissible u T)
    (hClass : PreterminalH3EnergyClass u a T)
    {i : Fin 3}
    (hPhysical :
      H3TerminalActualVorticityStrongH3EndpointPath hH3 i)
    (hCauchy :
      H3TerminalVelocityRawFourierL2CauchyAtEndpoint hH3) :
    (
      ∃ v : SpaceTimeVectorField ℝ ℝ MulReal Depth.three,
        SmoothContinuationExtension u v T
    )
      ∨
    H3TerminalPhysicalDissipationFrequencyEscapePointSequence
        hH3 hClass
      ∨
    H3TerminalPhysicalDissipationDensityBlowupPointSequence
        hH3 hClass := by

  classical

  by_cases hExtension :
      ∃ v : SpaceTimeVectorField ℝ ℝ MulReal Depth.three,
        SmoothContinuationExtension u v T

  · exact Or.inl hExtension

  · exact
      Or.inr
        (physicalDissipationFrequencyEscape_or_densityBlowup_of_velocityRawFourierL2Cauchy_of_actualVorticityStrongH3EndpointPath_of_noH3PathExtension
          hH3
          hExtension
          hClass
          hPhysical
          hCauchy)

end

end Euclidean
end Bridge
end PrimeTensor
