import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.NativeResidualIntrinsicFiniteCoreTrace

/-!
# Selected-closure terminal trace

The terminal selected spatial modulus does more than make one previously found
finite-core trace independent of its witness sequence.

It gives a general trace theory on the sequential closure of the selected
spatial set.

A selected spatial cluster point is any point `y` approached by some sequence
of selected points `x (k j)`.  A selected-closure terminal trace at `y` is a
real number `L` obtained as the limit of the actual terminal
complementary-gradient values along such an approach.

Under the terminal selected spatial modulus:

* every selected spatial cluster point admits a terminal trace;
* that trace is unique;
* any two selected approaches to the same cluster point give the same limit.

Thus the actual terminal complementary-gradient field has a canonical
sequential trace on the closure generated by the selected points, even though
ambient continuity at those closure points has not been assumed.

The previously isolated finite nonzero residual core therefore determines a
nonzero intrinsic selected-closure trace.  This removes the residual native
factor and witness subsequence from the geometric statement itself.
-/

namespace PrimeTensor
namespace Bridge
namespace Euclidean

open Set Filter MeasureTheory
open scoped BigOperators ENNReal NNReal Interval Topology

noncomputable section

noncomputable local instance axisFintypeH3TerminalResidualSelectedClosureTrace
    (d : Depth) :
    Fintype (PrimeTensor.Axis d) :=
  Fintype.ofFinite (PrimeTensor.Axis d)

/-! ## Sequential selected closure and trace relation -/

/--
A point lies in the sequential closure generated by the selected spatial
sequence when some selected subsequence converges to it.
-/
def H3TerminalSelectedSpatialClusterPoint
    (x : ℕ → Point3)
    (y : Point3) : Prop :=
  ∃ k : ℕ → ℕ,
    Tendsto
      (fun j : ℕ => x (k j))
      atTop
      (𝓝 y)

/--
`L` is a selected-closure terminal trace at `y` if some selected spatial
approach to `y` has actual terminal complementary-gradient values converging
to `L`.
-/
def H3TerminalComplementGradientSelectedClosureTraceAt
    (u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three)
    (p : H3TerminalCurlGradientPair)
    (x : ℕ → Point3)
    (T : ℝ)
    (y : Point3)
    (L : ℝ) : Prop :=
  ∃ k : ℕ → ℕ,
    Tendsto
        (fun j : ℕ => x (k j))
        atTop
        (𝓝 y)
      ∧
    Tendsto
      (
        fun j : ℕ =>
          h3TerminalComplementGradientFieldForPair
            u p
            T
            (x (k j))
      )
      atTop
      (𝓝 L)

/-! ## Existence of selected-closure traces -/

/--
Under the terminal selected spatial modulus, the terminal
complementary-gradient values along every convergent selected spatial approach
form a Cauchy sequence.
-/
theorem terminalValues_cauchySeq_of_selectedPoint_tendsto_of_terminalSpatialModulus
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {p : H3TerminalCurlGradientPair}
    {x : ℕ → Point3}
    {T : ℝ}
    {y : Point3}
    {k : ℕ → ℕ}
    (hModulus :
      H3TerminalComplementGradientSelectedTerminalSpatialUniformModulus
        u p x T)
    (hPoint :
      Tendsto
        (fun j : ℕ => x (k j))
        atTop
        (𝓝 y)) :
    CauchySeq
      (
        fun j : ℕ =>
          h3TerminalComplementGradientFieldForPair
            u p
            T
            (x (k j))
      ) := by

  have hPointCauchy :
      CauchySeq
        (fun j : ℕ => x (k j)) :=
    hPoint.cauchySeq

  rw [Metric.cauchySeq_iff]

  intro ε hε

  obtain
    ⟨
      η,
      hη,
      hUniform
    ⟩ :=
    hModulus
      ε
      hε

  obtain
    ⟨
      N,
      hN
    ⟩ :=
    (
      Metric.cauchySeq_iff.1
        hPointCauchy
    )
      η
      hη

  refine
    ⟨
      N,
      ?_
    ⟩

  intro m hm n hn

  exact
    hUniform
      (k m)
      (k n)
      (
        hN
          m hm
          n hn
      )

/--
Every selected spatial cluster point has at least one selected-closure terminal
trace under the terminal selected spatial modulus.
-/
theorem exists_selectedClosureTrace_of_clusterPoint_of_terminalSpatialModulus
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {p : H3TerminalCurlGradientPair}
    {x : ℕ → Point3}
    {T : ℝ}
    {y : Point3}
    (hModulus :
      H3TerminalComplementGradientSelectedTerminalSpatialUniformModulus
        u p x T)
    (hCluster :
      H3TerminalSelectedSpatialClusterPoint
        x y) :
    ∃ L : ℝ,
      H3TerminalComplementGradientSelectedClosureTraceAt
        u p x T y L := by

  obtain
    ⟨
      k,
      hPoint
    ⟩ :=
    hCluster

  have hCauchy :
      CauchySeq
        (
          fun j : ℕ =>
            h3TerminalComplementGradientFieldForPair
              u p
              T
              (x (k j))
        ) :=
    terminalValues_cauchySeq_of_selectedPoint_tendsto_of_terminalSpatialModulus
      hModulus
      hPoint

  obtain
    ⟨
      L,
      hLimit
    ⟩ :=
    cauchySeq_tendsto_of_complete
      hCauchy

  exact
    ⟨
      L,
      k,
      hPoint,
      hLimit
    ⟩

/-! ## Uniqueness of selected-closure traces -/

/--
Under the terminal selected spatial modulus, a selected spatial cluster point
has at most one terminal trace.
-/
theorem selectedClosureTrace_unique_of_terminalSpatialModulus
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {p : H3TerminalCurlGradientPair}
    {x : ℕ → Point3}
    {T : ℝ}
    {y : Point3}
    {L₁ L₂ : ℝ}
    (hModulus :
      H3TerminalComplementGradientSelectedTerminalSpatialUniformModulus
        u p x T)
    (hTrace₁ :
      H3TerminalComplementGradientSelectedClosureTraceAt
        u p x T y L₁)
    (hTrace₂ :
      H3TerminalComplementGradientSelectedClosureTraceAt
        u p x T y L₂) :
    L₁ = L₂ := by

  obtain
    ⟨
      k₁,
      hPoint₁,
      hLimit₁
    ⟩ :=
    hTrace₁

  obtain
    ⟨
      k₂,
      hPoint₂,
      hLimit₂
    ⟩ :=
    hTrace₂

  have hLimit₂ToL₁ :
      Tendsto
        (
          fun j : ℕ =>
            h3TerminalComplementGradientFieldForPair
              u p
              T
              (x (k₂ j))
        )
        atTop
        (𝓝 L₁) :=
    terminalTrace_tendsto_of_sameSelectedCluster_of_terminalSpatialModulus
      hModulus
      hPoint₁
      hLimit₁
      hPoint₂

  exact
    tendsto_nhds_unique
      hLimit₂ToL₁
      hLimit₂

/--
Every selected spatial cluster point has a unique selected-closure terminal
trace under the terminal selected spatial modulus.
-/
theorem existsUnique_selectedClosureTrace_of_clusterPoint_of_terminalSpatialModulus
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {p : H3TerminalCurlGradientPair}
    {x : ℕ → Point3}
    {T : ℝ}
    {y : Point3}
    (hModulus :
      H3TerminalComplementGradientSelectedTerminalSpatialUniformModulus
        u p x T)
    (hCluster :
      H3TerminalSelectedSpatialClusterPoint
        x y) :
    ∃! L : ℝ,
      H3TerminalComplementGradientSelectedClosureTraceAt
        u p x T y L := by

  obtain
    ⟨
      L,
      hTrace
    ⟩ :=
    exists_selectedClosureTrace_of_clusterPoint_of_terminalSpatialModulus
      hModulus
      hCluster

  refine
    ⟨
      L,
      hTrace,
      ?_
    ⟩

  intro L' hTrace'

  exact
    selectedClosureTrace_unique_of_terminalSpatialModulus
      hModulus
      hTrace'
      hTrace

/-! ## Nonzero intrinsic selected-closure trace -/

/--
The selected closure contains a point carrying a unique nonzero terminal trace.
-/
def H3TerminalComplementGradientHasNonzeroIntrinsicSelectedClosureTrace
    (u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three)
    (p : H3TerminalCurlGradientPair)
    (x : ℕ → Point3)
    (T : ℝ) : Prop :=
  ∃ y : Point3,
    ∃ L : ℝ,
      L ≠ 0
        ∧
      H3TerminalComplementGradientSelectedClosureTraceAt
        u p x T y L
        ∧
      ∀ L' : ℝ,
        H3TerminalComplementGradientSelectedClosureTraceAt
            u p x T y L'
          →
        L' = L

/--
A distinct intrinsic finite terminal trace channel yields a nonzero intrinsic
selected-closure trace.
-/
theorem nonzeroIntrinsicSelectedClosureTrace_of_distinctIntrinsicFiniteTerminalTrace
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {p : H3TerminalCurlGradientPair}
    {τ : ℕ → ℝ}
    {x : ℕ → Point3}
    {T : ℝ}
    (hModulus :
      H3TerminalComplementGradientSelectedTerminalSpatialUniformModulus
        u p x T)
    (hTrace :
      H3TerminalNativeComplementHasDistinctIntrinsicFiniteTerminalTraceChannel
        u p τ x T) :
    H3TerminalComplementGradientHasNonzeroIntrinsicSelectedClosureTrace
      u p x T := by

  obtain
    ⟨
      q,
      _hqNe,
      hqLogNe,
      y,
      k,
      _hkTop,
      _hTime,
      hPoint,
      _hFactor,
      hTerminal,
      _hIntrinsic
    ⟩ :=
    hTrace

  let L : ℝ :=
    PrimeTensor.Bridge.MulReal.logValue q

  have hLNe :
      L ≠ 0 := by

    simpa only [L] using
      hqLogNe

  have hTraceAt :
      H3TerminalComplementGradientSelectedClosureTraceAt
        u p x T y L := by

    exact
      ⟨
        k,
        hPoint,
        by simpa only [L] using hTerminal
      ⟩

  refine
    ⟨
      y,
      L,
      hLNe,
      hTraceAt,
      ?_
    ⟩

  intro L' hTrace'

  exact
    selectedClosureTrace_unique_of_terminalSpatialModulus
      hModulus
      hTrace'
      hTraceAt

/-! ## Closure-level escape-side package -/

/--
The escape-side obstruction, stated without retaining the particular finite
native factor or its witness subsequence:

* a native pivot cluster at spatial infinity;
* a nonzero intrinsic terminal trace on the selected spatial closure; and
* quantitative contrast between a finite core and every selected route to
  infinity.
-/
def H3TerminalNativeComplementHasPivotInfinityAndNonzeroClosureTrace
    (u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three)
    (p : H3TerminalCurlGradientPair)
    (τ : ℕ → ℝ)
    (x : ℕ → Point3)
    (T : ℝ) : Prop :=
  H3TerminalNativeComplementHasCofinalPivotClusterAtSpatialInfinity
      u p τ x T
    ∧
  H3TerminalComplementGradientHasNonzeroIntrinsicSelectedClosureTrace
      u p x T
    ∧
  H3TerminalComplementGradientHasFiniteCoreInfinityContrast
      u p x T

/--
Under endpoint temporal control, selected spatial equicontinuity, terminal
decay at infinity, and eventual boundedness of the residual logarithm, failure
of the canonical native factor forces either

* a pivot cluster at spatial infinity together with a nonzero intrinsic trace
  on the selected spatial closure and quantitative finite-core contrast; or
* bounded selected range with positive terminal spatial contrast and positive
  witness separation.
-/
theorem nativeComplement_noCanonicalFactor_forces_pivotInfinityAndNonzeroClosureTrace_or_boundedTerminalContrast
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {p : H3TerminalCurlGradientPair}
    {τ : ℕ → ℝ}
    {x : ℕ → Point3}
    {T : ℝ}
    (hTau :
      Tendsto τ atTop (𝓝 T))
    (hEndpoint :
      H3TerminalComplementGradientSelectedEndpointTemporalModulus
        u p τ x T)
    (hSpatialEquicontinuity :
      H3TerminalComplementGradientSelectedSpatialEquicontinuity
        u p τ x)
    (hDecay :
      H3TerminalComplementGradientSelectedTerminalDecayAtInfinity
        u p x T)
    (hResidualBounded :
      H3TerminalNativeComplementResidualLogEventuallyBounded
        u p τ x)
    (hNoFactor :
      ¬
        H3TerminalNativeComplementHasCanonicalFactor
          u p τ x) :
    H3TerminalNativeComplementHasPivotInfinityAndNonzeroClosureTrace
        u p τ x T
      ∨
    (
      Bornology.IsBounded (Set.range x)
        ∧
      H3TerminalComplementGradientHasPositiveSelectedTerminalSpatialContrastSeparation
        u p x T
    ) := by

  have hTerminalModulus :
      H3TerminalComplementGradientSelectedTerminalSpatialUniformModulus
        u p x T :=
    selectedTerminalSpatialUniformModulus_of_spatialEquicontinuity_of_endpointTemporalModulus
      hTau
      hSpatialEquicontinuity
      hEndpoint

  rcases
    nativeComplement_noCanonicalFactor_forces_pivotInfinityAndIntrinsicFiniteCoreTrace_or_boundedTerminalContrast
      hTau
      hEndpoint
      hSpatialEquicontinuity
      hDecay
      hResidualBounded
      hNoFactor
    with
    hEscapeSide | hContrast

  · left

    have hClosureTrace :
        H3TerminalComplementGradientHasNonzeroIntrinsicSelectedClosureTrace
          u p x T :=
      nonzeroIntrinsicSelectedClosureTrace_of_distinctIntrinsicFiniteTerminalTrace
        hTerminalModulus
        hEscapeSide.2.1

    exact
      ⟨
        hEscapeSide.1,
        hClosureTrace,
        hEscapeSide.2.2
      ⟩

  · exact
      Or.inr
        hContrast

end

end Euclidean
end Bridge
end PrimeTensor
