import PrimeTensor.Fluid.Vorticity.H3.Energy.Transport.Order.Three.Interpolation.Landau.Analytic.CompactSupportSobolev
import Mathlib.Analysis.Calculus.BumpFunction.InnerProduct

/-!
# Smooth radial cutoffs for the whole-space Landau Sobolev endpoint

The compact-support Sobolev anchor is now available on PrimeTensor's physical
three-space.  The next step toward the whole-space theorem is to manufacture
compactly-supported approximants of an arbitrary `C¹` scalar field.

For every radius `R > 0`, this file uses Mathlib's `ContDiffBump` API to define
a smooth cutoff centered at the origin with

    rIn  = R,
    rOut = 2R.

Hence the cutoff is

* identically `1` on the closed ball of radius `R`;
* valued in `[0,1]`;
* compactly supported in the closed ball of radius `2R`;
* `C∞`.

Multiplying a `SpatialC1` field by this cutoff therefore gives a compactly
supported `SpatialC1` field agreeing with the original field on the radius-`R`
closed ball.

No derivative estimate is proved yet.  That is intentionally the next
increment: it will identify the Fréchet derivative of the cutoff product and
control the error term generated by the cutoff derivative.
-/

namespace PrimeTensor
namespace Bridge
namespace Euclidean

open Set Function
open scoped Topology ContDiff

noncomputable section

noncomputable local instance axisFintypeH3LandauCutoff
    (d : Depth) :
    Fintype (PrimeTensor.Axis d) :=
  Fintype.ofFinite (PrimeTensor.Axis d)

/-- Smooth bump centered at the origin, equal to one through radius `R` and
supported through radius `2R`. -/
noncomputable def h3LandauCutoffBump
    (R : ℝ)
    (hR : 0 < R) :
    ContDiffBump (0 : Point3) where
  rIn := R
  rOut := 2 * R
  rIn_pos := hR
  rIn_lt_rOut := by
    nlinarith

@[simp]
theorem h3LandauCutoffBump_rIn
    (R : ℝ)
    (hR : 0 < R) :
    (h3LandauCutoffBump R hR).rIn = R := by
  rfl

@[simp]
theorem h3LandauCutoffBump_rOut
    (R : ℝ)
    (hR : 0 < R) :
    (h3LandauCutoffBump R hR).rOut = 2 * R := by
  rfl

/-- The cutoff is exactly one on the radius-`R` closed ball. -/
theorem h3LandauCutoffBump_eq_one_of_norm_le
    {R : ℝ}
    (hR : 0 < R)
    {x : Point3}
    (hx : ‖x‖ ≤ R) :
    h3LandauCutoffBump R hR x = 1 := by
  apply
    (h3LandauCutoffBump R hR).one_of_mem_closedBall

  simpa [Metric.mem_closedBall] using hx

/-- The cutoff is nonnegative everywhere. -/
theorem h3LandauCutoffBump_nonneg
    {R : ℝ}
    (hR : 0 < R)
    (x : Point3) :
    0 ≤ h3LandauCutoffBump R hR x := by
  exact
    (h3LandauCutoffBump R hR).nonneg

/-- The cutoff is at most one everywhere. -/
theorem h3LandauCutoffBump_le_one
    {R : ℝ}
    (hR : 0 < R)
    (x : Point3) :
    h3LandauCutoffBump R hR x ≤ 1 := by
  exact
    (h3LandauCutoffBump R hR).le_one

/-- The cutoff is smooth, in particular `C¹`. -/
theorem h3LandauCutoffBump_spatialC1
    {R : ℝ}
    (hR : 0 < R) :
    SpatialC1
      (fun x : Point3 =>
        h3LandauCutoffBump R hR x) := by
  exact
    (h3LandauCutoffBump R hR).contDiff

/-- The cutoff has compact support. -/
theorem h3LandauCutoffBump_hasCompactSupport
    {R : ℝ}
    (hR : 0 < R) :
    HasCompactSupport
      (fun x : Point3 =>
        h3LandauCutoffBump R hR x) := by
  exact
    (h3LandauCutoffBump R hR).hasCompactSupport

/-- Multiply a scalar field by the smooth radius-`R` cutoff. -/
noncomputable def h3LandauCutoffField
    (R : ℝ)
    (hR : 0 < R)
    (g : ScalarField3) :
    ScalarField3 :=
  fun x : Point3 =>
    h3LandauCutoffBump R hR x * g x

/-- Cutting off a spatially `C¹` field preserves spatial `C¹` regularity. -/
theorem h3LandauCutoffField_spatialC1
    {R : ℝ}
    (hR : 0 < R)
    {g : ScalarField3}
    (hg : SpatialC1 g) :
    SpatialC1
      (h3LandauCutoffField R hR g) := by
  unfold h3LandauCutoffField

  exact
    (h3LandauCutoffBump R hR).contDiff.mul hg

/-- Cutting off any scalar field produces compact support. -/
theorem h3LandauCutoffField_hasCompactSupport
    {R : ℝ}
    (hR : 0 < R)
    (g : ScalarField3) :
    HasCompactSupport
      (h3LandauCutoffField R hR g) := by
  unfold h3LandauCutoffField

  exact
    (h3LandauCutoffBump_hasCompactSupport hR).mul_right

/-- The cutoff field agrees pointwise with the original field on the radius-`R`
closed ball. -/
theorem h3LandauCutoffField_eq_of_norm_le
    {R : ℝ}
    (hR : 0 < R)
    {g : ScalarField3}
    {x : Point3}
    (hx : ‖x‖ ≤ R) :
    h3LandauCutoffField R hR g x = g x := by
  unfold h3LandauCutoffField

  rw [
    h3LandauCutoffBump_eq_one_of_norm_le
      hR hx,
    one_mul
  ]

/-- Therefore every fixed physical point is eventually untouched by expanding
positive-radius cutoffs. -/
theorem h3LandauCutoffField_eq_of_radius_ge_norm
    {R : ℝ}
    (hR : 0 < R)
    (g : ScalarField3)
    (x : Point3)
    (hx : ‖x‖ ≤ R) :
    h3LandauCutoffField R hR g x = g x :=
  h3LandauCutoffField_eq_of_norm_le
    hR hx

end

end Euclidean
end Bridge
end PrimeTensor
