import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.Schwartz.Spectral.Nonlinear.Forcing.Duhamel.Frechet.Induction.MomentFreeHeat

/-!
# Fréchet endpoint induction: uniform positive-time moment slabs

The endpoint induction is not pointwise in time: every terminal Duhamel tail
needs one forcing bound valid on a whole positive source interval.  This file
therefore packages the actual invariant which the Nat induction will iterate.

For a real moment exponent `p`, a selected moment slab on `[a,t]` records one
uniform bound for each of:

* the canonical mild-state `p` moment;
* the complete selected Duhamel `p` moment;
* the unweighted raw Fourier `L¹` mass.

The first reusable consequence is the nonlinear half of the bootstrap:
whenever `1 ≤ p`, a `p`-moment slab gives an integrable forcing moment
`p-1` at every time in the slab, together with one explicit forcing bound
valid uniformly across the whole slab.

This is the induction invariant replacing all future named endpoint envelopes.
-/

namespace PrimeTensor
namespace Bridge
namespace Euclidean

open MeasureTheory Set Filter
open scoped BigOperators ENNReal NNReal Interval Topology InnerProductSpace

noncomputable section

noncomputable local instance axisFintypeH3SchwartzFrechetInductionMomentSlab
    (d : Depth) :
    Fintype (PrimeTensor.Axis d) :=
  Fintype.ofFinite (PrimeTensor.Axis d)

/-- Uniform positive-time data at one Fourier moment exponent.

The three scalar bounds are explicit parameters so later bootstrap steps can
construct new slab bounds without hiding any compactness argument. -/
def H3SelectedMomentSlab
    (p ν A a t BState BDuhamel B0 : ℝ)
    (hν : 0 < ν)
    (U₀ : H3SpectralVelocityState)
    (hA : 0 < A)
    (hU₀ : ‖U₀‖ ≤ A) : Prop :=
  0 ≤ BState ∧
  0 ≤ BDuhamel ∧
  0 ≤ B0 ∧
  ∀ s ∈ Set.Icc a t, ∀ i : Fin 3,
    let W : ℝ → H3SpectralFinVectorState :=
      h3SpectralFinHeatLerayMildSolutionAtRestartRadiusPhysicalExtension
        hν U₀ hA hU₀
    let D : H3FourierComplexL2 :=
      h3SpectralFinHeatLerayDuhamelSelectedRawFourierL2
        (t := s) hν U₀ hA hU₀ i
    H3RawFourierMomentIntegrable p (W s i) ∧
    h3SpectralScalarRawFourierMomentMass p (W s i) ≤ BState ∧
    Integrable
      (fun ξ : H3FourierPoint3 =>
        h3FourierMomentWeight p ξ * ‖D ξ‖)
      (volume : Measure H3FourierPoint3) ∧
    (∫ ξ : H3FourierPoint3,
        h3FourierMomentWeight p ξ * ‖D ξ‖)
      ≤ BDuhamel ∧
    h3SpectralScalarRawFourierL1Mass (W s i) ≤ B0

/-- A moment slab restricts to every nested closed time interval without
changing any of its three numerical bounds. -/
theorem H3SelectedMomentSlab.restrict
    {p ν A a₀ t₀ a₁ t₁ BState BDuhamel B0 : ℝ}
    {hν : 0 < ν}
    {U₀ : H3SpectralVelocityState}
    {hA : 0 < A}
    {hU₀ : ‖U₀‖ ≤ A}
    (hSlab :
      H3SelectedMomentSlab
        p ν A a₀ t₀ BState BDuhamel B0
        hν U₀ hA hU₀)
    (ha : a₀ ≤ a₁)
    (ht : t₁ ≤ t₀) :
    H3SelectedMomentSlab
      p ν A a₁ t₁ BState BDuhamel B0
      hν U₀ hA hU₀ := by
  unfold H3SelectedMomentSlab at hSlab ⊢
  rcases hSlab with ⟨hBS, hBD, hB0, hData⟩
  refine ⟨hBS, hBD, hB0, ?_⟩
  intro s hs i
  exact
    hData s
      ⟨le_trans ha hs.1, le_trans hs.2 ht⟩
      i

/-- Uniform forcing envelope generated by a state `p`-moment bound and a raw
`L¹` bound.  It is intentionally left as the finite coordinate sum appearing
in the generic Young/Leray estimate. -/
noncomputable def h3SelectedMomentSlabForcingEnvelope
    (p BState B0 : ℝ) : ℝ :=
  2 *
    ∑ _k : Fin 3,
      ∑ _j : Fin 3,
        (2 * Real.pi) *
          (h3FourierMomentSplitCoefficient p *
            (BState * B0 + B0 * BState))

/-- The slab forcing envelope is nonnegative when its input bounds are
nonnegative. -/
theorem h3SelectedMomentSlabForcingEnvelope_nonneg
    {p BState B0 : ℝ}
    (hBS : 0 ≤ BState)
    (hB0 : 0 ≤ B0) :
    0 ≤ h3SelectedMomentSlabForcingEnvelope p BState B0 := by
  unfold h3SelectedMomentSlabForcingEnvelope
  have hTerm :
      0 ≤
        (2 * Real.pi) *
          (h3FourierMomentSplitCoefficient p *
            (BState * B0 + B0 * BState)) := by
    exact
      mul_nonneg
        (by positivity)
        (mul_nonneg
          (h3FourierMomentSplitCoefficient_nonneg p)
          (add_nonneg
            (mul_nonneg hBS hB0)
            (mul_nonneg hB0 hBS)))
  exact
    mul_nonneg
      (by norm_num)
      (Finset.sum_nonneg fun _k _ =>
        Finset.sum_nonneg fun _j _ => hTerm)

/-- Every time slice in a `p`-moment slab has an integrable nonlinear forcing
moment `p-1`. -/
theorem h3RawFinLerayOuterProductDivergence_selectedMomentSlab_subOneMoment_integrable
    {p ν A a t BState BDuhamel B0 : ℝ}
    (hp : 1 ≤ p)
    (hν : 0 < ν)
    (U₀ : H3SpectralVelocityState)
    (hA : 0 < A)
    (hU₀ : ‖U₀‖ ≤ A)
    (hSlab :
      H3SelectedMomentSlab
        p ν A a t BState BDuhamel B0
        hν U₀ hA hU₀)
    (s : ℝ)
    (hs : s ∈ Set.Icc a t)
    (i : Fin 3) :
    let W : ℝ → H3SpectralFinVectorState :=
      h3SpectralFinHeatLerayMildSolutionAtRestartRadiusPhysicalExtension
        hν U₀ hA hU₀
    Integrable
      (fun ξ : H3FourierPoint3 =>
        h3FourierMomentWeight (p - 1) ξ *
          ‖h3RawFinLerayOuterProductDivergence
            (W s) (W s) i ξ‖)
      (volume : Measure H3FourierPoint3) := by
  dsimp only

  unfold H3SelectedMomentSlab at hSlab
  rcases hSlab with ⟨_hBS, _hBD, _hB0, hData⟩

  let W : ℝ → H3SpectralFinVectorState :=
    h3SpectralFinHeatLerayMildSolutionAtRestartRadiusPhysicalExtension
      hν U₀ hA hU₀

  have hState :
      ∀ k : Fin 3,
        H3RawFourierMomentIntegrable p (W s k) := by
    intro k
    have hk := hData s hs k
    dsimp only [W] at hk
    exact hk.1

  have hpEq :
      (p - 1) + 1 = p := by
    ring

  have hState' :
      ∀ k : Fin 3,
        H3RawFourierMomentIntegrable
          ((p - 1) + 1) (W s k) := by
    intro k
    rw [hpEq]
    exact hState k

  exact
    h3RawFinLerayOuterProductDivergence_moment_integrable_of_nextMoments
      (q := p - 1)
      (by linarith)
      (W s) (W s)
      hState' hState' i

/-- The generic nonlinear forcing mass is bounded by one slab-wide constant
at every time slice. -/
theorem h3RawFinLerayOuterProductDivergence_selectedMomentSlab_subOneMass_le
    {p ν A a t BState BDuhamel B0 : ℝ}
    (hp : 1 ≤ p)
    (hν : 0 < ν)
    (U₀ : H3SpectralVelocityState)
    (hA : 0 < A)
    (hU₀ : ‖U₀‖ ≤ A)
    (hSlab :
      H3SelectedMomentSlab
        p ν A a t BState BDuhamel B0
        hν U₀ hA hU₀)
    (s : ℝ)
    (hs : s ∈ Set.Icc a t)
    (i : Fin 3) :
    let W : ℝ → H3SpectralFinVectorState :=
      h3SpectralFinHeatLerayMildSolutionAtRestartRadiusPhysicalExtension
        hν U₀ hA hU₀
    h3RawFinLerayOuterProductDivergenceMomentMass
        (p - 1) (W s) (W s) i
      ≤
    h3SelectedMomentSlabForcingEnvelope p BState B0 := by
  dsimp only

  unfold H3SelectedMomentSlab at hSlab
  rcases hSlab with ⟨hBS0, _hBD0, hB00, hData⟩

  let W : ℝ → H3SpectralFinVectorState :=
    h3SpectralFinHeatLerayMildSolutionAtRestartRadiusPhysicalExtension
      hν U₀ hA hU₀

  have hState :
      ∀ k : Fin 3,
        H3RawFourierMomentIntegrable p (W s k) := by
    intro k
    have hk := hData s hs k
    dsimp only [W] at hk
    exact hk.1

  have hStateMass :
      ∀ k : Fin 3,
        h3SpectralScalarRawFourierMomentMass p (W s k)
          ≤ BState := by
    intro k
    have hk := hData s hs k
    dsimp only [W] at hk
    exact hk.2.1

  have hL1 :
      ∀ k : Fin 3,
        h3SpectralScalarRawFourierL1Mass (W s k)
          ≤ B0 := by
    intro k
    have hk := hData s hs k
    dsimp only [W] at hk
    exact hk.2.2.2.2

  have hpEq :
      (p - 1) + 1 = p := by
    ring

  have hState' :
      ∀ k : Fin 3,
        H3RawFourierMomentIntegrable
          ((p - 1) + 1) (W s k) := by
    intro k
    rw [hpEq]
    exact hState k

  have hBase :=
    h3RawFinLerayOuterProductDivergenceMomentMass_le_stateMoments
      (q := p - 1)
      (by linarith)
      (W s) (W s)
      hState' hState' i

  rw [hpEq] at hBase

  have hL1nonneg :
      ∀ k : Fin 3,
        0 ≤ h3SpectralScalarRawFourierL1Mass (W s k) := by
    intro k
    unfold h3SpectralScalarRawFourierL1Mass
    exact integral_nonneg fun ξ => norm_nonneg _

  have hMomentNonneg :
      ∀ k : Fin 3,
        0 ≤ h3SpectralScalarRawFourierMomentMass p (W s k) := by
    intro k
    exact
      h3SpectralScalarRawFourierMomentMass_nonneg
        p (W s k)

  have hEach :
      ∀ k j : Fin 3,
        (2 * Real.pi) *
            (h3FourierMomentSplitCoefficient p *
              (h3SpectralScalarRawFourierMomentMass p (W s k) *
                  h3SpectralScalarRawFourierL1Mass (W s j) +
                h3SpectralScalarRawFourierL1Mass (W s k) *
                  h3SpectralScalarRawFourierMomentMass p (W s j)))
          ≤
        (2 * Real.pi) *
          (h3FourierMomentSplitCoefficient p *
            (BState * B0 + B0 * BState)) := by
    intro k j

    have hFirst :
        h3SpectralScalarRawFourierMomentMass p (W s k) *
            h3SpectralScalarRawFourierL1Mass (W s j)
          ≤
        BState * B0 :=
      mul_le_mul
        (hStateMass k)
        (hL1 j)
        (hL1nonneg j)
        hBS0

    have hSecond :
        h3SpectralScalarRawFourierL1Mass (W s k) *
            h3SpectralScalarRawFourierMomentMass p (W s j)
          ≤
        B0 * BState :=
      mul_le_mul
        (hL1 k)
        (hStateMass j)
        (hMomentNonneg j)
        hB00

    have hSum :=
      add_le_add hFirst hSecond

    have hSplit :=
      mul_le_mul_of_nonneg_left
        hSum
        (h3FourierMomentSplitCoefficient_nonneg p)

    exact
      mul_le_mul_of_nonneg_left
        hSplit
        (by positivity)

  unfold h3SelectedMomentSlabForcingEnvelope

  exact
    le_trans hBase
      (mul_le_mul_of_nonneg_left
        (Finset.sum_le_sum fun k _ =>
          Finset.sum_le_sum fun j _ =>
            hEach k j)
        (by norm_num))

end
end Euclidean
end Bridge
end PrimeTensor
