import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.Schwartz.Spectral.Classicalization.Physical.Tail.Unit.Viscosity.Frontier.Endpoint.Continuity.Closure

/-!
# Zeroth-order endpoint continuity reduced to an L² Lipschitz estimate

The closed unit-viscosity continuation interface now has only two remaining
time-topology inputs:

* strong physical `L²` continuity of the zeroth-order velocity coordinates;
* strong physical `L²` continuity of the ordered third-order coordinates.

The zeroth-order statement is naturally generated by the Navier--Stokes
evolution equation.  Uniform control of the physical projected RHS on a closed
elapsed interval yields a quantitative `L²` Lipschitz estimate for the velocity
path, and Lipschitz continuity immediately gives the required strong topology.

This file isolates exactly that quantitative target.  It does not assume a
derivative formula or a particular RHS bound yet; those are the next analytic
steps.  The continuation theorem is repackaged so that zeroth-order continuity
is no longer an opaque topological hypothesis but a concrete Lipschitz
estimate.

The ordered-third-order continuity frontier is unchanged.
-/

namespace PrimeTensor
namespace Bridge
namespace Euclidean

open MeasureTheory Filter Set
open scoped ENNReal NNReal Interval Topology BigOperators

noncomputable section

noncomputable local instance axisFintypeH3UnitViscosityZeroL2Lipschitz
    (d : Depth) :
    Fintype (PrimeTensor.Axis d) :=
  Fintype.ofFinite (PrimeTensor.Axis d)

/-- Quantitative zeroth-order physical `L²` time regularity on one elapsed
interval.  One common Lipschitz constant controls all three velocity
coordinates. -/
def H3PreterminalCanonicalL2ZeroLipschitzOnElapsed
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau E : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (hEnd : t + tau < T)
    (hTail : CanonicalH3TailDataFrom u t T E) : Prop :=
  ∃ K : ℝ≥0,
    ∀ j : Fin 3,
      LipschitzWith
        K
        (h3PreterminalCanonicalL2JetOnElapsed
          hNS ht hEnd hTail (h3JetSlot0 j))

/-- An `L²` Lipschitz estimate immediately supplies the zeroth-order strong
continuity required by the endpoint frontier. -/
theorem h3PreterminalCanonicalL2ZeroContinuousOnElapsed_of_lipschitz
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau E : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (hEnd : t + tau < T)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hLipschitz :
      H3PreterminalCanonicalL2ZeroLipschitzOnElapsed
        hNS ht hEnd hTail) :
    H3PreterminalCanonicalL2ZeroContinuousOnElapsed
      hNS ht hEnd hTail := by
  rcases hLipschitz with ⟨K, hK⟩
  intro j
  exact (hK j).continuous

/-- Radius-wide unit-viscosity zeroth-order `L²` Lipschitz frontier. -/
def H3PreterminalTailUnitViscosityZeroLipschitzFrontierOnRestartRadius
    (E : ℝ)
    (u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three)
    (T t : ℝ)
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E) : Prop :=
  ∀ q : Set.Icc
      (0 : ℝ)
      (h3FinHeatLerayRestartRadius (1 : ℝ) E),
    ∀ hqPos : 0 < (q : ℝ),
      ∀ hEnd : t + (q : ℝ) < T,
        H3PreterminalCanonicalL2ZeroLipschitzOnElapsed
          hNS ht hEnd hTail

/-- Radius-wide zeroth-order Lipschitz control closes the previous radius-wide
zeroth-order continuity frontier. -/
theorem h3PreterminalTailUnitViscosityZeroContinuityFrontierOnRestartRadius_of_lipschitz
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hLipschitz :
      H3PreterminalTailUnitViscosityZeroLipschitzFrontierOnRestartRadius
        E u T t hNS ht hE hTail) :
    H3PreterminalTailUnitViscosityZeroContinuityFrontierOnRestartRadius
      E u T t hNS ht hE hTail := by
  intro q hqPos hEnd
  exact
    h3PreterminalCanonicalL2ZeroContinuousOnElapsed_of_lipschitz
      hNS ht hEnd hTail
      (hLipschitz q hqPos hEnd)

/-- Global zeroth-order physical `L²` Lipschitz frontier. -/
def H3PreterminalTailUnitViscosityZeroLipschitzFrontier : Prop :=
  ∀
    (E : ℝ)
    (hE : 1 ≤ E)
    (u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three)
    (T t : ℝ)
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (hTail : CanonicalH3TailDataFrom u t T E),
      H3PreterminalTailUnitViscosityZeroLipschitzFrontierOnRestartRadius
        E u T t hNS ht hE hTail

/-- The global Lipschitz frontier implies the global zeroth-order continuity
frontier used by the endpoint split. -/
theorem h3PreterminalTailUnitViscosityZeroContinuityFrontier_of_lipschitz
    (hLipschitz :
      H3PreterminalTailUnitViscosityZeroLipschitzFrontier) :
    H3PreterminalTailUnitViscosityZeroContinuityFrontier := by
  intro E hE u T t hNS ht hTail
  exact
    h3PreterminalTailUnitViscosityZeroContinuityFrontierOnRestartRadius_of_lipschitz
      hNS ht hE hTail
      (hLipschitz E hE u T t hNS ht hTail)

/-- Current closed continuation boundary with the zeroth-order topology replaced
by the quantitative PDE-scale Lipschitz target. -/
theorem h3ControlProducesExtension_of_unitViscosityZeroLipschitzThirdContinuityClosed
    (hZeroLipschitz :
      H3PreterminalTailUnitViscosityZeroLipschitzFrontier)
    (hThird :
      H3PreterminalTailUnitViscosityThirdContinuityFrontier) :
    H3ControlProducesExtension := by
  exact
    h3ControlProducesExtension_of_unitViscosityZeroThirdContinuityClosed
      (h3PreterminalTailUnitViscosityZeroContinuityFrontier_of_lipschitz
        hZeroLipschitz)
      hThird

end

end Euclidean
end Bridge
end PrimeTensor
