import PrimeTensor.Fluid.Vorticity.Continuation.H3.Analysis.Closed
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Analysis.Frontier.Split
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Analysis.Reduced
import PrimeTensor.Fluid.Vorticity.Continuation.H3.BKM.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Bridge.Old.Physical.L2.Pairing
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Canonical.Data.Reduction
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Canonical.Selected
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Core
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Commutation.Mixed.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Commutation.Mixed.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Mixed.Commutation
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.One.Energy.Derivative.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.One.Scalar.Weak.Test.Density
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.One.Selected.Cubic.Velocity.Fourier.L2.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.One.Selected.Cubic.Velocity.Physical.L2.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.One.Selected.Cubic.Velocity.Physical.L2.Identification
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.One.Selected.Energy.Reduction
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.One.Selected.Forcing.First.Coordinate.Fourier.L2.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.One.Selected.Forcing.First.Coordinate.Open.L2.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.One.Selected.Forcing.First.Coordinate.Physical.L2.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.One.Selected.Forcing.First.Coordinate.Physical.L2.Identification
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.One.Selected.L2.Jet.Reduction
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.One.Selected.Relative.Strong.L2.Reduction
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.One.Selected.Strong.L2.From.Coefficient.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.One.Selected.Temporal.L2.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.One.Selected.Temporal.L2.Reduction
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.One.Selected.Third.Velocity.L2.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.One.Selected.Weak.First.Jet.Derivative
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Three.Energy.Derivative.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Three.Energy.Derivative.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Three.Selected.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Three.Selected.Energy.Absolute.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Three.Selected.Forcing.Third.Coordinate.Fourier.L2.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Three.Selected.Forcing.Third.Coordinate.Open.L2.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Three.Selected.Forcing.Third.Coordinate.Physical.L2.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Three.Selected.Forcing.Third.Coordinate.Physical.L2.Identification
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Three.Selected.L2.Jet.Reduction
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Three.Selected.Reduction
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Three.Selected.Strong.L2.From.Coefficient.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Three.Selected.Temporal.L2.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Three.Selected.Temporal.L2.Reduction
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Three.Selected.Velocity.Fifth.Coordinate.Fourier.L2.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Three.Selected.Velocity.Fifth.Coordinate.Physical.L2.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Three.Selected.Velocity.Fifth.Coordinate.Physical.L2.Identification
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Three.Selected.Velocity.Fifth.Radial.L2.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Three.Selected.Velocity.Fifth.Radial.L2.Difference
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Three.Selected.Velocity.Sixth.Radial.L2.Compact.Bound
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Three.Selected.Velocity.Tail.Sixth.Radial.L2.Bound
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Three.Selected.Weak.Third.Jet.Derivative
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Two.Energy.Derivative.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Two.Selected.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Two.Selected.Forcing.Second.Coordinate.Fourier.L2.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Two.Selected.Forcing.Second.Coordinate.Open.L2.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Two.Selected.Forcing.Second.Coordinate.Physical.L2.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Two.Selected.Forcing.Second.Coordinate.Physical.L2.Identification
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Two.Selected.L2.Jet.Reduction
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Two.Selected.Reduction
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Two.Selected.Strong.L2.From.Coefficient.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Two.Selected.Temporal.L2.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Two.Selected.Temporal.L2.Reduction
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Two.Selected.Velocity.Duhamel.Raw.L2.Bound
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Two.Selected.Velocity.Fifth.Radial.L2.Compact.Bound
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Two.Selected.Velocity.Fourth.Coordinate.Fourier.L2.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Two.Selected.Velocity.Fourth.Coordinate.Physical.L2.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Two.Selected.Velocity.Fourth.Coordinate.Physical.L2.Identification
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Two.Selected.Velocity.Fourth.Radial.L2.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Two.Selected.Velocity.Head.Fifth.Radial.L2.Bound
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Two.Selected.Velocity.Heat.Radial.L2.Bound
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Two.Selected.Velocity.Radial.L2.Difference
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Two.Selected.Velocity.Raw.Fourier.L2.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Two.Selected.Velocity.Tail.Fifth.Radial.L2.Bound
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Two.Selected.Weak.Second.Jet.Derivative
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.TwoThree.Energy.Derivative.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.TwoThree.Majorant.BKM.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.TwoThree.Majorant.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Derivative.Order.Zero.Energy.Derivative.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Balance.Exact
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Balance.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Diffusion.Dissipation
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Diffusion.High.L2.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Diffusion.Sign.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Dynamics.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Growth.Dissipative
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Growth.Log
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Growth.Positive
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Growth.Sqrt
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Growth.Sqrt.Integrability.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Jet.High.L2.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Majorant.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Majorant.Pairing.PDE
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Majorant.Path.Diffusion.Pressure.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Majorant.Path.Scalar.Energy.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Majorant.Path.Scalar.Full.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Momentum.RHS.Square.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Momentum.Split.L2.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Pairing.PDE.L2.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Pairing.Separated.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Pointwise.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Scalar.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Tail.Low.From.Derivative.Identities
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Tail.Low.Scalar.Full.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.WholeSpace.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Pressure.Cancel.Higher
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Pressure.Cancel.Zero
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Pressure.L2.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Pressure.L2.Order.One
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Pressure.L2.Order.Three
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Pressure.L2.Order.Two
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Pressure.L2.Order.Zero
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Restart.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Restart.Direct
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Duhamel.Tail.Cubic.L2.Baseline
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Duhamel.Tail.Radial.L2.BKM.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Duhamel.Tail.Radial.L2.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Duhamel.Tail.Weighted.Kernel.L2
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Duhamel.Tail.Weighted.Kernel.L2.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Forcing.Fourier.Linf
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Forcing.Physical.L2.Jet
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Forcing.Physical.L2.Zero
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Forcing.Radial.Compact.L2.Bound
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Forcing.Radial.L2
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Forcing.Radial.L2.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Forcing.Radial.L2.Difference
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Forcing.Radial.L2.State
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Forcing.Radial.Open.L2.Continuity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Forcing.Uniform.Radial.L2
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Forcing.Uniform.Radial.L2.Generic
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.High.Fourier.Coordinate.L2.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.High.Frechet.Complex.L2.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.High.Frechet.L2.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.High.Radial.Duhamel.L2.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.High.Radial.Duhamel.Tail.L2.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.High.Radial.Fourier.L2.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.High.Radial.Pointwise.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.High.Spatial.Jet.L2.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Order.Zero.Coefficient.Bridge
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Physical.L2.Derivative
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Physical.L2.Energy.Axis.Bridge
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Physical.L2.Energy.Derivative
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Physical.L2.Energy.Germ.Bridge
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Physical.L2.Energy.Old.Bridge
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Physical.L2.Evolution
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Pressure.Physical.L2.First
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Pressure.Physical.L2.Second
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Pressure.Physical.L2.Third
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Pressure.Physical.L2.Zero
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Projected.RHS.Old.Bridge
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Raw.Forcing.Physical.L2.First
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Raw.Forcing.Physical.L2.Second
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Raw.Forcing.Physical.L2.Third
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Raw.Forcing.Physical.L2.Zero
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Raw.Forcing.Radial.L2
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Raw.Forcing.Second.Moment
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Raw.Forcing.Third.Moment
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Second.Velocity.L2.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Spectral.State.Old.Bridge
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Velocity.Jet.Four.Arbitrary.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Velocity.Jet.High.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Selected.Velocity.Old.Bridge
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Temporal.Jet.L2.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Temporal.Jet.L2.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Temporal.Jet.Square.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Temporal.Pairing.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Dichotomy
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Log.Alternative
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Near.Alternative
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Transport.Absorption.Continuation
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Transport.Absorption.Landau.Loop
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Transport.Excess.Full
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Transport.Excess.Partial
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Transport.L2.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Transport.Pressure.L2.Split.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Vorticity.Apriori.Frontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Vorticity.Energy.Envelope
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Riccati.LowerBound
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Riccati.Integrability
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Sequence
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Third
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Third.Rate
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Third.Rate.Polynomial
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Diffusion.Interpolation.Fourier.FourthSymbol
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Diffusion.Interpolation.Fourier.FourthCoordinate
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Diffusion.Interpolation.Fourier.FourthMoment
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Diffusion.Interpolation.Fourier.FourthRadial
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Diffusion.Interpolation.Fourier.LowerRadial
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Diffusion.Interpolation.Fourier.MomentDensity
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Energy.Diffusion.Interpolation.Fourier.MomentCauchy
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Third.Rate.Dissipation
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Third.Rate.Dissipation.Eventual
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Third.Rate.Dissipation.TransportDichotomy
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Third.Rate.Dissipation.Integrability
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Third.Rate.Dissipation.IntegrabilityDichotomy
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Third.Rate.Dissipation.TransportIntegrability
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.Integrability
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.Sequence
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.TransportSequence
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.JointSequence
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.TransportHarmonicSequence
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.TransportCubicRate
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.AbsorptionDefectSequence
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.IndexedEnergySequence
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.IndexedCascade
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.SuperquadraticCascade
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.TopFrequencyCascade
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.CharacteristicFrequencyCascade
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.CharacteristicFrequencyRate
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.CharacteristicLengthRate
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.CharacteristicFrequencyIntegrability
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.CharacteristicFrequencyContinuation
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.CharacteristicFrequencyThresholdContinuation
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.CharacteristicFrequencyFullLimit
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.FullEnergyDissipationCascade
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.FullEnergyNormalizedCascade
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.FullEnergyDissipationContinuation
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.NormalizedBalanceDichotomy
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.FullEnergyTransportSequence
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.NonnegativeGrowthNormalizedTransport
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.NormalizedBalanceGap
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.NormalizedDissipationRate
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.NormalizedDissipationThresholdContinuation
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.NormalizedDissipationIntegrability
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Transport.Absorption.Landau.TerminalFrontier
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Transport.Absorption.Landau.HarmonicRate
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Transport.Absorption.Landau.AffineHarmonicRate
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Transport.Absorption.Landau.SqrtEnergyEquivalence
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Transport.Absorption.Landau.VorticityEnvelopeEquivalence
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Vorticity.TailIntegrability
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Gradient.TailIntegrability
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.ComponentAmplitude
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.ComponentSequences
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.VorticityGradientSynchronizedSequence
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.VorticityGradientSamePointSequence
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.EnstrophySequence
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.NativeEnstrophyEscape
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.FixedVorticityComponent
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.FixedGradientComponent
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.FixedComponentSequences
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.FixedCurlGradientPair
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.FixedCurlGradientSamePoint
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.FixedCurlGradientOrientation
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.NativeVorticityOrientationEscape
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.FixedCurlGradientDoubleOrientation
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.NativeCurlGradientDoubleEscape
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.NativeCurlGradientFiniteStateEscape
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.NativeCurlGradientEnstrophyCascade
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.NativeCurlGradientEnstrophyFiniteStateEscape
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.NativeCurlEnstrophyQuadratic
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.ComplementaryGradientDichotomy
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.ComplementaryGradientCancellationRefinement
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.ComplementaryGradientCancellationRatio
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.ComplementaryGradientCancellationSubsequence
