import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.Schwartz.Spectral.Classicalization.Physical.Tail.Endpoint.Canonical.Physical.L2.Admissible.Closure.Leray.Density.Temporal.Endpoint.Family.Closure.Curl.Integrated
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.Schwartz.Spectral.Classicalization.Physical.Tail.Endpoint.Canonical.Weak.Diffusion.Pairing
import PrimeTensor.Fluid.Vorticity.Preterminal.Equation

/-!
# Identify the three curl-test velocity pairings with classical vorticity pairings

The weak-curl route has reduced endpoint evolution to only three integrated
weak identities, generated by

    curl01(ψ) = ( ∂₁ψ, -∂₀ψ,      0 ),
    curl02(ψ) = ( ∂₂ψ,      0, -∂₀ψ ),
    curl12(ψ) = (     0,  ∂₂ψ, -∂₁ψ ).

At each fixed preterminal time, one spatial integration by parts moves those
derivatives from the compact test onto the old velocity.  The three pairings
then become exactly

    curl01  ->   <ψ, ω_z>,
    curl02  -> - <ψ, ω_y>,
    curl12  ->   <ψ, ω_x>.

This is the spatial half of the vorticity bypass.  It uses only slice-wise
spatial regularity of the old solution; no temporal Fubini or joint spacetime
continuity appears.
-/

namespace PrimeTensor
namespace Bridge
namespace Euclidean

open MeasureTheory Filter Set
open scoped BigOperators ENNReal NNReal Interval Topology InnerProductSpace

noncomputable section

noncomputable local instance axisFintypeH3EndpointCurlVorticityPairing
    (d : Depth) :
    Fintype (PrimeTensor.Axis d) :=
  Fintype.ofFinite (PrimeTensor.Axis d)

noncomputable local instance point3MeasureSpaceH3EndpointCurlVorticityPairing :
    MeasureSpace Point3 :=
  @MeasureTheory.MeasureSpace.pi
    (PrimeTensor.Axis Depth.three)
    (Fintype.ofFinite (PrimeTensor.Axis Depth.three))
    (fun _ : PrimeTensor.Axis Depth.three => ℝ)
    (fun _ : PrimeTensor.Axis Depth.three => Real.measureSpace)

/-- A compact weak test times one first spatial derivative of a genuine old
velocity component is integrable. -/
theorem h3PreterminalTailCanonical_test_mul_loggedVelocitySpatialDerivative_integrable
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (hEnd : t + tau < T)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (q : Set.Icc (0 : ℝ) tau)
    (j a : PrimeTensor.Axis Depth.three)
    (ψ : H3WeakTestFunction) :
    Integrable
      (fun x : Point3 =>
        (ContinuousLinearMap.lsmul ℝ ℝ)
          (ψ x)
          (spatial3.d
            a
            (loggedVelocityComponent u (t + (q : ℝ)) j)
            x))
      (volume : Measure Point3) := by
  have hAbs :
      t + (q : ℝ) ∈ Set.Ioo (0 : ℝ) T :=
    h3PreterminalElapsedTime_mem_Ioo
      ht hEnd q

  let pOld :
      SpaceTimeScalarField ℝ ℝ ℝ Depth.three :=
    Classical.choose hNS

  let hPDE :
      PreterminalNavierStokes3
        (logSpaceTimeVectorField u)
        pOld
        T :=
    Classical.choose_spec hNS

  have hC3 :
      SpatialC3
        (loggedVelocityComponent
          u (t + (q : ℝ)) j) := by
    unfold loggedVelocityComponent
    exact
      hPDE.regularity.velocity_spatial_three
        (t + (q : ℝ)) hAbs j

  have hC1 :
      SpatialC1
        (loggedVelocityComponent
          u (t + (q : ℝ)) j) :=
    hC3.of_le (by norm_num)

  have hDContinuous :
      Continuous
        (spatial3.d
          a
          (loggedVelocityComponent
            u (t + (q : ℝ)) j)) :=
    h3SpatialC1_spatial3_d_continuous_weakPressure
      hC1 a

  exact
    ψ.integrable_bilin
      (ContinuousLinearMap.lsmul ℝ ℝ)
      (hDContinuous.locallyIntegrable.locallyIntegrableOn Set.univ)

/-- Pairing one differentiated compact test against an old physical `L²`
velocity slot moves that derivative onto the classical old velocity with the
usual minus sign. -/
theorem inner_h3WeakTestFunctionSpatialDerivative_preterminalSlot0_eq_neg_pairing_loggedVelocitySpatialDerivative
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (hEnd : t + tau < T)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (q : Set.Icc (0 : ℝ) tau)
    (i : Fin 3)
    (a : PrimeTensor.Axis Depth.three)
    (ψ : H3WeakTestFunction) :
    inner ℝ
        (h3WeakTestFunctionPhysicalL2
          (h3WeakTestFunctionSpatialDerivative a ψ))
        (h3PreterminalCanonicalL2JetOnElapsed
          hNS ht hEnd hTail (h3JetSlot0 i) q)
      =
    -
    ∫ x : Point3,
      (ContinuousLinearMap.lsmul ℝ ℝ)
        (ψ x)
        (spatial3.d
          a
          (loggedVelocityComponent
            u (t + (q : ℝ)) (h3AxisOfFin3 i))
          x)
      ∂volume := by
  let f : ScalarField3 :=
    loggedVelocityComponent
      u (t + (q : ℝ)) (h3AxisOfFin3 i)

  let Φ : H3ScalarL2 :=
    h3WeakTestFunctionPhysicalL2
      (h3WeakTestFunctionSpatialDerivative a ψ)

  let V : H3ScalarL2 :=
    h3PreterminalCanonicalL2JetOnElapsed
      hNS ht hEnd hTail (h3JetSlot0 i) q

  have hΦ :
      (Φ : Point3 → ℝ)
        =ᵐ[(volume : Measure Point3)]
      (h3WeakTestFunctionSpatialDerivative a ψ :
        Point3 → ℝ) := by
    dsimp only [Φ]
    exact
      h3WeakTestFunctionPhysicalL2_ae
        (h3WeakTestFunctionSpatialDerivative a ψ)

  have hV :
      (V : Point3 → ℝ)
        =ᵐ[(volume : Measure Point3)]
      f := by
    dsimp only [V, f]
    exact
      h3PreterminalCanonicalL2JetOnElapsed_slot0_ae_eq_loggedVelocityComponent
        hNS ht hEnd hTail q i

  have hInner :
      inner ℝ Φ V
        =
      ∫ x : Point3,
        (ContinuousLinearMap.lsmul ℝ ℝ)
          ((h3WeakTestFunctionSpatialDerivative a ψ) x)
          (f x)
        ∂volume := by
    rw [MeasureTheory.L2.inner_def]
    apply integral_congr_ae
    filter_upwards [hΦ, hV] with x hxΦ hxV
    rw [hxΦ, hxV]
    simp [mul_comm]

  have hAbs :
      t + (q : ℝ) ∈ Set.Ioo (0 : ℝ) T :=
    h3PreterminalElapsedTime_mem_Ioo
      ht hEnd q

  let pOld :
      SpaceTimeScalarField ℝ ℝ ℝ Depth.three :=
    Classical.choose hNS

  let hPDE :
      PreterminalNavierStokes3
        (logSpaceTimeVectorField u)
        pOld
        T :=
    Classical.choose_spec hNS

  have hfC3 : SpatialC3 f := by
    dsimp only [f]
    unfold loggedVelocityComponent
    exact
      hPDE.regularity.velocity_spatial_three
        (t + (q : ℝ)) hAbs (h3AxisOfFin3 i)

  have hfC1 : SpatialC1 f :=
    hfC3.of_le (by norm_num)

  have hIBP :=
    h3SpatialC1_test_pairing_spatial3_d_eq_neg_testDerivative_pairing
      hfC1 a ψ

  change inner ℝ Φ V =
    - ∫ x : Point3,
        (ContinuousLinearMap.lsmul ℝ ℝ)
          (ψ x)
          (spatial3.d a f x)
        ∂volume

  rw [hInner]
  linarith

/-- Compact weak pairing with the classical old x-vorticity. -/
noncomputable def h3PreterminalTailCanonicalWeakVorticityXPairingOnElapsed
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {t tau : ℝ}
    (ψ : H3WeakTestFunction)
    (q : Set.Icc (0 : ℝ) tau) : ℝ :=
  ∫ x : Point3,
    (ContinuousLinearMap.lsmul ℝ ℝ)
      (ψ x)
      (realVorticityX
        (logSpaceTimeVectorField u)
        (t + (q : ℝ))
        x)
    ∂volume

/-- Compact weak pairing with the classical old y-vorticity. -/
noncomputable def h3PreterminalTailCanonicalWeakVorticityYPairingOnElapsed
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {t tau : ℝ}
    (ψ : H3WeakTestFunction)
    (q : Set.Icc (0 : ℝ) tau) : ℝ :=
  ∫ x : Point3,
    (ContinuousLinearMap.lsmul ℝ ℝ)
      (ψ x)
      (realVorticityY
        (logSpaceTimeVectorField u)
        (t + (q : ℝ))
        x)
    ∂volume

/-- Compact weak pairing with the classical old z-vorticity. -/
noncomputable def h3PreterminalTailCanonicalWeakVorticityZPairingOnElapsed
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {t tau : ℝ}
    (ψ : H3WeakTestFunction)
    (q : Set.Icc (0 : ℝ) tau) : ℝ :=
  ∫ x : Point3,
    (ContinuousLinearMap.lsmul ℝ ℝ)
      (ψ x)
      (realVorticityZ
        (logSpaceTimeVectorField u)
        (t + (q : ℝ))
        x)
    ∂volume

/-- The `01` curl-test velocity pairing is exactly the old z-vorticity weak
pairing. -/
theorem h3PreterminalTailCanonicalVelocityWeakPairingOnElapsed_curl01_eq_weakVorticityZ
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (hEnd : t + tau < T)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (ψ : H3WeakTestFunction)
    (q : Set.Icc (0 : ℝ) tau) :
    h3PreterminalTailCanonicalVelocityWeakPairingOnElapsed
        hNS ht hEnd hTail (h3WeakTestCurl01 ψ) q
      =
    h3PreterminalTailCanonicalWeakVorticityZPairingOnElapsed
      (u := u) (t := t) ψ q := by
  have h0 :=
    inner_h3WeakTestFunctionSpatialDerivative_preterminalSlot0_eq_neg_pairing_loggedVelocitySpatialDerivative
      hNS ht hEnd hTail q (0 : Fin 3) yAxis ψ

  have h1 :=
    inner_h3WeakTestFunctionSpatialDerivative_preterminalSlot0_eq_neg_pairing_loggedVelocitySpatialDerivative
      hNS ht hEnd hTail q (1 : Fin 3) xAxis ψ

  simp only [h3AxisOfFin3_zero] at h0
  simp only [h3AxisOfFin3_one] at h1

  have hDx :
      Integrable
        (fun x : Point3 =>
          (ContinuousLinearMap.lsmul ℝ ℝ)
            (ψ x)
            (spatial3.d
              xAxis
              (loggedVelocityComponent u (t + (q : ℝ)) yAxis)
              x))
        (volume : Measure Point3) :=
    h3PreterminalTailCanonical_test_mul_loggedVelocitySpatialDerivative_integrable
      hNS ht hEnd hTail q yAxis xAxis ψ

  have hDy :
      Integrable
        (fun x : Point3 =>
          (ContinuousLinearMap.lsmul ℝ ℝ)
            (ψ x)
            (spatial3.d
              yAxis
              (loggedVelocityComponent u (t + (q : ℝ)) xAxis)
              x))
        (volume : Measure Point3) :=
    h3PreterminalTailCanonical_test_mul_loggedVelocitySpatialDerivative_integrable
      hNS ht hEnd hTail q xAxis yAxis ψ

  have hVorticityPointwise
      (x : Point3) :
      realVorticityZ
          (logSpaceTimeVectorField u)
          (t + (q : ℝ))
          x
        =
      spatial3.d
          xAxis
          (loggedVelocityComponent u (t + (q : ℝ)) yAxis)
          x
        -
      spatial3.d
          yAxis
          (loggedVelocityComponent u (t + (q : ℝ)) xAxis)
          x := by
    rfl

  have hVort :
      h3PreterminalTailCanonicalWeakVorticityZPairingOnElapsed
          (u := u) (t := t) ψ q
        =
      (∫ x : Point3,
        (ContinuousLinearMap.lsmul ℝ ℝ)
          (ψ x)
          (spatial3.d
            xAxis
            (loggedVelocityComponent u (t + (q : ℝ)) yAxis)
            x)
        ∂volume)
        -
      (∫ x : Point3,
        (ContinuousLinearMap.lsmul ℝ ℝ)
          (ψ x)
          (spatial3.d
            yAxis
            (loggedVelocityComponent u (t + (q : ℝ)) xAxis)
            x)
        ∂volume) := by
    unfold h3PreterminalTailCanonicalWeakVorticityZPairingOnElapsed
    rw [← integral_sub hDx hDy]
    apply integral_congr_ae
    filter_upwards with x
    rw [hVorticityPointwise x]
    exact
      ((ContinuousLinearMap.lsmul ℝ ℝ) (ψ x)).map_sub
        (spatial3.d
          xAxis
          (loggedVelocityComponent u (t + (q : ℝ)) yAxis)
          x)
        (spatial3.d
          yAxis
          (loggedVelocityComponent u (t + (q : ℝ)) xAxis)
          x)

  unfold h3PreterminalTailCanonicalVelocityWeakPairingOnElapsed
  rw [Fin.sum_univ_three]
  simp only [
    h3WeakTestCurl01_apply_zero,
    h3WeakTestCurl01_apply_one,
    h3WeakTestCurl01_apply_two,
    h3WeakTestFunctionPhysicalL2_neg,
    h3WeakTestFunctionPhysicalL2_zero
  ]
  simp
  rw [h0, h1, hVort]
  ring

/-- The `02` curl-test velocity pairing is minus the old y-vorticity weak
pairing. -/
theorem h3PreterminalTailCanonicalVelocityWeakPairingOnElapsed_curl02_eq_neg_weakVorticityY
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (hEnd : t + tau < T)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (ψ : H3WeakTestFunction)
    (q : Set.Icc (0 : ℝ) tau) :
    h3PreterminalTailCanonicalVelocityWeakPairingOnElapsed
        hNS ht hEnd hTail (h3WeakTestCurl02 ψ) q
      =
    -
    h3PreterminalTailCanonicalWeakVorticityYPairingOnElapsed
      (u := u) (t := t) ψ q := by
  have h0 :=
    inner_h3WeakTestFunctionSpatialDerivative_preterminalSlot0_eq_neg_pairing_loggedVelocitySpatialDerivative
      hNS ht hEnd hTail q (0 : Fin 3) zAxis ψ

  have h2 :=
    inner_h3WeakTestFunctionSpatialDerivative_preterminalSlot0_eq_neg_pairing_loggedVelocitySpatialDerivative
      hNS ht hEnd hTail q (2 : Fin 3) xAxis ψ

  simp only [h3AxisOfFin3_zero] at h0
  simp only [h3AxisOfFin3_two] at h2

  have hDz :
      Integrable
        (fun x : Point3 =>
          (ContinuousLinearMap.lsmul ℝ ℝ)
            (ψ x)
            (spatial3.d
              zAxis
              (loggedVelocityComponent u (t + (q : ℝ)) xAxis)
              x))
        (volume : Measure Point3) :=
    h3PreterminalTailCanonical_test_mul_loggedVelocitySpatialDerivative_integrable
      hNS ht hEnd hTail q xAxis zAxis ψ

  have hDx :
      Integrable
        (fun x : Point3 =>
          (ContinuousLinearMap.lsmul ℝ ℝ)
            (ψ x)
            (spatial3.d
              xAxis
              (loggedVelocityComponent u (t + (q : ℝ)) zAxis)
              x))
        (volume : Measure Point3) :=
    h3PreterminalTailCanonical_test_mul_loggedVelocitySpatialDerivative_integrable
      hNS ht hEnd hTail q zAxis xAxis ψ

  have hVorticityPointwise
      (x : Point3) :
      realVorticityY
          (logSpaceTimeVectorField u)
          (t + (q : ℝ))
          x
        =
      spatial3.d
          zAxis
          (loggedVelocityComponent u (t + (q : ℝ)) xAxis)
          x
        -
      spatial3.d
          xAxis
          (loggedVelocityComponent u (t + (q : ℝ)) zAxis)
          x := by
    rfl

  have hVort :
      h3PreterminalTailCanonicalWeakVorticityYPairingOnElapsed
          (u := u) (t := t) ψ q
        =
      (∫ x : Point3,
        (ContinuousLinearMap.lsmul ℝ ℝ)
          (ψ x)
          (spatial3.d
            zAxis
            (loggedVelocityComponent u (t + (q : ℝ)) xAxis)
            x)
        ∂volume)
        -
      (∫ x : Point3,
        (ContinuousLinearMap.lsmul ℝ ℝ)
          (ψ x)
          (spatial3.d
            xAxis
            (loggedVelocityComponent u (t + (q : ℝ)) zAxis)
            x)
        ∂volume) := by
    unfold h3PreterminalTailCanonicalWeakVorticityYPairingOnElapsed
    rw [← integral_sub hDz hDx]
    apply integral_congr_ae
    filter_upwards with x
    rw [hVorticityPointwise x]
    exact
      ((ContinuousLinearMap.lsmul ℝ ℝ) (ψ x)).map_sub
        (spatial3.d
          zAxis
          (loggedVelocityComponent u (t + (q : ℝ)) xAxis)
          x)
        (spatial3.d
          xAxis
          (loggedVelocityComponent u (t + (q : ℝ)) zAxis)
          x)

  unfold h3PreterminalTailCanonicalVelocityWeakPairingOnElapsed
  rw [Fin.sum_univ_three]
  simp only [
    h3WeakTestCurl02_apply_zero,
    h3WeakTestCurl02_apply_one,
    h3WeakTestCurl02_apply_two,
    h3WeakTestFunctionPhysicalL2_neg,
    h3WeakTestFunctionPhysicalL2_zero
  ]
  simp
  rw [h0, h2, hVort]
  ring

/-- The `12` curl-test velocity pairing is exactly the old x-vorticity weak
pairing. -/
theorem h3PreterminalTailCanonicalVelocityWeakPairingOnElapsed_curl12_eq_weakVorticityX
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (hEnd : t + tau < T)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (ψ : H3WeakTestFunction)
    (q : Set.Icc (0 : ℝ) tau) :
    h3PreterminalTailCanonicalVelocityWeakPairingOnElapsed
        hNS ht hEnd hTail (h3WeakTestCurl12 ψ) q
      =
    h3PreterminalTailCanonicalWeakVorticityXPairingOnElapsed
      (u := u) (t := t) ψ q := by
  have h1 :=
    inner_h3WeakTestFunctionSpatialDerivative_preterminalSlot0_eq_neg_pairing_loggedVelocitySpatialDerivative
      hNS ht hEnd hTail q (1 : Fin 3) zAxis ψ

  have h2 :=
    inner_h3WeakTestFunctionSpatialDerivative_preterminalSlot0_eq_neg_pairing_loggedVelocitySpatialDerivative
      hNS ht hEnd hTail q (2 : Fin 3) yAxis ψ

  simp only [h3AxisOfFin3_one] at h1
  simp only [h3AxisOfFin3_two] at h2

  have hDy :
      Integrable
        (fun x : Point3 =>
          (ContinuousLinearMap.lsmul ℝ ℝ)
            (ψ x)
            (spatial3.d
              yAxis
              (loggedVelocityComponent u (t + (q : ℝ)) zAxis)
              x))
        (volume : Measure Point3) :=
    h3PreterminalTailCanonical_test_mul_loggedVelocitySpatialDerivative_integrable
      hNS ht hEnd hTail q zAxis yAxis ψ

  have hDz :
      Integrable
        (fun x : Point3 =>
          (ContinuousLinearMap.lsmul ℝ ℝ)
            (ψ x)
            (spatial3.d
              zAxis
              (loggedVelocityComponent u (t + (q : ℝ)) yAxis)
              x))
        (volume : Measure Point3) :=
    h3PreterminalTailCanonical_test_mul_loggedVelocitySpatialDerivative_integrable
      hNS ht hEnd hTail q yAxis zAxis ψ

  have hVorticityPointwise
      (x : Point3) :
      realVorticityX
          (logSpaceTimeVectorField u)
          (t + (q : ℝ))
          x
        =
      spatial3.d
          yAxis
          (loggedVelocityComponent u (t + (q : ℝ)) zAxis)
          x
        -
      spatial3.d
          zAxis
          (loggedVelocityComponent u (t + (q : ℝ)) yAxis)
          x := by
    rfl

  have hVort :
      h3PreterminalTailCanonicalWeakVorticityXPairingOnElapsed
          (u := u) (t := t) ψ q
        =
      (∫ x : Point3,
        (ContinuousLinearMap.lsmul ℝ ℝ)
          (ψ x)
          (spatial3.d
            yAxis
            (loggedVelocityComponent u (t + (q : ℝ)) zAxis)
            x)
        ∂volume)
        -
      (∫ x : Point3,
        (ContinuousLinearMap.lsmul ℝ ℝ)
          (ψ x)
          (spatial3.d
            zAxis
            (loggedVelocityComponent u (t + (q : ℝ)) yAxis)
            x)
        ∂volume) := by
    unfold h3PreterminalTailCanonicalWeakVorticityXPairingOnElapsed
    rw [← integral_sub hDy hDz]
    apply integral_congr_ae
    filter_upwards with x
    rw [hVorticityPointwise x]
    exact
      ((ContinuousLinearMap.lsmul ℝ ℝ) (ψ x)).map_sub
        (spatial3.d
          yAxis
          (loggedVelocityComponent u (t + (q : ℝ)) zAxis)
          x)
        (spatial3.d
          zAxis
          (loggedVelocityComponent u (t + (q : ℝ)) yAxis)
          x)

  unfold h3PreterminalTailCanonicalVelocityWeakPairingOnElapsed
  rw [Fin.sum_univ_three]
  simp only [
    h3WeakTestCurl12_apply_zero,
    h3WeakTestCurl12_apply_one,
    h3WeakTestCurl12_apply_two,
    h3WeakTestFunctionPhysicalL2_neg,
    h3WeakTestFunctionPhysicalL2_zero
  ]
  simp
  rw [h1, h2, hVort]
  ring

end

end Euclidean
end Bridge
end PrimeTensor
