import PrimeTensor
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Clock.Endpoint

/-! The canonical endpoint coexists with all historical root imports. -/
open PrimeTensor.Bridge.Euclidean

#check smoothContinuationExtension_or_quantitativeCriticalAlternative_and_higherRadialUniversalEscape_after_resolvedPDEClosure
#print axioms smoothContinuationExtension_or_quantitativeCriticalAlternative_and_higherRadialUniversalEscape_after_resolvedPDEClosure

-- Named interval limits retain the old logical content and common subsequence.
#check H3TerminalIntervalLimits
#check h3TerminalIntervalLimits_iff
#check H3TerminalIntervalLimits.comp
#print axioms h3TerminalIntervalLimits_iff
#print axioms H3TerminalIntervalLimits.comp
#print axioms h3TerminalHigherRadial_intervalGeometry_of_synchronized_collapse

-- Forward-width rebasing preserves the original witness and floor statement.
#check H3TerminalForwardWidthLimits
#check h3TerminalForwardWidthLimits_iff
#check H3TerminalIntervalLimits.toForwardWidth
#print axioms h3TerminalForwardWidthLimits_iff
#print axioms H3TerminalIntervalLimits.toForwardWidth
#print axioms h3TerminalHigherRadial_forwardWidthGeometry_of_terminalIntervalGeometry
