import PrimeTensor

/-!
Audit-only entrypoint. Print actual Lean types and transitive axiom dependencies.
This does not change the library's imports or strengthen its conclusions.
Keep the terminal extension package distinct from the genuine real restart.
-/

open PrimeTensor.Bridge.Euclidean

#print LoggedPreterminalH3PathAdmissible
#print PreterminalH3EnergyClass
#print H3TerminalComplementGradientStrongH3EndpointPath
#print H3TerminalActualVorticityStrongH3EndpointPath
#print H3TerminalVelocityRawFourierL2CauchyAtEndpoint
#print TerminalTailH3Control

#print SmoothContinuationExtension
#print H3ControlProducesRealRestart

-- Compare the full-data route with the weaker scalar-continuity route.
#print CanonicalH3EnergyDataOnTail
#print EnergyClassProducesCanonicalH3Data
#print CanonicalH3EnergyContinuousOnTail
#print EnergyClassProducesCanonicalH3EnergyContinuity
#check energyClassProducesCanonicalH3EnergyContinuity_of_canonicalData
#print axioms energyClassProducesCanonicalH3EnergyContinuity_of_canonicalData
#check h3ControlProducesRealRestart_of_unitViscosityEnergyContinuity
#print axioms h3ControlProducesRealRestart_of_unitViscosityEnergyContinuity
#check h3ControlProducesExtension_of_unitViscosityEnergyContinuity
#print axioms h3ControlProducesExtension_of_unitViscosityEnergyContinuity

-- The H3 path already supplies continuity for its own direct restart.
#check LoggedPreterminalH3PathAdmissible.canonicalH3EnergyContinuousOnTail
#print axioms LoggedPreterminalH3PathAdmissible.canonicalH3EnergyContinuousOnTail
#check h3PreterminalTailUnitViscosityLateEnergyContinuousRestartData_of_h3Path_tailControl
#print axioms h3PreterminalTailUnitViscosityLateEnergyContinuousRestartData_of_h3Path_tailControl
#check h3PathRealRestart_of_tailControl
#print axioms h3PathRealRestart_of_tailControl
#print H3PathH3ControlProducesExtension
#check h3PathH3ControlProducesExtension
#print axioms h3PathH3ControlProducesExtension

#check smoothContinuationExtension_of_realRestart
#print axioms smoothContinuationExtension_of_realRestart

#check h3ControlProducesRealRestart_of_unitViscosityCanonicalEnergy
#print axioms h3ControlProducesRealRestart_of_unitViscosityCanonicalEnergy

#check h3ControlProducesExtension_of_realRestart
#print axioms h3ControlProducesExtension_of_realRestart

-- Closed BKM and tail-local sufficient controls: no obsolete analytic frontier.
#print VorticityEnvelope
#print VorticityL1LinfControl
#print H3PathVorticityL1LinfProducesExtension
#check h3PathVorticityL1LinfProducesExtension_closed
#print axioms h3PathVorticityL1LinfProducesExtension_closed
#check h3PathExtension_of_integrableVorticityEnvelopeOnEnergyClassTail
#print axioms h3PathExtension_of_integrableVorticityEnvelopeOnEnergyClassTail
#check terminalTailH3Control_of_velocityH3EnergyBoundOnTail
#print axioms terminalTailH3Control_of_velocityH3EnergyBoundOnTail
#print h3PathPositiveLogEnergyGrowthRate
#check terminalTailH3Control_of_integrablePositiveLogEnergyGrowthRateOnTail
#print axioms terminalTailH3Control_of_integrablePositiveLogEnergyGrowthRateOnTail
#print H3PathPreterminalNavierStokesForcesVorticityL1Linf
#check everyH3PathPreterminalNavierStokesSolutionExtends_of_vorticityApriori
#print axioms everyH3PathPreterminalNavierStokesSolutionExtends_of_vorticityApriori

-- Expand the surviving alternative rather than treating its name as closure.
#print H3TerminalHigherRadialSampleClockNonvanishingWitness
#print H3TerminalHigherRadialForwardWidthCriticalThreshold
#print H3TerminalResolvedCanonicalForcingQuantitativeCriticalAlternative
#print H3TerminalPhysicalExtendedHigherRadialMomentUniversalEscapeSubsequenceOf

#check smoothContinuationExtension_or_quantitativeCriticalAlternative_and_higherRadialUniversalEscape_after_resolvedPDEClosure
#print axioms smoothContinuationExtension_or_quantitativeCriticalAlternative_and_higherRadialUniversalEscape_after_resolvedPDEClosure

-- Track the finite jet count after replacing native evaluation with cardinal arithmetic.
#check h3JetIndex_card
#print axioms h3JetIndex_card
