import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.Complement.Endpoint.Factor.BKM.Native.Full.Tail.Balance.Amplitude.Minimal.Vorticity.Physical.Longitudinal.Equatorial.Vorticity.Physical.Dissipation.Top.Radial.Tail.Temporal.Forward.PDE.TopDissipation.Forcing.Product.Quotient.Terminal.Second.LowerTemporal.Amplitude.Forcing.Primitive
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.Complement.Endpoint.Factor.BKM.Native.Full.Tail.Balance.Amplitude.Minimal.Vorticity.Physical.Strict.Time.Decay
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.Complement.Endpoint.Factor.BKM.Native.Full.Tail.Balance.Amplitude.Minimal.Vorticity.Physical.Longitudinal.Equatorial.Vorticity.Physical.L2.Cauchy.Frontier
import PrimeTensor
import PrimeTensor.Fluid.Vorticity.Continuation.H3.Terminal.Derivative.Positive.Complement.Endpoint.Factor.BKM.Native.Full.Tail.Balance.Amplitude.Minimal.Vorticity.Physical.Longitudinal.Equatorial.Vorticity.Physical.Dissipation.Top.Radial.Tail.Temporal.Hilbert.Weighted.Old.PDE.Terms

/-! Standalone API checks: importing the root must not cause name conflicts. -/

open PrimeTensor.Bridge.Euclidean

#check exists_h3TerminalPhysicalTopTailSeparatedWeightedPDETerms
#print axioms exists_h3TerminalPhysicalTopTailSeparatedWeightedPDETerms

-- Physical/Fourier L2 Cauchy identification and conditional closure.
#check h3TerminalPhysicalVelocityComponentAt
#check h3TerminalPhysicalVelocityTotalSquareDefect
#check h3TerminalRawVelocityFourierComponent_velocitySpectralStateAt_eq_scalarFourierL2_physical
#check h3TerminalRawVelocityFourierTotalSquareDefect_eq_coordinate_norm_squares
#check h3TerminalRawVelocityFourierTotalSquareDefect_velocitySpectralStateAt_eq_physical
#check H3TerminalVelocityPhysicalL2CauchyAtEndpoint
#check velocityRawFourierL2CauchyAtEndpoint_iff_physicalL2CauchyAtEndpoint
#check exists_failing_complementary_vorticityComponent_highRadialRaw_of_velocityPhysicalL2Cauchy_of_actualVorticityStrongH3EndpointPath_of_noH3PathExtension
#print axioms h3TerminalRawVelocityFourierTotalSquareDefect_velocitySpectralStateAt_eq_physical
#print axioms velocityRawFourierL2CauchyAtEndpoint_iff_physicalL2CauchyAtEndpoint
#print axioms exists_failing_complementary_vorticityComponent_highRadialRaw_of_velocityPhysicalL2Cauchy_of_actualVorticityStrongH3EndpointPath_of_noH3PathExtension

-- Fixed-time spatial decay; no uniform terminal-time claim.
#check h3TerminalCurlFieldForPair_strictTime_tendsto_zero_of_h3Path
#print axioms h3TerminalCurlFieldForPair_strictTime_tendsto_zero_of_h3Path
#check h3NativeActualVorticityComponentAt_strictTime_tendsto_zero_of_h3Path
#print axioms h3NativeActualVorticityComponentAt_strictTime_tendsto_zero_of_h3Path

-- Original aggregate API, including imported shared declarations.
#check h3TerminalForcingFourthQRadialLerayEnvelopeAt
#check h3TerminalForcingFourthQRadialLerayEnvelopeAt_nonneg
#check h3TerminalPhysicalTopDissipationForcingFourthQMassAt_le_sq_radialLerayEnvelope
#check h3TerminalForcingFourthQRadialLerayEnvelopeAt_tendstoAtTop_of_massPath_tendstoAtTop
#check h3TerminalForcingFourthQRadialProductNormAt
#check h3TerminalForcingFourthQRadialProductNormAt_nonneg
#check h3TerminalForcingFourthQFixedPairCoefficient
#check h3TerminalForcingFourthQFixedPairCoefficient_pos
#check h3TerminalForcingFourthQRadialLerayEnvelopeAt_eq_sum_productNorm
#check exists_pair_h3TerminalForcingFourthQRadialLerayEnvelopeAt_le_fixedCoefficient_mul_productNorm
#check exists_fixed_pair_subsequence_of_h3TerminalForcingFourthQMassPath_tendstoAtTop
#check h3TerminalForcingFourthQRadialProductStateMassEnvelopeAt
#check h3TerminalForcingFourthQRadialProductStateMassEnvelopeAt_nonneg
#check sq_h3TerminalForcingFourthQRadialProductNormAt_le_stateMassEnvelope
#check h3TerminalForcingFourthQRadialProductStateMassEnvelopeAt_tendstoAtTop_of_productNorm_tendstoAtTop
#check h3TerminalForcingFourthQPrimitiveFactorAt
#check h3TerminalForcingFourthQPrimitiveFactorAt_nonneg
#check exists_primitive_h3TerminalForcingFourthQRadialProductStateMassEnvelopeAt_le_fixedCoefficient_mul_pow_four
#check exists_fixed_h3TerminalForcingFourthQPrimitiveFactor_subsequence_of_stateMassEnvelope_tendstoAtTop
#check exists_fixed_h3TerminalForcingFourthQPrimitiveFactor_subsequence_of_massPath_tendstoAtTop
#print axioms exists_fixed_pair_subsequence_of_h3TerminalForcingFourthQMassPath_tendstoAtTop
#print axioms h3TerminalForcingFourthQPrimitiveFactorAt_nonneg
#print axioms exists_primitive_h3TerminalForcingFourthQRadialProductStateMassEnvelopeAt_le_fixedCoefficient_mul_pow_four
#print axioms exists_fixed_h3TerminalForcingFourthQPrimitiveFactor_subsequence_of_stateMassEnvelope_tendstoAtTop
#print axioms exists_fixed_h3TerminalForcingFourthQPrimitiveFactor_subsequence_of_massPath_tendstoAtTop
