import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.Schwartz.Spectral.Classicalization.PhysicalL2JetContinuity

/-!
# Classicalization: physical H³ tail canonical path

`PhysicalL2JetContinuity` removes the spectral-topology obligation from the
preterminal overlap construction:

    physical H³ L²-jet continuity
      → Fourier H³-jet continuity
      → weighted spectral-state continuity.

This file threads that bridge through `PreterminalTailCanonicalPath`.

The resulting canonical path no longer takes an explicit spectral continuity
proof.  It is generated directly from

* the retained canonical H³ tail data, and
* strong continuity of every physical ordered H³ `L²` jet coordinate.

The final overlap theorem therefore has only two substantive analytic inputs:

1. physical H³ `L²` jet continuity on the overlap interval;
2. the restarted heat--Leray mild identity for the resulting canonical path.

No separate spectral continuity hypothesis remains in the API.
-/

namespace PrimeTensor
namespace Bridge
namespace Euclidean

open MeasureTheory Filter Set
open scoped ENNReal NNReal Interval Topology BigOperators

noncomputable section

noncomputable local instance axisFintypeH3SchwartzClassicalizationPhysicalTailCanonicalPath
    (d : Depth) :
    Fintype (PrimeTensor.Axis d) :=
  Fintype.ofFinite (PrimeTensor.Axis d)

/-- The canonical weighted spectral-state map is continuous whenever the
physical ordered H³ `L²` jet is continuous.  This named wrapper fixes the exact
proof term used by the path constructor below. -/
theorem h3PreterminalTailCanonicalSpectralStateContinuousOnElapsed_of_l2Jet
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t τ E : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (hEnd : t + τ < T)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hL2 :
      H3PreterminalCanonicalL2JetContinuousOnElapsed
        hNS ht hEnd hTail) :
    Continuous
      (fun q : Set.Icc (0 : ℝ) τ =>
        h3PreterminalCanonicalSpectralStateOnElapsed
          hNS
          ht
          hEnd
          (canonicalH3TailDataFrom_integrableOnElapsed
            hEnd hTail)
          q) := by
  exact
    continuous_h3PreterminalCanonicalSpectralStateOnElapsed_of_l2Jet
      hNS ht hEnd hTail hL2

/-- Canonical physical weighted-spectral path of the old solution, with
continuity generated from the physical H³ `L²` jet rather than supplied as an
independent spectral hypothesis. -/
noncomputable def h3PreterminalTailCanonicalSpectralPhysicalPathOfL2Jet
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t τ E : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (hEnd : t + τ < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hL2 :
      H3PreterminalCanonicalL2JetContinuousOnElapsed
        hNS ht hEnd hTail) :
    H3SpectralPhysicalVelocityPath τ :=
  h3PreterminalCanonicalSpectralPhysicalPath
    hNS
    ht
    hEnd
    hE
    (canonicalH3TailDataFrom_integrableOnElapsed
      hEnd hTail)
    (canonicalH3TailDataFrom_energyOnElapsed_le_twoE
      hE hEnd hTail)
    (h3PreterminalTailCanonicalSpectralStateContinuousOnElapsed_of_l2Jet
      hNS ht hEnd hTail hL2)

@[simp]
theorem h3PreterminalTailCanonicalSpectralPhysicalPathOfL2Jet_apply
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t τ E : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (hEnd : t + τ < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hL2 :
      H3PreterminalCanonicalL2JetContinuousOnElapsed
        hNS ht hEnd hTail)
    (q : Set.Icc (0 : ℝ) τ) :
    h3PreterminalTailCanonicalSpectralPhysicalPathOfL2Jet
        hNS ht hEnd hE hTail hL2 q
      =
    h3PreterminalCanonicalSpectralStateOnElapsed
      hNS
      ht
      hEnd
      (canonicalH3TailDataFrom_integrableOnElapsed
        hEnd hTail)
      q := by
  rfl

/-- Tail H³ data plus physical H³ `L²` jet continuity reduce the local
preterminal overlap witness to the restarted mild equation alone.

The path occurring in the mild equation is the canonical old-solution path
whose continuity was generated by `PhysicalL2JetContinuity`. -/
theorem h3PreterminalSpectralOverlapWitnessAt_of_tailL2CanonicalPath
    {ν E : ℝ}
    (hν : 0 < ν)
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t τ : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (hτ : 0 ≤ τ)
    (hEnd : t + τ < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hL2 :
      H3PreterminalCanonicalL2JetContinuousOnElapsed
        hNS ht hEnd hTail)
    (hMild :
      ∀ s : H3UnitTime,
        h3SpectralVelocityHeatApplyNN
            ν hν.le
            (h3PhysicalTimeNN τ hτ s)
            (h3PreterminalCanonicalAnchorSpectralState
              hNS
              ht
              (canonicalH3TailDataFrom_at_anchor
                ht hTail).1)
          -
        h3SpectralFinHeatLerayDuhamel
            ν
            (h3PhysicalTime τ s)
            hν
            (h3PathPhysicalRealExtension
              τ
              (h3SpectralNormalizedPathOfPhysical
                hτ
                (h3PreterminalTailCanonicalSpectralPhysicalPathOfL2Jet
                  hNS ht hEnd hE hTail hL2)))
            (h3PathPhysicalRealExtension
              τ
              (h3SpectralNormalizedPathOfPhysical
                hτ
                (h3PreterminalTailCanonicalSpectralPhysicalPathOfL2Jet
                  hNS ht hEnd hE hTail hL2)))
          =
        h3PreterminalTailCanonicalSpectralPhysicalPathOfL2Jet
          hNS ht hEnd hE hTail hL2
          (h3PhysicalTimeMap τ hτ s)) :
    H3PreterminalSpectralOverlapWitnessAt
      ν
      E
      hν
      (h3PreterminalCanonicalAnchorSpectralState
        hNS
        ht
        (canonicalH3TailDataFrom_at_anchor
          ht hTail).1)
      u
      t
      τ
      hτ := by
  let hCont :
      Continuous
        (fun q : Set.Icc (0 : ℝ) τ =>
          h3PreterminalCanonicalSpectralStateOnElapsed
            hNS
            ht
            hEnd
            (canonicalH3TailDataFrom_integrableOnElapsed
              hEnd hTail)
            q) :=
    h3PreterminalTailCanonicalSpectralStateContinuousOnElapsed_of_l2Jet
      hNS ht hEnd hTail hL2

  apply
    h3PreterminalSpectralOverlapWitnessAt_of_tailCanonicalPath
      hν
      hNS
      ht
      hτ
      hEnd
      hE
      hTail
      hCont

  intro s

  simpa only [
    h3PreterminalTailCanonicalSpectralPhysicalPathOfL2Jet,
    hCont
  ] using hMild s

end
end Euclidean
end Bridge
end PrimeTensor
