import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.Schwartz.Spectral.Classicalization.PhysicalTailEndpointCanonicalPhysicalL2DefectOrthogonality
import Mathlib.Analysis.InnerProductSpace.Projection.Submodule

/-!
# Classicalization: reduce the physical `L²` vector identity to admissible-closure membership

`PhysicalTailEndpointCanonicalPhysicalL2DefectOrthogonality` constructs the
physical Hilbert-space evolution defect

    D := (U(τ) - U(0)) - ∫₀^τ R(s) ds

and proves that every currently admissible compact smooth solenoidal test state
annihilates it.

This file performs the exact Hilbert-space closure reduction and nothing more.
Let `S` be the current admissible test set and let

    K := span_ℝ S.

The generator orthogonality theorem extends by linearity to

    D ∈ Kᗮ.

The closed Hilbert space generated by the admissible tests is

    closure(K) = Kᗮᗮ.

Consequently, if the defect also belongs to `closure(K)`, then

    D ∈ Kᗮ ∩ Kᗮᗮ = {0},

so the desired physical `L²` vector evolution identity follows.

We package the remaining membership frontier in the slightly stronger and more
useful form that the two terms separately belong to the admissible closed span:

* the endpoint velocity increment;
* the Bochner integral of the projected RHS.

Since the closed span is a submodule, those two facts imply defect membership
and hence the vector identity.

No claim is made here that the admissible closed span is already the full
solenoidal `L²` subspace.  Establishing that identification, or directly
proving the two membership facts by a Leray/density argument, is the next
analytic checkpoint.
-/

namespace PrimeTensor
namespace Bridge
namespace Euclidean

open MeasureTheory Filter Set
open scoped BigOperators ENNReal NNReal Interval Topology InnerProductSpace

noncomputable section

noncomputable local instance axisFintypeH3PhysicalTailEndpointCanonicalPhysicalL2AdmissibleClosureReduction
    (d : Depth) :
    Fintype (PrimeTensor.Axis d) :=
  Fintype.ofFinite (PrimeTensor.Axis d)

noncomputable local instance point3MeasureSpaceH3PhysicalTailEndpointCanonicalPhysicalL2AdmissibleClosureReduction :
    MeasureSpace Point3 :=
  @MeasureTheory.MeasureSpace.pi
    (PrimeTensor.Axis Depth.three)
    (Fintype.ofFinite (PrimeTensor.Axis Depth.three))
    (fun _ : PrimeTensor.Axis Depth.three => ℝ)
    (fun _ : PrimeTensor.Axis Depth.three => Real.measureSpace)

/-- Algebraic real span of the currently admissible compact smooth solenoidal
physical `L²` test states. -/
noncomputable def h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2Span
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail) :
    Submodule ℝ H3PhysicalRealFinVectorL2Hilbert :=
  Submodule.span ℝ
    (h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2Set
      hNS ht htau hEnd hE hTail hEndpoint)

/-- Closed Hilbert submodule generated by the currently admissible physical
`L²` tests. -/
noncomputable def h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2ClosedSpan
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail) :
    Submodule ℝ H3PhysicalRealFinVectorL2Hilbert :=
  (h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2Span
    hNS ht htau hEnd hE hTail hEndpoint).topologicalClosure

/-- The closed admissible span is the double orthogonal complement of its
algebraic span. -/
theorem h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2ClosedSpan_eq_orthogonal_orthogonal
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail) :
    h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2ClosedSpan
        hNS ht htau hEnd hE hTail hEndpoint
      =
    (h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2Span
      hNS ht htau hEnd hE hTail hEndpoint)ᗮᗮ := by
  unfold h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2ClosedSpan
  symm
  exact
    Submodule.orthogonal_orthogonal_eq_closure
      (h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2Span
        hNS ht htau hEnd hE hTail hEndpoint)

/-- Generator orthogonality extends by linearity to the entire algebraic span:
the physical evolution defect lies in the orthogonal complement of the current
admissible test span. -/
theorem h3PreterminalTailCanonicalPhysicalL2EvolutionDefect_mem_admissibleWeakTestSpan_orthogonal
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail) :
    h3PreterminalTailCanonicalPhysicalL2EvolutionDefect
        hNS ht htau hEnd hE hTail hEndpoint
      ∈
    (h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2Span
      hNS ht htau hEnd hE hTail hEndpoint)ᗮ := by
  let D : H3PhysicalRealFinVectorL2Hilbert :=
    h3PreterminalTailCanonicalPhysicalL2EvolutionDefect
      hNS ht htau hEnd hE hTail hEndpoint

  let S : Set H3PhysicalRealFinVectorL2Hilbert :=
    h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2Set
      hNS ht htau hEnd hE hTail hEndpoint

  let K : Submodule ℝ H3PhysicalRealFinVectorL2Hilbert :=
    Submodule.span ℝ S

  let L : H3PhysicalRealFinVectorL2Hilbert →L[ℝ] ℝ :=
    innerSL ℝ D

  have hGeneratorKer : S ⊆ L.ker := by
    intro Φ hΦ

    have hPair : inner ℝ Φ D = 0 := by
      dsimp only [D, S]
      exact
        h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2Set_subset_evolutionDefect_zeroPairing
          hNS ht htau hEnd hE hTail hEndpoint hΦ

    change L Φ = 0
    dsimp only [L]

    simpa only [innerSL_apply_apply, real_inner_comm] using hPair

  have hSpanKer : K ≤ L.ker := by
    dsimp only [K]
    exact Submodule.span_le.mpr hGeneratorKer

  change D ∈ Kᗮ
  rw [Submodule.mem_orthogonal']

  intro Φ hΦ

  have hKer : Φ ∈ L.ker := hSpanKer hΦ

  change L Φ = 0 at hKer
  dsimp only [L] at hKer

  simpa only [innerSL_apply_apply] using hKer

/-- If the physical evolution defect belongs to the closed span generated by
the currently admissible tests, then the defect is zero. -/
theorem h3PreterminalTailCanonicalPhysicalL2EvolutionDefect_eq_zero_of_mem_admissibleWeakTestClosedSpan
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail)
    (hMem :
      h3PreterminalTailCanonicalPhysicalL2EvolutionDefect
          hNS ht htau hEnd hE hTail hEndpoint
        ∈
      h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2ClosedSpan
        hNS ht htau hEnd hE hTail hEndpoint) :
    h3PreterminalTailCanonicalPhysicalL2EvolutionDefect
        hNS ht htau hEnd hE hTail hEndpoint
      =
    0 := by
  let D : H3PhysicalRealFinVectorL2Hilbert :=
    h3PreterminalTailCanonicalPhysicalL2EvolutionDefect
      hNS ht htau hEnd hE hTail hEndpoint

  let K : Submodule ℝ H3PhysicalRealFinVectorL2Hilbert :=
    h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2Span
      hNS ht htau hEnd hE hTail hEndpoint

  have hOrth : D ∈ Kᗮ := by
    dsimp only [D, K]
    exact
      h3PreterminalTailCanonicalPhysicalL2EvolutionDefect_mem_admissibleWeakTestSpan_orthogonal
        hNS ht htau hEnd hE hTail hEndpoint

  have hDouble : D ∈ Kᗮᗮ := by
    have hClosedEq :
        h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2ClosedSpan
            hNS ht htau hEnd hE hTail hEndpoint
          =
        Kᗮᗮ := by
      dsimp only [K]
      exact
        h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2ClosedSpan_eq_orthogonal_orthogonal
          hNS ht htau hEnd hE hTail hEndpoint

    rw [← hClosedEq]
    exact hMem

  have hBoth : D ∈ Kᗮ ⊓ Kᗮᗮ := ⟨hOrth, hDouble⟩

  have hBot : D ∈ (⊥ : Submodule ℝ H3PhysicalRealFinVectorL2Hilbert) := by
    rw [← Submodule.inf_orthogonal_eq_bot Kᗮ]
    exact hBoth

  simpa using hBot

/-- Exact remaining closure-membership frontier for the two physical `L²`
evolution terms separately. -/
def H3PreterminalTailCanonicalPhysicalL2EvolutionTermsInAdmissibleWeakTestClosedSpan
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail) : Prop :=
  h3PreterminalTailCanonicalVelocityIncrementPhysicalL2Hilbert
      hNS ht htau hEnd hTail
    ∈
  h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2ClosedSpan
      hNS ht htau hEnd hE hTail hEndpoint
  ∧
  h3PreterminalTailCanonicalProjectedRHSPhysicalL2BochnerIntegralHilbert
      hNS ht htau hEnd hE hTail hEndpoint
    ∈
  h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2ClosedSpan
      hNS ht htau hEnd hE hTail hEndpoint

/-- Once the two physical `L²` evolution terms belong to the admissible closed
span, the evolution defect belongs there as well. -/
theorem h3PreterminalTailCanonicalPhysicalL2EvolutionDefect_mem_admissibleWeakTestClosedSpan_of_terms
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail)
    (hTerms :
      H3PreterminalTailCanonicalPhysicalL2EvolutionTermsInAdmissibleWeakTestClosedSpan
        hNS ht htau hEnd hE hTail hEndpoint) :
    h3PreterminalTailCanonicalPhysicalL2EvolutionDefect
        hNS ht htau hEnd hE hTail hEndpoint
      ∈
    h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2ClosedSpan
      hNS ht htau hEnd hE hTail hEndpoint := by
  rcases hTerms with ⟨hVelocity, hRHS⟩

  unfold h3PreterminalTailCanonicalPhysicalL2EvolutionDefect

  exact
    (h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2ClosedSpan
      hNS ht htau hEnd hE hTail hEndpoint).sub_mem
        hVelocity hRHS

/-- Conditional vector evolution identity at the exact remaining
functional-analytic frontier. -/
theorem h3PreterminalTailCanonicalVelocityIncrementPhysicalL2Hilbert_eq_BochnerProjectedRHS_of_terms_mem_admissibleWeakTestClosedSpan
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail)
    (hTerms :
      H3PreterminalTailCanonicalPhysicalL2EvolutionTermsInAdmissibleWeakTestClosedSpan
        hNS ht htau hEnd hE hTail hEndpoint) :
    h3PreterminalTailCanonicalVelocityIncrementPhysicalL2Hilbert
        hNS ht htau hEnd hTail
      =
    h3PreterminalTailCanonicalProjectedRHSPhysicalL2BochnerIntegralHilbert
      hNS ht htau hEnd hE hTail hEndpoint := by
  have hDefectMem :=
    h3PreterminalTailCanonicalPhysicalL2EvolutionDefect_mem_admissibleWeakTestClosedSpan_of_terms
      hNS ht htau hEnd hE hTail hEndpoint hTerms

  have hDefectZero :=
    h3PreterminalTailCanonicalPhysicalL2EvolutionDefect_eq_zero_of_mem_admissibleWeakTestClosedSpan
      hNS ht htau hEnd hE hTail hEndpoint hDefectMem

  unfold h3PreterminalTailCanonicalPhysicalL2EvolutionDefect at hDefectZero

  exact sub_eq_zero.mp hDefectZero

end

end Euclidean
end Bridge
end PrimeTensor
