import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.Schwartz.Spectral.Nonlinear.Forcing.Pressure.Multiplier

/-!
# Bounded Fourier representation of the H³ pressure

The pressure multiplier from the Leray complement was initially written as

    p̂(ξ)
      =
    - (Σₖ conj(dₖ(ξ)) Fₖ(ξ)) / Q(ξ),

with the quotient set to zero at zero gradient frequency.

For the nonlinear forcing

    Fₖ = Σⱼ dⱼ rawConv(Uₖ,Vⱼ),

the quotient can be regrouped as

    p̂(ξ)
      =
    - Σₖ Σⱼ
        Rⱼₖ(ξ) rawConv(Uₖ,Vⱼ)(ξ),

where `Rⱼₖ` is the rank-one Leray coefficient

    dⱼ conj(dₖ) / Q.

This is the analytically useful form: every `Rⱼₖ` is measurable and has norm
at most one, including at zero frequency.  Thus the apparent `1 / Q`
singularity has disappeared completely.

As the first consequence, the pressure Fourier amplitude is `L¹` for arbitrary
H³ velocity states.  The next rung will retain one raw Fourier moment and
construct the canonical `C¹` pressure representative.
-/

namespace PrimeTensor
namespace Bridge
namespace Euclidean

open MeasureTheory Filter
open scoped BigOperators ENNReal NNReal

noncomputable section

noncomputable local instance axisFintypeH3PressureBounded
    (d : Depth) :
    Fintype (PrimeTensor.Axis d) :=
  Fintype.ofFinite (PrimeTensor.Axis d)

/-- Pointwise bounded-rank-one representation of the pressure Fourier
multiplier. -/
theorem h3RawFinPressureFourier_eq_neg_sum_rankOne_rawProductConvolution
    (U V : H3SpectralFinVectorState)
    (ξ : H3FourierPoint3) :
    h3RawFinPressureFourier U V ξ
      =
    - ∑ k : Fin 3,
        ∑ j : Fin 3,
          h3LerayRankOneCoefficient ξ j k *
            h3RawProductConvolution (U k) (V j) ξ := by
  by_cases hq : h3FourierGradientSquare ξ = 0
  · simp [
      h3RawFinPressureFourier,
      h3RawFinLerayComplementScalar,
      h3LerayRankOneCoefficient,
      hq
    ]

  · simp only [
      h3RawFinPressureFourier,
      h3RawFinLerayComplementScalar,
      h3RawFinOuterProductDivergence,
      h3LerayRankOneCoefficient,
      dif_neg hq
    ]

    congr 1

    rw [Finset.sum_div]

    apply Finset.sum_congr rfl
    intro k hk

    rw [Finset.mul_sum, Finset.sum_div]

    apply Finset.sum_congr rfl
    intro j hj

    ring

/-- Functional form of the bounded pressure representation. -/
theorem h3RawFinPressureFourier_eq_neg_sum_rankOne_rawProductConvolution_fun
    (U V : H3SpectralFinVectorState) :
    h3RawFinPressureFourier U V
      =
    fun ξ : H3FourierPoint3 =>
      - ∑ k : Fin 3,
          ∑ j : Fin 3,
            h3LerayRankOneCoefficient ξ j k *
              h3RawProductConvolution (U k) (V j) ξ := by
  funext ξ
  exact
    h3RawFinPressureFourier_eq_neg_sum_rankOne_rawProductConvolution
      U V ξ

/-- One bounded rank-one Leray coefficient times one raw H³ product
convolution is integrable. -/
theorem h3LerayRankOneCoefficient_mul_rawProductConvolution_integrable
    (F G : H3SpectralScalarState)
    (j k : Fin 3) :
    Integrable
      (fun ξ : H3FourierPoint3 =>
        h3LerayRankOneCoefficient ξ j k *
          h3RawProductConvolution F G ξ)
      (volume : Measure H3FourierPoint3) := by
  have hConv :
      Integrable
        (h3RawProductConvolution F G)
        (volume : Measure H3FourierPoint3) :=
    h3RawProductConvolution_integrable F G

  have hTargetMeas :
      AEStronglyMeasurable
        (fun ξ : H3FourierPoint3 =>
          h3LerayRankOneCoefficient ξ j k *
            h3RawProductConvolution F G ξ)
        (volume : Measure H3FourierPoint3) := by
    exact
      (measurable_h3LerayRankOneCoefficient j k).aestronglyMeasurable.mul
        hConv.1

  refine Integrable.mono' hConv.norm hTargetMeas ?_
  filter_upwards with ξ

  have hBound :
      ‖h3LerayRankOneCoefficient ξ j k *
          h3RawProductConvolution F G ξ‖
        ≤
      ‖h3RawProductConvolution F G ξ‖ := by
    rw [norm_mul]
    simpa using
      mul_le_mul_of_nonneg_right
        (norm_h3LerayRankOneCoefficient_le_one ξ j k)
        (norm_nonneg (h3RawProductConvolution F G ξ))

  simpa [
    Real.norm_eq_abs,
    abs_of_nonneg (norm_nonneg (h3RawProductConvolution F G ξ))
  ] using hBound

/-- The pressure Fourier amplitude generated by arbitrary H³ velocity states is
integrable.  This is the zeroth-moment input for its ordinary inverse Fourier
reconstruction. -/
theorem h3RawFinPressureFourier_integrable
    (U V : H3SpectralFinVectorState) :
    Integrable
      (h3RawFinPressureFourier U V)
      (volume : Measure H3FourierPoint3) := by
  rw [
    h3RawFinPressureFourier_eq_neg_sum_rankOne_rawProductConvolution_fun
  ]

  have hSum :
      Integrable
        (fun ξ : H3FourierPoint3 =>
          ∑ k : Fin 3,
            ∑ j : Fin 3,
              h3LerayRankOneCoefficient ξ j k *
                h3RawProductConvolution (U k) (V j) ξ)
        (volume : Measure H3FourierPoint3) := by
    exact
      integrable_finset_sum
        (Finset.univ : Finset (Fin 3))
        (fun k _ =>
          integrable_finset_sum
            (Finset.univ : Finset (Fin 3))
            (fun j _ =>
              h3LerayRankOneCoefficient_mul_rawProductConvolution_integrable
                (U k) (V j) j k))

  exact hSum.neg

end

end Euclidean
end Bridge
end PrimeTensor
