import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.Schwartz.Spectral.Classicalization.Physical.Tail.Endpoint.Canonical.Physical.L2.Admissible.Closure.Leray.Density.Dual.Reduction
import PrimeTensor.Bridge.Euclidean.Partials.Mixed

/-!
# Classicalization: compact smooth curl tests

The physical Leray-density frontier has been reduced to the following dual
uniqueness statement:

    a Leray-fixed physical `L²` vector orthogonal to every compact smooth
    divergence-free weak test must vanish.

The next analytic step is to extract distributional curl-free information from
that annihilation hypothesis.

This file constructs the three elementary compactly supported smooth curl
tests generated by one scalar weak test `ψ`:

    curl01(ψ) = ( ∂₁ψ, -∂₀ψ,      0 ),
    curl02(ψ) = ( ∂₂ψ,      0, -∂₀ψ ),
    curl12(ψ) = (     0,  ∂₂ψ, -∂₁ψ ).

Each is divergence-free because mixed partials commute.

The point of keeping these three generators explicit is that the next file can
feed them directly into the annihilator hypothesis and obtain the three weak
curl identities without introducing a separate abstract vector-potential API.

No density theorem is proved here.  This file closes only the exact
compact-test differential algebra needed for the dual uniqueness argument.
-/

namespace PrimeTensor
namespace Bridge
namespace Euclidean

open MeasureTheory Filter Set
open scoped BigOperators ENNReal NNReal Interval Topology InnerProductSpace LineDeriv

noncomputable section

noncomputable local instance axisFintypeH3PhysicalL2AdmissibleClosureLerayDensityDualCurlTest
    (d : Depth) :
    Fintype (PrimeTensor.Axis d) :=
  Fintype.ofFinite (PrimeTensor.Axis d)

noncomputable local instance point3MeasureSpaceH3PhysicalL2AdmissibleClosureLerayDensityDualCurlTest :
    MeasureSpace Point3 :=
  @MeasureTheory.MeasureSpace.pi
    (PrimeTensor.Axis Depth.three)
    (Fintype.ofFinite (PrimeTensor.Axis Depth.three))
    (fun _ : PrimeTensor.Axis Depth.three => ℝ)
    (fun _ : PrimeTensor.Axis Depth.three => Real.measureSpace)

/-! ## Linearity of bundled weak-test derivatives -/

@[simp]
theorem h3WeakTestFunctionSpatialDerivative_neg
    (a : PrimeTensor.Axis Depth.three)
    (ψ : H3WeakTestFunction) :
    h3WeakTestFunctionSpatialDerivative a (-ψ)
      =
    - h3WeakTestFunctionSpatialDerivative a ψ := by
  unfold h3WeakTestFunctionSpatialDerivative
  exact map_neg _ ψ

@[simp]
theorem h3WeakTestFunctionSpatialDerivative_zero
    (a : PrimeTensor.Axis Depth.three) :
    h3WeakTestFunctionSpatialDerivative
        a
        (0 : H3WeakTestFunction)
      =
    0 := by
  unfold h3WeakTestFunctionSpatialDerivative
  exact map_zero _

/-! ## Mixed weak-test derivatives commute -/

/-- Bundled coordinate derivatives of a compact smooth scalar weak test
commute.  The proof transports both bundled derivatives to the project's
concrete `spatial3.d` operator and applies the existing `C²` Clairaut theorem. -/
theorem h3WeakTestFunctionSpatialDerivative_comm
    (ψ : H3WeakTestFunction)
    (i j : Fin 3) :
    h3WeakTestFunctionSpatialDerivative
        (h3AxisOfFin3 i)
        (h3WeakTestFunctionSpatialDerivative
          (h3AxisOfFin3 j)
          ψ)
      =
    h3WeakTestFunctionSpatialDerivative
        (h3AxisOfFin3 j)
        (h3WeakTestFunctionSpatialDerivative
          (h3AxisOfFin3 i)
          ψ) := by
  have hψC2 :
      SpatialC2
        (ψ : Point3 → ℝ) := by
    unfold SpatialC2
    exact
      ψ.contDiff.of_le
        (by norm_num)

  ext x

  have hOuterIJ :
      (h3WeakTestFunctionSpatialDerivative
          (h3AxisOfFin3 i)
          (h3WeakTestFunctionSpatialDerivative
            (h3AxisOfFin3 j)
            ψ) :
        Point3 → ℝ)
        x
        =
      spatial3.d
        (h3AxisOfFin3 i)
        (h3WeakTestFunctionSpatialDerivative
          (h3AxisOfFin3 j)
          ψ :
          Point3 → ℝ)
        x :=
    congrFun
      (h3WeakTestFunctionSpatialDerivative_eq_spatial3_d
        (h3WeakTestFunctionSpatialDerivative
          (h3AxisOfFin3 j)
          ψ)
        i)
      x

  have hOuterJI :
      (h3WeakTestFunctionSpatialDerivative
          (h3AxisOfFin3 j)
          (h3WeakTestFunctionSpatialDerivative
            (h3AxisOfFin3 i)
            ψ) :
        Point3 → ℝ)
        x
        =
      spatial3.d
        (h3AxisOfFin3 j)
        (h3WeakTestFunctionSpatialDerivative
          (h3AxisOfFin3 i)
          ψ :
          Point3 → ℝ)
        x :=
    congrFun
      (h3WeakTestFunctionSpatialDerivative_eq_spatial3_d
        (h3WeakTestFunctionSpatialDerivative
          (h3AxisOfFin3 i)
          ψ)
        j)
      x

  have hInnerI :
      (h3WeakTestFunctionSpatialDerivative
          (h3AxisOfFin3 i)
          ψ :
        Point3 → ℝ)
        =
      spatial3.d
        (h3AxisOfFin3 i)
        (ψ : Point3 → ℝ) :=
    h3WeakTestFunctionSpatialDerivative_eq_spatial3_d
      ψ i

  have hInnerJ :
      (h3WeakTestFunctionSpatialDerivative
          (h3AxisOfFin3 j)
          ψ :
        Point3 → ℝ)
        =
      spatial3.d
        (h3AxisOfFin3 j)
        (ψ : Point3 → ℝ) :=
    h3WeakTestFunctionSpatialDerivative_eq_spatial3_d
      ψ j

  calc
    (h3WeakTestFunctionSpatialDerivative
        (h3AxisOfFin3 i)
        (h3WeakTestFunctionSpatialDerivative
          (h3AxisOfFin3 j)
          ψ))
        x
        =
      spatial3.d
        (h3AxisOfFin3 i)
        (h3WeakTestFunctionSpatialDerivative
          (h3AxisOfFin3 j)
          ψ :
          Point3 → ℝ)
        x :=
      hOuterIJ

    _ =
      spatial3.d
        (h3AxisOfFin3 i)
        (spatial3.d
          (h3AxisOfFin3 j)
          (ψ : Point3 → ℝ))
        x := by
          rw [hInnerJ]

    _ =
      spatial3.d
        (h3AxisOfFin3 j)
        (spatial3.d
          (h3AxisOfFin3 i)
          (ψ : Point3 → ℝ))
        x := by
          exact
            hψC2.spatial_d_comm
              x
              (h3AxisOfFin3 i)
              (h3AxisOfFin3 j)

    _ =
      spatial3.d
        (h3AxisOfFin3 j)
        (h3WeakTestFunctionSpatialDerivative
          (h3AxisOfFin3 i)
          ψ :
          Point3 → ℝ)
        x := by
          rw [hInnerI]

    _ =
      (h3WeakTestFunctionSpatialDerivative
        (h3AxisOfFin3 j)
        (h3WeakTestFunctionSpatialDerivative
          (h3AxisOfFin3 i)
          ψ))
        x :=
      hOuterJI.symm

/-! ## The three elementary curl tests -/

/-- The `01` skew-derivative test generated by `ψ`. -/
noncomputable def h3WeakTestCurl01
    (ψ : H3WeakTestFunction) :
    H3WeakTestVector :=
  ![
    h3WeakTestFunctionSpatialDerivative
      (h3AxisOfFin3 1)
      ψ,
    -
    h3WeakTestFunctionSpatialDerivative
      (h3AxisOfFin3 0)
      ψ,
    (0 : H3WeakTestFunction)
  ]

/-- The `02` skew-derivative test generated by `ψ`. -/
noncomputable def h3WeakTestCurl02
    (ψ : H3WeakTestFunction) :
    H3WeakTestVector :=
  ![
    h3WeakTestFunctionSpatialDerivative
      (h3AxisOfFin3 2)
      ψ,
    (0 : H3WeakTestFunction),
    -
    h3WeakTestFunctionSpatialDerivative
      (h3AxisOfFin3 0)
      ψ
  ]

/-- The `12` skew-derivative test generated by `ψ`. -/
noncomputable def h3WeakTestCurl12
    (ψ : H3WeakTestFunction) :
    H3WeakTestVector :=
  ![
    (0 : H3WeakTestFunction),
    h3WeakTestFunctionSpatialDerivative
      (h3AxisOfFin3 2)
      ψ,
    -
    h3WeakTestFunctionSpatialDerivative
      (h3AxisOfFin3 1)
      ψ
  ]

@[simp]
theorem h3WeakTestCurl01_apply_zero
    (ψ : H3WeakTestFunction) :
    h3WeakTestCurl01 ψ 0
      =
    h3WeakTestFunctionSpatialDerivative
      (h3AxisOfFin3 1)
      ψ := rfl

@[simp]
theorem h3WeakTestCurl01_apply_one
    (ψ : H3WeakTestFunction) :
    h3WeakTestCurl01 ψ 1
      =
    -
    h3WeakTestFunctionSpatialDerivative
      (h3AxisOfFin3 0)
      ψ := rfl

@[simp]
theorem h3WeakTestCurl01_apply_two
    (ψ : H3WeakTestFunction) :
    h3WeakTestCurl01 ψ 2
      =
    (0 : H3WeakTestFunction) := rfl

@[simp]
theorem h3WeakTestCurl02_apply_zero
    (ψ : H3WeakTestFunction) :
    h3WeakTestCurl02 ψ 0
      =
    h3WeakTestFunctionSpatialDerivative
      (h3AxisOfFin3 2)
      ψ := rfl

@[simp]
theorem h3WeakTestCurl02_apply_one
    (ψ : H3WeakTestFunction) :
    h3WeakTestCurl02 ψ 1
      =
    (0 : H3WeakTestFunction) := rfl

@[simp]
theorem h3WeakTestCurl02_apply_two
    (ψ : H3WeakTestFunction) :
    h3WeakTestCurl02 ψ 2
      =
    -
    h3WeakTestFunctionSpatialDerivative
      (h3AxisOfFin3 0)
      ψ := rfl

@[simp]
theorem h3WeakTestCurl12_apply_zero
    (ψ : H3WeakTestFunction) :
    h3WeakTestCurl12 ψ 0
      =
    (0 : H3WeakTestFunction) := rfl

@[simp]
theorem h3WeakTestCurl12_apply_one
    (ψ : H3WeakTestFunction) :
    h3WeakTestCurl12 ψ 1
      =
    h3WeakTestFunctionSpatialDerivative
      (h3AxisOfFin3 2)
      ψ := rfl

@[simp]
theorem h3WeakTestCurl12_apply_two
    (ψ : H3WeakTestFunction) :
    h3WeakTestCurl12 ψ 2
      =
    -
    h3WeakTestFunctionSpatialDerivative
      (h3AxisOfFin3 1)
      ψ := rfl

/-! ## Every elementary curl test is divergence-free -/

theorem h3WeakTestCurl01_divergenceFree
    (ψ : H3WeakTestFunction) :
    H3WeakTestVectorDivergenceFree
      (h3WeakTestCurl01 ψ) := by
  unfold H3WeakTestVectorDivergenceFree
  rw [Fin.sum_univ_three]

  change
    h3WeakTestFunctionSpatialDerivative
        (h3AxisOfFin3 0)
        (h3WeakTestFunctionSpatialDerivative
          (h3AxisOfFin3 1)
          ψ)
      +
      h3WeakTestFunctionSpatialDerivative
        (h3AxisOfFin3 1)
        (-
          h3WeakTestFunctionSpatialDerivative
            (h3AxisOfFin3 0)
            ψ)
      +
      h3WeakTestFunctionSpatialDerivative
        (h3AxisOfFin3 2)
        (0 : H3WeakTestFunction)
      =
    0

  rw [
    h3WeakTestFunctionSpatialDerivative_neg,
    h3WeakTestFunctionSpatialDerivative_zero,
    h3WeakTestFunctionSpatialDerivative_comm ψ 0 1
  ]

  abel

theorem h3WeakTestCurl02_divergenceFree
    (ψ : H3WeakTestFunction) :
    H3WeakTestVectorDivergenceFree
      (h3WeakTestCurl02 ψ) := by
  unfold H3WeakTestVectorDivergenceFree
  rw [Fin.sum_univ_three]

  change
    h3WeakTestFunctionSpatialDerivative
        (h3AxisOfFin3 0)
        (h3WeakTestFunctionSpatialDerivative
          (h3AxisOfFin3 2)
          ψ)
      +
      h3WeakTestFunctionSpatialDerivative
        (h3AxisOfFin3 1)
        (0 : H3WeakTestFunction)
      +
      h3WeakTestFunctionSpatialDerivative
        (h3AxisOfFin3 2)
        (-
          h3WeakTestFunctionSpatialDerivative
            (h3AxisOfFin3 0)
            ψ)
      =
    0

  rw [
    h3WeakTestFunctionSpatialDerivative_zero,
    h3WeakTestFunctionSpatialDerivative_neg,
    h3WeakTestFunctionSpatialDerivative_comm ψ 0 2
  ]

  abel

theorem h3WeakTestCurl12_divergenceFree
    (ψ : H3WeakTestFunction) :
    H3WeakTestVectorDivergenceFree
      (h3WeakTestCurl12 ψ) := by
  unfold H3WeakTestVectorDivergenceFree
  rw [Fin.sum_univ_three]

  change
    h3WeakTestFunctionSpatialDerivative
        (h3AxisOfFin3 0)
        (0 : H3WeakTestFunction)
      +
      h3WeakTestFunctionSpatialDerivative
        (h3AxisOfFin3 1)
        (h3WeakTestFunctionSpatialDerivative
          (h3AxisOfFin3 2)
          ψ)
      +
      h3WeakTestFunctionSpatialDerivative
        (h3AxisOfFin3 2)
        (-
          h3WeakTestFunctionSpatialDerivative
            (h3AxisOfFin3 1)
            ψ)
      =
    0

  rw [
    h3WeakTestFunctionSpatialDerivative_zero,
    h3WeakTestFunctionSpatialDerivative_neg,
    h3WeakTestFunctionSpatialDerivative_comm ψ 1 2
  ]

  abel

end

end Euclidean
end Bridge
end PrimeTensor
