import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.SchwartzSpectralNonlinearForcingL1

/-!
# Continuous physical reconstruction of the unheated H³ nonlinear forcing

`SchwartzSpectralNonlinearForcingL1` proves that the raw finite-index
Leray-divergence forcing generated by two H³ spectral velocity states is
Fourier `L¹` coordinatewise.

The same H³ deweighting estimate also gives `L²`: after one Fourier
derivative the factor

    ‖ξ‖ W₃(ξ)⁻¹

is uniformly bounded.  Finite divergence summation and the bounded Leray
matrix therefore preserve `L²`.

Thus the unheated nonlinear forcing belongs to `L¹ ∩ L²`.  Its ordinary
inverse Fourier transform is a genuine continuous function, and the generic
`L¹ ∩ L²` reconstruction theorem identifies that function almost everywhere
with the unitary `L²` inverse Fourier transform of the same raw amplitude.

This is the physical endpoint object needed for the near-endpoint Duhamel
bootstrap: the forcing at zero heat lag is now an honest continuous spatial
function, not merely a formal Fourier expression.
-/

namespace PrimeTensor
namespace Bridge
namespace Euclidean

open MeasureTheory Filter Set FourierTransform
open scoped ENNReal NNReal Topology RealInnerProductSpace

noncomputable section

noncomputable local instance axisFintypeH3SchwartzSpectralNonlinearForcingC0Bridge
    (d : Depth) :
    Fintype (PrimeTensor.Axis d) :=
  Fintype.ofFinite (PrimeTensor.Axis d)

noncomputable local instance point3MeasureSpaceH3SchwartzSpectralNonlinearForcingC0Bridge :
    MeasureSpace Point3 :=
  @MeasureTheory.MeasureSpace.pi
    (PrimeTensor.Axis Depth.three)
    (Fintype.ofFinite (PrimeTensor.Axis Depth.three))
    (fun _ : PrimeTensor.Axis Depth.three => ℝ)
    (fun _ : PrimeTensor.Axis Depth.three => Real.measureSpace)

/-! ## The divergence multiplier is also L² -/

/-- The first-moment inverse H³ weight is uniformly bounded by one. -/
theorem h3SobolevFrequencyFirstMomentInv_le_one
    (ξ : H3FourierPoint3) :
    h3SobolevFrequencyFirstMomentInv ξ ≤ 1 := by
  have hStd := h3SobolevFrequencyFirstMomentInv_le_standard ξ
  have hB : 1 ≤ 1 + ‖ξ‖ ^ 2 :=
    le_add_of_nonneg_right (sq_nonneg ‖ξ‖)
  have hBpos : 0 < 1 + ‖ξ‖ ^ 2 := by positivity
  have hBinvNonneg : 0 ≤ (1 + ‖ξ‖ ^ 2)⁻¹ :=
    inv_nonneg.mpr hBpos.le
  have hStdOne : h3StandardInverseBesselWeight ξ ≤ 1 := by
    unfold h3StandardInverseBesselWeight
    calc
      (1 + ‖ξ‖ ^ 2)⁻¹
          = 1 * (1 + ‖ξ‖ ^ 2)⁻¹ := by ring
      _ ≤ (1 + ‖ξ‖ ^ 2) * (1 + ‖ξ‖ ^ 2)⁻¹ :=
        mul_le_mul_of_nonneg_right hB hBinvNonneg
      _ = 1 := mul_inv_cancel₀ (ne_of_gt hBpos)
  exact hStd.trans hStdOne

/-- One divergence derivative of an exact H³ product convolution belongs to
Fourier `L²` as well as `L¹`. -/
theorem h3FourierDerivative_mul_rawProductConvolution_memLp2
    (F G : H3SpectralScalarState)
    (j : Fin 3) :
    MemLp
      (fun ξ : H3FourierPoint3 =>
        h3FourierDerivativeSymbol j ξ *
          h3RawProductConvolution F G ξ)
      2
      (volume : Measure H3FourierPoint3) := by
  let P : H3SpectralScalarState :=
    h3WeightedRawProductConvolutionL2 F G

  have hConvAE :
      h3SpectralScalarRawFourier P
        =ᵐ[(volume : Measure H3FourierPoint3)]
      h3RawProductConvolution F G := by
    dsimp [P]
    exact h3SpectralScalarRawFourier_weightedRawProductConvolutionL2_ae F G

  have hTargetMeas :
      AEStronglyMeasurable
        (fun ξ : H3FourierPoint3 =>
          h3FourierDerivativeSymbol j ξ *
            h3RawProductConvolution F G ξ)
        (volume : Measure H3FourierPoint3) :=
    (h3FourierDerivative_mul_rawProductConvolution_integrable F G j).1

  have hMajorant :
      MemLp
        (fun ξ : H3FourierPoint3 =>
          ((2 * Real.pi : ℝ) : ℂ) * P ξ)
        2
        (volume : Measure H3FourierPoint3) :=
    (MeasureTheory.Lp.memLp P).const_mul
      (((2 * Real.pi : ℝ) : ℂ))

  refine hMajorant.of_le hTargetMeas ?_
  filter_upwards [hConvAE] with ξ hξ

  have hTwoPi : 0 ≤ 2 * Real.pi := by positivity
  have hInvNonneg :
      0 ≤ h3SobolevFrequencyWeightInv ξ := by
    unfold h3SobolevFrequencyWeightInv
    exact inv_nonneg.mpr (h3SobolevFrequencyWeight_pos ξ).le

  have hDerivWeight :
      ‖h3FourierDerivativeSymbol j ξ‖ *
          h3SobolevFrequencyWeightInv ξ
        ≤
      2 * Real.pi := by
    calc
      ‖h3FourierDerivativeSymbol j ξ‖ *
          h3SobolevFrequencyWeightInv ξ
          ≤
        h3FourierGradientMagnitude ξ *
          h3SobolevFrequencyWeightInv ξ :=
        mul_le_mul_of_nonneg_right
          (norm_h3FourierDerivativeSymbol_le_gradientMagnitude j ξ)
          hInvNonneg
      _ =
        (2 * Real.pi) *
          h3SobolevFrequencyFirstMomentInv ξ := by
        unfold h3FourierGradientMagnitude
        unfold h3SobolevFrequencyFirstMomentInv
        ring
      _ ≤ (2 * Real.pi) * 1 :=
        mul_le_mul_of_nonneg_left
          (h3SobolevFrequencyFirstMomentInv_le_one ξ)
          hTwoPi
      _ = 2 * Real.pi := by ring

  rw [← hξ]
  unfold h3SpectralScalarRawFourier
  unfold h3SobolevFrequencyWeightInvComplex
  rw [norm_mul, norm_mul, Complex.norm_real]
  rw [Real.norm_eq_abs, abs_of_nonneg hInvNonneg]
  rw [norm_mul, Complex.norm_real]
  rw [Real.norm_eq_abs, abs_of_nonneg hTwoPi]
  simpa only [mul_assoc] using
    (mul_le_mul_of_nonneg_right
      hDerivWeight
      (norm_nonneg (P ξ)))

/-- Every raw finite divergence coordinate belongs to Fourier `L²`. -/
theorem h3RawFinOuterProductDivergence_memLp2
    (U V : H3SpectralFinVectorState)
    (i : Fin 3) :
    MemLp
      (h3RawFinOuterProductDivergence U V i)
      2
      (volume : Measure H3FourierPoint3) := by
  unfold h3RawFinOuterProductDivergence
  simpa using
    (MeasureTheory.memLp_finsetSum
      (Finset.univ : Finset (Fin 3))
      (fun j _ =>
        h3FourierDerivative_mul_rawProductConvolution_memLp2
          (U i) (V j) j))

/-- A bounded Leray coefficient preserves Fourier `L²` for one raw divergence
coordinate. -/
theorem h3LerayCoefficient_mul_rawFinOuterProductDivergence_memLp2
    (U V : H3SpectralFinVectorState)
    (i k : Fin 3) :
    MemLp
      (fun ξ : H3FourierPoint3 =>
        h3LerayCoefficient ξ i k *
          h3RawFinOuterProductDivergence U V k ξ)
      2
      (volume : Measure H3FourierPoint3) := by
  have hDiv2 := h3RawFinOuterProductDivergence_memLp2 U V k

  have hTargetMeas :
      AEStronglyMeasurable
        (fun ξ : H3FourierPoint3 =>
          h3LerayCoefficient ξ i k *
            h3RawFinOuterProductDivergence U V k ξ)
        (volume : Measure H3FourierPoint3) :=
    (h3LerayCoefficient_mul_rawFinOuterProductDivergence_integrable
      U V i k).1

  have hMajorant :
      MemLp
        (fun ξ : H3FourierPoint3 =>
          (2 : ℂ) * h3RawFinOuterProductDivergence U V k ξ)
        2
        (volume : Measure H3FourierPoint3) :=
    hDiv2.const_mul (2 : ℂ)

  refine hMajorant.of_le hTargetMeas ?_
  filter_upwards with ξ

  rw [norm_mul, norm_mul]
  have hCoeff := norm_h3LerayCoefficient_le_two ξ i k
  norm_num at hCoeff ⊢
  exact
    mul_le_mul_of_nonneg_right
      hCoeff
      (norm_nonneg (h3RawFinOuterProductDivergence U V k ξ))

/-- The complete raw finite Leray-divergence forcing belongs to Fourier `L²`
coordinatewise. -/
theorem h3RawFinLerayOuterProductDivergence_memLp2
    (U V : H3SpectralFinVectorState)
    (i : Fin 3) :
    MemLp
      (h3RawFinLerayOuterProductDivergence U V i)
      2
      (volume : Measure H3FourierPoint3) := by
  unfold h3RawFinLerayOuterProductDivergence
  simpa using
    (MeasureTheory.memLp_finsetSum
      (Finset.univ : Finset (Fin 3))
      (fun k _ =>
        h3LerayCoefficient_mul_rawFinOuterProductDivergence_memLp2
          U V i k))

/-! ## Continuous physical forcing reconstruction -/

/-- Ordinary inverse-Fourier representative of one raw nonlinear forcing
coordinate. -/
noncomputable def h3RawFinLerayOuterProductDivergenceC0Representative
    (U V : H3SpectralFinVectorState)
    (i : Fin 3) :
    H3FourierPoint3 → ℂ :=
  FourierTransformInv.fourierInv
    (h3RawFinLerayOuterProductDivergence U V i)

/-- The ordinary inverse Fourier transform of the raw nonlinear forcing is
continuous. -/
theorem h3RawFinLerayOuterProductDivergenceC0Representative_continuous
    (U V : H3SpectralFinVectorState)
    (i : Fin 3) :
    Continuous
      (h3RawFinLerayOuterProductDivergenceC0Representative U V i) := by
  have hInnerNegContinuous :
      Continuous
        (fun p : H3FourierPoint3 × H3FourierPoint3 =>
          ((-(innerₗ H3FourierPoint3)) p.1) p.2) := by
    change Continuous
      (fun p : H3FourierPoint3 × H3FourierPoint3 =>
        -inner ℝ p.1 p.2)
    exact
      (continuous_inner (𝕜 := ℝ) (E := H3FourierPoint3)).neg

  unfold h3RawFinLerayOuterProductDivergenceC0Representative
  change Continuous
    (VectorFourier.fourierIntegral
      Real.fourierChar
      (volume : Measure H3FourierPoint3)
      (-(innerₗ H3FourierPoint3))
      (h3RawFinLerayOuterProductDivergence U V i))
  exact
    VectorFourier.fourierIntegral_continuous
      Real.continuous_fourierChar
      hInnerNegContinuous
      (h3RawFinLerayOuterProductDivergence_integrable U V i)

/-- Canonical `L²` package of the same raw forcing amplitude. -/
noncomputable def h3RawFinLerayOuterProductDivergenceFourierL2
    (U V : H3SpectralFinVectorState)
    (i : Fin 3) :
    H3FourierComplexL2 :=
  (h3RawFinLerayOuterProductDivergence_memLp2 U V i).toLp
    (h3RawFinLerayOuterProductDivergence U V i)

/-- Canonical unitary `L²` inverse-Fourier reconstruction of the raw forcing. -/
noncomputable def h3RawFinLerayOuterProductDivergencePhysicalL2
    (U V : H3SpectralFinVectorState)
    (i : Fin 3) :
    H3FourierComplexL2 :=
  (MeasureTheory.Lp.fourierTransformₗᵢ H3FourierPoint3 ℂ).symm
    (h3RawFinLerayOuterProductDivergenceFourierL2 U V i)

/-- The continuous ordinary reconstruction and the canonical unitary `L²`
reconstruction are the same almost everywhere. -/
theorem h3RawFinLerayOuterProductDivergenceC0Representative_ae_eq_physicalL2
    (U V : H3SpectralFinVectorState)
    (i : Fin 3) :
    h3RawFinLerayOuterProductDivergenceC0Representative U V i
      =ᵐ[(volume : Measure H3FourierPoint3)]
    ((h3RawFinLerayOuterProductDivergencePhysicalL2 U V i : H3FourierComplexL2) :
      H3FourierPoint3 → ℂ) := by
  unfold h3RawFinLerayOuterProductDivergenceC0Representative
  unfold h3RawFinLerayOuterProductDivergencePhysicalL2
  unfold h3RawFinLerayOuterProductDivergenceFourierL2
  exact
    h3FourierInv_integrable_memLp2_ae_eq_L2
      (h3RawFinLerayOuterProductDivergence_integrable U V i)
      (h3RawFinLerayOuterProductDivergence_memLp2 U V i)

/-- Continuous forcing representative on the project's `Point3` carrier. -/
noncomputable def h3RawFinLerayOuterProductDivergenceC0RepresentativeOnPoint3
    (U V : H3SpectralFinVectorState)
    (i : Fin 3) :
    Point3 → ℂ :=
  fun x =>
    h3RawFinLerayOuterProductDivergenceC0Representative U V i
      ((WithLp.toLp 2 : Point3 → H3FourierPoint3) x)

/-- Transport through the canonical finite-dimensional `WithLp` equivalence
preserves continuity. -/
theorem h3RawFinLerayOuterProductDivergenceC0RepresentativeOnPoint3_continuous
    (U V : H3SpectralFinVectorState)
    (i : Fin 3) :
    Continuous
      (h3RawFinLerayOuterProductDivergenceC0RepresentativeOnPoint3 U V i) := by
  have hToLp :
      Continuous (WithLp.toLp 2 : Point3 → H3FourierPoint3) := by
    exact (PiLp.contDiff_toLp :
      ContDiff ℝ 1 (WithLp.toLp 2 : Point3 → H3FourierPoint3)).continuous
  unfold h3RawFinLerayOuterProductDivergenceC0RepresentativeOnPoint3
  exact
    (h3RawFinLerayOuterProductDivergenceC0Representative_continuous U V i).comp
      hToLp

/-- On `Point3`, the continuous representative agrees almost everywhere with
the transported canonical `L²` reconstruction. -/
theorem h3RawFinLerayOuterProductDivergenceC0RepresentativeOnPoint3_ae_eq_physicalL2
    (U V : H3SpectralFinVectorState)
    (i : Fin 3) :
    h3RawFinLerayOuterProductDivergenceC0RepresentativeOnPoint3 U V i
      =ᵐ[(volume : Measure Point3)]
    (fun x : Point3 =>
      ((h3RawFinLerayOuterProductDivergencePhysicalL2 U V i : H3FourierComplexL2) :
        H3FourierPoint3 → ℂ)
        ((WithLp.toLp 2 : Point3 → H3FourierPoint3) x)) := by
  exact
    (PiLp.volume_preserving_toLp
      (PrimeTensor.Axis Depth.three)).quasiMeasurePreserving.ae_eq_comp
        (h3RawFinLerayOuterProductDivergenceC0Representative_ae_eq_physicalL2
          U V i)

end

end Euclidean
end Bridge
end PrimeTensor
