import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.Schwartz.Spectral.Nonlinear.Forcing.Duhamel.Frechet.Restart.Bound
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.Schwartz.Spectral.H3.Real.C1.Bridge

/-!
# Real C¹ nonlinear Duhamel reconstruction on `Point3`

The full nonlinear Duhamel reconstruction is now genuinely `C¹` in the
Euclidean Fourier-space spatial variable.  This file transports that result
to the real physical carrier used by the classical restart interface.

We first take the real part of the complex classical Duhamel representative,
then compose with the canonical `WithLp.toLp` identification from `Point3` to
`H3FourierPoint3`.  Both operations preserve `C¹`.

The final two theorems specialize this real physical representative to the
actual Banach-selected path on the canonical restart interval, including the
complete canonical restart radius.  This is the first direct spatial
classicalization statement for the singular nonlinear Duhamel term itself.
-/

namespace PrimeTensor
namespace Bridge
namespace Euclidean

open MeasureTheory Set
open scoped Topology

noncomputable section

noncomputable local instance axisFintypeH3SchwartzSpectralNonlinearForcingDuhamelFrechetRealC1
    (d : Depth) :
    Fintype (PrimeTensor.Axis d) :=
  Fintype.ofFinite (PrimeTensor.Axis d)

/-- Real part of the full complex nonlinear Duhamel classical representative
on the Euclidean Fourier carrier. -/
noncomputable def h3RawFinLerayOuterProductDivergenceHeatRealC1Duhamel
    (ν t : ℝ)
    (U V : ℝ → H3SpectralFinVectorState)
    (i : Fin 3) :
    H3FourierPoint3 → ℝ :=
  fun x =>
    (h3RawFinLerayOuterProductDivergenceHeatC3Duhamel
      ν t U V i x).re

/-- The real nonlinear Duhamel representative is spatially `C¹` on the
Euclidean Fourier carrier. -/
theorem h3RawFinLerayOuterProductDivergenceHeatRealC1Duhamel_contDiff_one
    {ν t MU MV : ℝ}
    (hν : 0 < ν)
    (ht : 0 ≤ t)
    (hMU : 0 ≤ MU)
    (hMV : 0 ≤ MV)
    (U V : ℝ → H3SpectralFinVectorState)
    (hUcont : Continuous U)
    (hVcont : Continuous V)
    (hU : ∀ s ∈ Set.Ioo (0 : ℝ) t, ‖U s‖ ≤ MU)
    (hV : ∀ s ∈ Set.Ioo (0 : ℝ) t, ‖V s‖ ≤ MV)
    (i : Fin 3) :
    ContDiff ℝ 1
      (h3RawFinLerayOuterProductDivergenceHeatRealC1Duhamel
        ν t U V i) := by
  unfold h3RawFinLerayOuterProductDivergenceHeatRealC1Duhamel
  simpa [Function.comp_def] using
    (h3RawFinLerayOuterProductDivergenceHeatC3Duhamel_contDiff_one
      hν ht hMU hMV U V hUcont hVcont hU hV i).continuousLinearMap_comp
        Complex.reCLM

/-- Real nonlinear Duhamel representative transported to the project's
physical spatial carrier. -/
noncomputable def h3RawFinLerayOuterProductDivergenceHeatRealC1DuhamelOnPoint3
    (ν t : ℝ)
    (U V : ℝ → H3SpectralFinVectorState)
    (i : Fin 3) :
    Point3 → ℝ :=
  fun x =>
    h3RawFinLerayOuterProductDivergenceHeatRealC1Duhamel
      ν t U V i
      ((WithLp.toLp 2 : Point3 → H3FourierPoint3) x)

/-- Transport through the canonical finite-dimensional carrier identification
preserves the full nonlinear Duhamel `C¹` regularity. -/
theorem h3RawFinLerayOuterProductDivergenceHeatRealC1DuhamelOnPoint3_contDiff_one
    {ν t MU MV : ℝ}
    (hν : 0 < ν)
    (ht : 0 ≤ t)
    (hMU : 0 ≤ MU)
    (hMV : 0 ≤ MV)
    (U V : ℝ → H3SpectralFinVectorState)
    (hUcont : Continuous U)
    (hVcont : Continuous V)
    (hU : ∀ s ∈ Set.Ioo (0 : ℝ) t, ‖U s‖ ≤ MU)
    (hV : ∀ s ∈ Set.Ioo (0 : ℝ) t, ‖V s‖ ≤ MV)
    (i : Fin 3) :
    ContDiff ℝ 1
      (h3RawFinLerayOuterProductDivergenceHeatRealC1DuhamelOnPoint3
        ν t U V i) := by
  have hToLp :
      ContDiff ℝ 1
        (WithLp.toLp 2 : Point3 → H3FourierPoint3) := by
    exact PiLp.contDiff_toLp
  unfold h3RawFinLerayOuterProductDivergenceHeatRealC1DuhamelOnPoint3
  exact
    (h3RawFinLerayOuterProductDivergenceHeatRealC1Duhamel_contDiff_one
      hν ht hMU hMV U V hUcont hVcont hU hV i).comp hToLp

/-- On every time slice inside the canonical restart window, the nonlinear
Duhamel term generated by the actual Banach-selected path has a real spatial
`C¹` representative on `Point3`. -/
theorem h3RawFinLerayOuterProductDivergenceHeatRealC1DuhamelOnPoint3_selectedRestart_contDiff_one
    {ν A t : ℝ}
    (hν : 0 < ν)
    (U₀ : H3SpectralVelocityState)
    (hA : 0 < A)
    (hU₀ : ‖U₀‖ ≤ A)
    (ht : 0 ≤ t)
    (_htR : t ≤ h3FinHeatLerayRestartRadius ν A)
    (i : Fin 3) :
    let W : ℝ → H3SpectralFinVectorState :=
      h3SpectralFinHeatLerayMildSolutionAtRestartRadiusPhysicalExtension
        hν U₀ hA hU₀
    ContDiff ℝ 1
      (h3RawFinLerayOuterProductDivergenceHeatRealC1DuhamelOnPoint3
        ν t W W i) := by
  dsimp only

  let W : ℝ → H3SpectralFinVectorState :=
    h3SpectralFinHeatLerayMildSolutionAtRestartRadiusPhysicalExtension
      hν U₀ hA hU₀

  have hWcont : Continuous W := by
    dsimp only [W]
    exact
      continuous_h3SpectralFinHeatLerayMildSolutionAtRestartRadiusPhysicalExtension
        hν U₀ hA hU₀

  have hW :
      ∀ s ∈ Set.Ioo (0 : ℝ) t,
        ‖W s‖ ≤ 2 * A := by
    intro s _hs
    dsimp only [W]
    exact
      norm_h3SpectralFinHeatLerayMildSolutionAtRestartRadiusPhysicalExtension_le_twoA
        hν U₀ hA hU₀ s

  have h2A : 0 ≤ 2 * A := by
    positivity

  exact
    h3RawFinLerayOuterProductDivergenceHeatRealC1DuhamelOnPoint3_contDiff_one
      hν ht h2A h2A
      W W hWcont hWcont hW hW i

/-- At the complete canonical restart radius, the selected nonlinear Duhamel
term already has a genuine real spatial `C¹` representative on `Point3`. -/
theorem h3RawFinLerayOuterProductDivergenceHeatRealC1DuhamelOnPoint3_atRestartRadius_contDiff_one
    {ν A : ℝ}
    (hν : 0 < ν)
    (U₀ : H3SpectralVelocityState)
    (hA : 0 < A)
    (hU₀ : ‖U₀‖ ≤ A)
    (i : Fin 3) :
    let R : ℝ := h3FinHeatLerayRestartRadius ν A
    let W : ℝ → H3SpectralFinVectorState :=
      h3SpectralFinHeatLerayMildSolutionAtRestartRadiusPhysicalExtension
        hν U₀ hA hU₀
    ContDiff ℝ 1
      (h3RawFinLerayOuterProductDivergenceHeatRealC1DuhamelOnPoint3
        ν R W W i) := by
  dsimp only
  exact
    h3RawFinLerayOuterProductDivergenceHeatRealC1DuhamelOnPoint3_selectedRestart_contDiff_one
      hν U₀ hA hU₀
      (h3FinHeatLerayRestartRadius_pos ν hA).le
      (le_refl (h3FinHeatLerayRestartRadius ν A))
      i

end

end Euclidean
end Bridge
end PrimeTensor
