import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.Schwartz.Spectral.Classicalization.Physical.Tail.Endpoint.Canonical.Physical.L2.Admissible.Closure.Leray.Density.Temporal.Endpoint.Family.Closure
import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.Schwartz.Spectral.Classicalization.Physical.Tail.Endpoint.Canonical.Physical.L2.Admissible.Closure.Leray.Density.Temporal.Endpoint.Family.Orthogonality.Product

/-!
# Physical L² temporal endpoint family: product-integrable closure

The product-integrability route now reaches the full physical `L²` evolution
family without using the older endpoint-specific admissible-test saturation.

For the fixed endpoint problem, assume only that every compact smooth
divergence-free weak test is coordinatewise product-integrable on every
shortened interval `[0,q]`.

Then, for each `q ∈ [0,tau]`:

1. `Family.Orthogonality.Product` shows every divergence-free weak test
   annihilates the physical evolution defect;
2. linearity extends this to the algebraic divergence-free weak-test span;
3. the defect is already Leray-fixed by `Family.Closure`;
4. the repository's parameter-free density theorem identifies the closed span
   of all divergence-free weak tests with the Leray-fixed submodule; and
5. therefore the defect lies in both a span orthogonal and its double
   orthogonal, hence is zero.

This is a strictly cleaner conditional frontier than temporal local domination.
It still does not claim that the current separated preterminal regularity
implies the product-integrability hypothesis.
-/

namespace PrimeTensor
namespace Bridge
namespace Euclidean

open MeasureTheory Filter Set FourierTransform
open scoped BigOperators ENNReal NNReal Interval Topology InnerProductSpace

noncomputable section

noncomputable local instance axisFintypeH3PhysicalL2TemporalEndpointProductClosure
    (d : Depth) :
    Fintype (PrimeTensor.Axis d) :=
  Fintype.ofFinite (PrimeTensor.Axis d)

/-- Endpoint-family product-integrability frontier: every compact smooth
divergence-free weak test is product-integrable on every shortened interval
`[0,q]` of the fixed endpoint problem. -/
def H3PreterminalTailCanonicalAllDivergenceFreeWeakTestsTemporallyProductIntegrableOnElapsed
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail) : Prop :=
  ∀ q : Set.Icc (0 : ℝ) tau,
    ∀ φ : H3WeakTestVector,
      H3WeakTestVectorDivergenceFree φ →
      H3PreterminalTailCanonicalWeakTemporalProductIntegrableTo
        hNS ht htau hEnd hE hTail hEndpoint
        (q := (q : ℝ)) φ

/-- Under the all-tests product-integrability frontier, the intermediate defect
is orthogonal to the full algebraic span generated by compact smooth
divergence-free weak tests. -/
theorem h3PreterminalTailCanonicalPhysicalL2EvolutionDefectTo_mem_divergenceFreeWeakTestSpan_orthogonal_of_all_productIntegrable
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail)
    (hAll :
      H3PreterminalTailCanonicalAllDivergenceFreeWeakTestsTemporallyProductIntegrableOnElapsed
        hNS ht htau hEnd hE hTail hEndpoint)
    (q : Set.Icc (0 : ℝ) tau) :
    h3PreterminalTailCanonicalPhysicalL2EvolutionDefectTo
        hNS ht htau hEnd hE hTail hEndpoint q
      ∈
    h3DivergenceFreeWeakTestPhysicalL2Spanᗮ := by
  let D : H3PhysicalRealFinVectorL2Hilbert :=
    h3PreterminalTailCanonicalPhysicalL2EvolutionDefectTo
      hNS ht htau hEnd hE hTail hEndpoint q

  let S : Set H3PhysicalRealFinVectorL2Hilbert :=
    h3DivergenceFreeWeakTestPhysicalL2Set

  let K : Submodule ℝ H3PhysicalRealFinVectorL2Hilbert :=
    Submodule.span ℝ S

  let L : H3PhysicalRealFinVectorL2Hilbert →L[ℝ] ℝ :=
    innerSL ℝ D

  have hGeneratorKer : S ⊆ L.ker := by
    intro Φ hΦ
    rcases hΦ with ⟨φ, hDiv, rfl⟩

    have hPair :
        inner ℝ
            (h3WeakTestVectorPhysicalL2Hilbert φ)
            D
          =
        0 := by
      dsimp only [D]
      exact
        inner_h3WeakTestVectorPhysicalL2Hilbert_evolutionDefectTo_eq_zero_of_productIntegrable
          hNS ht htau hEnd hE hTail hEndpoint
          φ hDiv q (hAll q φ hDiv)

    change L (h3WeakTestVectorPhysicalL2Hilbert φ) = 0
    dsimp only [L]

    simpa only [innerSL_apply_apply, real_inner_comm] using hPair

  have hSpanKer : K ≤ L.ker := by
    dsimp only [K]
    exact Submodule.span_le.mpr hGeneratorKer

  change D ∈ Kᗮ
  rw [Submodule.mem_orthogonal']

  intro Φ hΦ

  have hKer : Φ ∈ L.ker :=
    hSpanKer hΦ

  change L Φ = 0 at hKer
  dsimp only [L] at hKer

  simpa only [innerSL_apply_apply] using hKer

/-- The intermediate physical evolution defect vanishes under the endpoint
all-tests product-integrability frontier. -/
theorem h3PreterminalTailCanonicalPhysicalL2EvolutionDefectTo_eq_zero_of_all_productIntegrable
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail)
    (hAll :
      H3PreterminalTailCanonicalAllDivergenceFreeWeakTestsTemporallyProductIntegrableOnElapsed
        hNS ht htau hEnd hE hTail hEndpoint)
    (q : Set.Icc (0 : ℝ) tau) :
    h3PreterminalTailCanonicalPhysicalL2EvolutionDefectTo
        hNS ht htau hEnd hE hTail hEndpoint q
      =
    0 := by
  let D : H3PhysicalRealFinVectorL2Hilbert :=
    h3PreterminalTailCanonicalPhysicalL2EvolutionDefectTo
      hNS ht htau hEnd hE hTail hEndpoint q

  let K : Submodule ℝ H3PhysicalRealFinVectorL2Hilbert :=
    h3DivergenceFreeWeakTestPhysicalL2Span

  have hOrth : D ∈ Kᗮ := by
    dsimp only [D, K]
    exact
      h3PreterminalTailCanonicalPhysicalL2EvolutionDefectTo_mem_divergenceFreeWeakTestSpan_orthogonal_of_all_productIntegrable
        hNS ht htau hEnd hE hTail hEndpoint hAll q

  have hFixed :
      D ∈ h3PhysicalRealFinVectorL2HilbertLerayFixedSubmodule := by
    dsimp only [D]
    exact
      h3PreterminalTailCanonicalPhysicalL2EvolutionDefectTo_mem_lerayFixedSubmodule
        hNS ht htau hEnd hE hTail hEndpoint q

  have hMemClosed :
      D ∈ h3DivergenceFreeWeakTestPhysicalL2ClosedSpan := by
    rw [h3DivergenceFreeWeakTestPhysicalL2ClosedSpan_eq_lerayFixedSubmodule]
    exact hFixed

  have hClosedEq :
      h3DivergenceFreeWeakTestPhysicalL2ClosedSpan
        =
      Kᗮᗮ := by
    dsimp only [K]
    unfold h3DivergenceFreeWeakTestPhysicalL2ClosedSpan
    symm
    exact
      Submodule.orthogonal_orthogonal_eq_closure
        h3DivergenceFreeWeakTestPhysicalL2Span

  have hDouble : D ∈ Kᗮᗮ := by
    rw [← hClosedEq]
    exact hMemClosed

  have hBoth : D ∈ Kᗮ ⊓ Kᗮᗮ :=
    ⟨hOrth, hDouble⟩

  have hBot :
      D ∈ (⊥ : Submodule ℝ H3PhysicalRealFinVectorL2Hilbert) := by
    rw [← Submodule.inf_orthogonal_eq_bot Kᗮ]
    exact hBoth

  simpa using hBot

/-- Genuine physical `L²` vector evolution on every intermediate target under
the all-tests product-integrability frontier. -/
theorem h3PreterminalTailCanonicalVelocityIncrementPhysicalL2HilbertTo_eq_BochnerProjectedRHSTo_of_all_productIntegrable
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail)
    (hAll :
      H3PreterminalTailCanonicalAllDivergenceFreeWeakTestsTemporallyProductIntegrableOnElapsed
        hNS ht htau hEnd hE hTail hEndpoint)
    (q : Set.Icc (0 : ℝ) tau) :
    h3PreterminalTailCanonicalVelocityIncrementPhysicalL2HilbertTo
        hNS ht htau hEnd hTail q
      =
    h3PreterminalTailCanonicalProjectedRHSPhysicalL2BochnerIntegralHilbertTo
      hNS ht htau hEnd hE hTail hEndpoint q := by
  have hZero :=
    h3PreterminalTailCanonicalPhysicalL2EvolutionDefectTo_eq_zero_of_all_productIntegrable
      hNS ht htau hEnd hE hTail hEndpoint hAll q

  unfold h3PreterminalTailCanonicalPhysicalL2EvolutionDefectTo at hZero

  exact sub_eq_zero.mp hZero

end

end Euclidean
end Bridge
end PrimeTensor
