import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Canonical.Actual.Gradient.Closure
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Canonical.Curl.Integrable
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Canonical.Endpoint.From.Low.Tail
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Canonical.Selected.Continuation
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Canonical.Selected.Log.Bound
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Canonical.Slice
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Canonical.Vorticity.Fourier
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Convolution.Closure
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Fourier.Factors
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Fourier.Localization
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Gradient.Localized.Fourier
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Gradient.Localized.Physical
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Gradient.Localized.Physical.Representative
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Gradient.Middle
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Gradient.Reconstruction
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Kernel
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Kernel.Bound
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Kernel.Constant
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Kernel.Physical
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Kernel.Scaling
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Localization.Continuity
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Localized.Curl.Physical
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Schwartz.Anchor
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Shell.Count
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Shell.Log
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Shell.Partition
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Shell.Sum
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Vorticity.Convolution.Fourier
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Vorticity.Convolution.Physical
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Vorticity.Convolution.Reconstruction
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Vorticity.Convolution.Representative
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Young.Continuity
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Dyadic.Young.Schwartz.Bridge
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Energy.Kinetic.Low.Tail
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Energy.Kinetic.Monotonicity
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Fourier.Algebra
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Fourier.Bound
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Fourier.Multiplier
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Frequency.Shell
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Frequency.Shell.Telescoping
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Frequency.Trichotomy
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Frequency.Trichotomy.Bound
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Frequency.Trichotomy.Gradient.Mass
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Frequency.Trichotomy.Support
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Gradient.Actual.Closure
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Gradient.Actual.Selected.Bound
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Gradient.High.Cutoff.Selection
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Gradient.High.Dyadic.Decay
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Gradient.High.L2
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Gradient.High.Quarter.Weight
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Gradient.High.Tail.Decay
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Gradient.Localized.Multiplier
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Gradient.Localized.Shell.Sum
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Gradient.Logarithmic.Interface
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Gradient.Low.L2
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Gradient.Low.Physical.L2
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Gradient.Low.Spectral
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Gradient.Middle.Kernel.Bound
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Gradient.Middle.Localized.Fourier
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Gradient.Middle.Localized.Physical
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Gradient.Middle.Localized.Physical.Representative
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Gradient.Middle.Multiplier.Kernel
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Gradient.Middle.Selected.Fourier.Amplitude
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Gradient.Middle.Selected.Log.Bound
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Gradient.Middle.Selected.Pointwise.Bound
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Gradient.Middle.Selected.Reconstruction
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Gradient.Middle.Selected.Representative
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Gradient.Selected.Model.Bound
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Gradient.Selected.Reconstruction
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Kernel.Physical
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Multiplier.Localized
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Multiplier.Localized.Scaling
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Multiplier.Localized.Smooth
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Vorticity.Curl.Localized.Reconstruction
import PrimeTensor.Fluid.Vorticity.BKM.Endpoint.Vorticity.Physical.Convolution.L2
