import PrimeTensor.Bridge.Kernel.Final
import PrimeTensor.Fluid.Coupling

/-!
# Canonical completed coupling in the fluid system

The intrinsic fluid layer is parameterized by an abstract `MulCoupling`.
`Bridge.KernelFinal` now supplies one canonical completed coupling, so this
file specializes the nonlinear transport and momentum equation without making
the intrinsic `Fluid` modules depend on bridge machinery.

The resulting objects are still intrinsic `MulReal` fluid objects.  Only their
construction is discharged by the bridge.
-/

namespace PrimeTensor
namespace Bridge
namespace PrimePairApprox

/-- Left-unit law for the canonical completed logarithmic product coupling. -/
@[simp]
theorem logProductCoupling_one_left
    (a : PrimeTensor.MulReal) :
    logProductCoupling.couple 1 a = 1 := by
  exact logProductCoupling_lawful.couple_one_left a

/-- Right-unit law for the canonical completed logarithmic product coupling. -/
@[simp]
theorem logProductCoupling_one_right
    (a : PrimeTensor.MulReal) :
    logProductCoupling.couple a 1 = 1 := by
  exact logProductCoupling_lawful.couple_one_right a

/-- Multiplicativity in the first input. -/
theorem logProductCoupling_mul_left
    (a b c : PrimeTensor.MulReal) :
    logProductCoupling.couple (a * b) c =
      logProductCoupling.couple a c *
        logProductCoupling.couple b c := by
  exact logProductCoupling_lawful.couple_mul_left a b c

/-- Multiplicativity in the second input. -/
theorem logProductCoupling_mul_right
    (a b c : PrimeTensor.MulReal) :
    logProductCoupling.couple a (b * c) =
      logProductCoupling.couple a b *
        logProductCoupling.couple a c := by
  exact logProductCoupling_lawful.couple_mul_right a b c

/--
The canonical completed nonlinear spatial interaction.

After logarithmic interpretation, this is intended to be the positive
multiplicative counterpart of `(u · ∇)u`.
-/
noncomputable def logProductAdvection
    {X : Type} {dim : PrimeTensor.Depth}
    (D : PrimeTensor.Differential X PrimeTensor.MulReal dim)
    (u : PrimeTensor.VectorField X PrimeTensor.MulReal dim) :
    PrimeTensor.VectorField X PrimeTensor.MulReal dim :=
  PrimeTensor.MulAdvection.spatial
    D
    logProductCoupling
    u

@[simp]
theorem logProductAdvection_component
    {X : Type} {dim : PrimeTensor.Depth}
    (D : PrimeTensor.Differential X PrimeTensor.MulReal dim)
    (u : PrimeTensor.VectorField X PrimeTensor.MulReal dim)
    (x : PrimeTensor.Point X dim)
    (j : PrimeTensor.Axis dim) :
    (logProductAdvection D u x).component j =
      PrimeTensor.Axis.fold (· * ·) dim
        (fun i =>
          logProductCoupling.couple
            ((u x).component i)
            (D.d i
              (fun y => (u y).component j)
              x)) := by
  rfl

/--
Canonical spacetime transport generated by the completed coupling.
-/
noncomputable def logProductTransport
    {T X : Type} {dim : PrimeTensor.Depth}
    (D : PrimeTensor.Differential X PrimeTensor.MulReal dim) :
    PrimeTensor.MulTransport T X dim :=
  PrimeTensor.MulTransport.ofCoupling
    D
    logProductCoupling

@[simp]
theorem logProductTransport_apply
    {T X : Type} {dim : PrimeTensor.Depth}
    (D : PrimeTensor.Differential X PrimeTensor.MulReal dim)
    (u :
      PrimeTensor.SpaceTimeVectorField
        T X PrimeTensor.MulReal dim)
    (t : T)
    (x : PrimeTensor.Point X dim)
    (j : PrimeTensor.Axis dim) :
    ((logProductTransport D).act u t x).component j =
      PrimeTensor.Axis.fold (· * ·) dim
        (fun i =>
          logProductCoupling.couple
            ((u t x).component i)
            (D.d i
              (fun y => (u t y).component j)
              x)) := by
  rfl

/--
The canonical completed multiplicative momentum equation.

No coupling or completion hypothesis remains in this statement.
-/
def LogProductMomentumBalance
    {T X : Type} {dim : PrimeTensor.Depth}
    (Dt :
      PrimeTensor.TemporalDifferential
        T PrimeTensor.MulReal)
    (D :
      PrimeTensor.Differential
        X PrimeTensor.MulReal dim)
    (u :
      PrimeTensor.SpaceTimeVectorField
        T X PrimeTensor.MulReal dim)
    (p :
      PrimeTensor.SpaceTimeScalarField
        T X PrimeTensor.MulReal dim) : Prop :=
  PrimeTensor.MulFluid.CoupledMomentumBalance
    Dt D logProductCoupling u p

/--
A fluid solution using the canonical completed logarithmic product coupling.
-/
structure LogProductSolution
    {T X : Type} {dim : PrimeTensor.Depth}
    (Dt :
      PrimeTensor.TemporalDifferential
        T PrimeTensor.MulReal)
    (D :
      PrimeTensor.Differential
        X PrimeTensor.MulReal dim) where

  velocity :
    PrimeTensor.SpaceTimeVectorField
      T X PrimeTensor.MulReal dim

  pressure :
    PrimeTensor.SpaceTimeScalarField
      T X PrimeTensor.MulReal dim

  incompressible :
    PrimeTensor.MulFluid.Incompressible
      D velocity

  momentum :
    LogProductMomentumBalance
      Dt D velocity pressure

/--
The canonical nonlinear momentum equation exposed componentwise.
-/
theorem logProductMomentum_component
    {T X : Type} {dim : PrimeTensor.Depth}
    (Dt :
      PrimeTensor.TemporalDifferential
        T PrimeTensor.MulReal)
    (D :
      PrimeTensor.Differential
        X PrimeTensor.MulReal dim)
    (u :
      PrimeTensor.SpaceTimeVectorField
        T X PrimeTensor.MulReal dim)
    (p :
      PrimeTensor.SpaceTimeScalarField
        T X PrimeTensor.MulReal dim)
    (h :
      LogProductMomentumBalance
        Dt D u p)
    (t : T)
    (x : PrimeTensor.Point X dim)
    (j : PrimeTensor.Axis dim) :
    (Dt.vectorDerivative u t x).component j *
        PrimeTensor.Axis.fold (· * ·) dim
          (fun i =>
            logProductCoupling.couple
              ((u t x).component i)
              (D.d i
                (fun y => (u t y).component j)
                x)) =
      (PrimeTensor.MulFluid.pressureForce D p t x).component j *
        (PrimeTensor.MulFluid.laplacianVector D u t x).component j := by
  exact
    PrimeTensor.MulFluid.coupledMomentum_component
      Dt D logProductCoupling
      u p h t x j

end PrimePairApprox
end Bridge
end PrimeTensor
