import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.Schwartz.Spectral.Classicalization.Physical.Tail.Endpoint.Canonical.Physical.L2.RHS.Bochner.Leray.Fixed
import Mathlib.Topology.Algebra.Module.ContinuousLinearMap.RestrictScalars

/-!
# Classicalization: reduce admissible closure to the physical Leray-fixed subspace

The two genuine physical `L²` evolution terms are now independently known to
be quotient-safe Leray-fixed:

* the endpoint velocity increment;
* the Bochner integral of the projected RHS.

The earlier admissible-closure reduction asks for those same two states to lie
in the closed span generated by the currently justified compact smooth
divergence-free tests satisfying temporal local domination.

This file identifies the natural intermediate Hilbert subspace exactly.

For a physical three-component `PiLp 2` state `V`, the repository already
defines the canonical raw Fourier vector

    V ↦ h3PhysicalRealFinVectorL2HilbertRawFourier V

and calls `V` Leray-fixed when the finite Leray multiplier fixes that Fourier
vector.

We now package the raw Fourier transform as a bounded real continuous linear
map and compose it with the already-bounded finite Leray projector.  The
physical Leray defect

    V ↦ P(F V) - F V

is therefore a continuous real-linear map.  Its kernel is the exact physical
Leray-fixed submodule, and that kernel is closed.

Both evolution terms lie in this closed submodule by the two preceding
checkpoints.  Consequently the old two-term admissible-closure frontier is
reduced to one inclusion only:

    physical Leray-fixed submodule
      ≤ admissible weak-test closed span.

That inclusion is the genuine remaining density/local-domination question.
No claim that it already holds is made here.
-/

namespace PrimeTensor
namespace Bridge
namespace Euclidean

open MeasureTheory Filter Set
open scoped BigOperators ENNReal NNReal Interval Topology InnerProductSpace

noncomputable section

noncomputable local instance axisFintypeH3PhysicalTailEndpointCanonicalPhysicalL2AdmissibleClosureLerayReduction
    (d : Depth) :
    Fintype (PrimeTensor.Axis d) :=
  Fintype.ofFinite (PrimeTensor.Axis d)

noncomputable local instance point3MeasureSpaceH3PhysicalTailEndpointCanonicalPhysicalL2AdmissibleClosureLerayReduction :
    MeasureSpace Point3 :=
  @MeasureTheory.MeasureSpace.pi
    (PrimeTensor.Axis Depth.three)
    (Fintype.ofFinite (PrimeTensor.Axis Depth.three))
    (fun _ : PrimeTensor.Axis Depth.three => ℝ)
    (fun _ : PrimeTensor.Axis Depth.three => Real.measureSpace)

/-! ## Physical raw Fourier transform as a bounded real-linear map -/

/-- Coordinatewise physical Plancherel on the three-component `PiLp 2`
Hilbert product, packaged as a real linear map. -/
noncomputable def h3PhysicalRealFinVectorL2HilbertRawFourierRealLinearMap :
    H3PhysicalRealFinVectorL2Hilbert →ₗ[ℝ]
      H3SpectralFinVectorState where
  toFun := h3PhysicalRealFinVectorL2HilbertRawFourier
  map_add' := by
    intro V W
    funext i
    unfold h3PhysicalRealFinVectorL2HilbertRawFourier
    simp only [PiLp.add_apply, Pi.add_apply]
    exact h3ScalarFourierL2_add (V i) (W i)
  map_smul' := by
    intro c V
    funext i
    unfold h3PhysicalRealFinVectorL2HilbertRawFourier
    simp only [PiLp.smul_apply, Pi.smul_apply]
    exact h3ScalarFourierL2_smul_real c (V i)

@[simp]
theorem h3PhysicalRealFinVectorL2HilbertRawFourierRealLinearMap_apply
    (V : H3PhysicalRealFinVectorL2Hilbert) :
    h3PhysicalRealFinVectorL2HilbertRawFourierRealLinearMap V
      =
    h3PhysicalRealFinVectorL2HilbertRawFourier V := rfl

/-- The coordinatewise physical Plancherel map is contractive from the
`PiLp 2` Hilbert norm to the finite product sup norm. -/
theorem norm_h3PhysicalRealFinVectorL2HilbertRawFourier_le
    (V : H3PhysicalRealFinVectorL2Hilbert) :
    ‖h3PhysicalRealFinVectorL2HilbertRawFourier V‖
      ≤
    ‖V‖ := by
  apply (pi_norm_le_iff_of_nonneg (norm_nonneg V)).2
  intro i

  calc
    ‖h3PhysicalRealFinVectorL2HilbertRawFourier V i‖
        =
      ‖V i‖ := by
        unfold h3PhysicalRealFinVectorL2HilbertRawFourier
        exact norm_h3ScalarFourierL2 (V i)
    _ ≤ ‖V‖ := PiLp.norm_apply_le V i

/-- Bounded real continuous-linear version of the physical raw Fourier map. -/
noncomputable def h3PhysicalRealFinVectorL2HilbertRawFourierRealContinuousLinearMap :
    H3PhysicalRealFinVectorL2Hilbert →L[ℝ]
      H3SpectralFinVectorState :=
  h3PhysicalRealFinVectorL2HilbertRawFourierRealLinearMap.mkContinuous
    1
    (fun V => by
      change
        ‖h3PhysicalRealFinVectorL2HilbertRawFourier V‖
          ≤
        1 * ‖V‖
      simpa using
        norm_h3PhysicalRealFinVectorL2HilbertRawFourier_le V)

@[simp]
theorem h3PhysicalRealFinVectorL2HilbertRawFourierRealContinuousLinearMap_apply
    (V : H3PhysicalRealFinVectorL2Hilbert) :
    h3PhysicalRealFinVectorL2HilbertRawFourierRealContinuousLinearMap V
      =
    h3PhysicalRealFinVectorL2HilbertRawFourier V := rfl

/-! ## The physical Leray-fixed closed submodule -/

/-- The existing bounded complex finite Leray projector, viewed only as a
real continuous-linear map. -/
noncomputable def h3SpectralFinLerayRealContinuousLinearMap :
    H3SpectralFinVectorState →L[ℝ]
      H3SpectralFinVectorState :=
  h3SpectralFinLerayContinuousLinearMap.restrictScalars ℝ

@[simp]
theorem h3SpectralFinLerayRealContinuousLinearMap_apply
    (G : H3SpectralFinVectorState) :
    h3SpectralFinLerayRealContinuousLinearMap G
      =
    h3SpectralFinLerayApply G := rfl

/-- Continuous physical Leray defect `V ↦ P(FV) - FV`. -/
noncomputable def h3PhysicalRealFinVectorL2HilbertLerayDefectContinuousLinearMap :
    H3PhysicalRealFinVectorL2Hilbert →L[ℝ]
      H3SpectralFinVectorState :=
  h3SpectralFinLerayRealContinuousLinearMap.comp
      h3PhysicalRealFinVectorL2HilbertRawFourierRealContinuousLinearMap
    -
  h3PhysicalRealFinVectorL2HilbertRawFourierRealContinuousLinearMap

@[simp]
theorem h3PhysicalRealFinVectorL2HilbertLerayDefectContinuousLinearMap_apply
    (V : H3PhysicalRealFinVectorL2Hilbert) :
    h3PhysicalRealFinVectorL2HilbertLerayDefectContinuousLinearMap V
      =
    h3SpectralFinLerayApply
        (h3PhysicalRealFinVectorL2HilbertRawFourier V)
      -
    h3PhysicalRealFinVectorL2HilbertRawFourier V := by
  rfl

/-- Exact physical solenoidal/Leray-fixed real Hilbert submodule. -/
noncomputable def h3PhysicalRealFinVectorL2HilbertLerayFixedSubmodule :
    Submodule ℝ H3PhysicalRealFinVectorL2Hilbert :=
  h3PhysicalRealFinVectorL2HilbertLerayDefectContinuousLinearMap.ker

/-- Membership in the kernel submodule is exactly the existing quotient-safe
physical Leray-fixed predicate. -/
theorem mem_h3PhysicalRealFinVectorL2HilbertLerayFixedSubmodule_iff
    (V : H3PhysicalRealFinVectorL2Hilbert) :
    V ∈ h3PhysicalRealFinVectorL2HilbertLerayFixedSubmodule
      ↔
    H3PhysicalRealFinVectorL2HilbertLerayFixed V := by
  unfold h3PhysicalRealFinVectorL2HilbertLerayFixedSubmodule
  change
    h3PhysicalRealFinVectorL2HilbertLerayDefectContinuousLinearMap V = 0
      ↔
    H3PhysicalRealFinVectorL2HilbertLerayFixed V

  rw [
    h3PhysicalRealFinVectorL2HilbertLerayDefectContinuousLinearMap_apply
  ]

  unfold H3PhysicalRealFinVectorL2HilbertLerayFixed

  exact sub_eq_zero

/-- The physical Leray-fixed submodule is topologically closed. -/
theorem isClosed_h3PhysicalRealFinVectorL2HilbertLerayFixedSubmodule :
    IsClosed
      (h3PhysicalRealFinVectorL2HilbertLerayFixedSubmodule :
        Set H3PhysicalRealFinVectorL2Hilbert) := by
  unfold h3PhysicalRealFinVectorL2HilbertLerayFixedSubmodule
  exact
    ContinuousLinearMap.isClosed_ker
      h3PhysicalRealFinVectorL2HilbertLerayDefectContinuousLinearMap

/-! ## Both physical evolution terms lie in the closed Leray subspace -/

/-- The endpoint velocity increment belongs to the exact closed physical
Leray-fixed submodule. -/
theorem h3PreterminalTailCanonicalVelocityIncrementPhysicalL2Hilbert_mem_lerayFixedSubmodule
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hTail : CanonicalH3TailDataFrom u t T E) :
    h3PreterminalTailCanonicalVelocityIncrementPhysicalL2Hilbert
        hNS ht htau hEnd hTail
      ∈
    h3PhysicalRealFinVectorL2HilbertLerayFixedSubmodule := by
  rw [
    mem_h3PhysicalRealFinVectorL2HilbertLerayFixedSubmodule_iff
  ]

  exact
    h3PreterminalTailCanonicalVelocityIncrementPhysicalL2Hilbert_lerayFixed
      hNS ht htau hEnd hTail

/-- The Bochner-integrated projected RHS belongs to the exact closed physical
Leray-fixed submodule. -/
theorem h3PreterminalTailCanonicalProjectedRHSPhysicalL2BochnerIntegralHilbert_mem_lerayFixedSubmodule
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail) :
    h3PreterminalTailCanonicalProjectedRHSPhysicalL2BochnerIntegralHilbert
        hNS ht htau hEnd hE hTail hEndpoint
      ∈
    h3PhysicalRealFinVectorL2HilbertLerayFixedSubmodule := by
  rw [
    mem_h3PhysicalRealFinVectorL2HilbertLerayFixedSubmodule_iff
  ]

  exact
    h3PreterminalTailCanonicalProjectedRHSPhysicalL2BochnerIntegralHilbert_lerayFixed
      hNS ht htau hEnd hE hTail hEndpoint

/-! ## Exact remaining inclusion frontier -/

/-- The exact remaining density/local-domination frontier needed by the old
admissible-closure reduction: every quotient-safe physical Leray-fixed state
must lie in the closed span generated by the currently admissible weak tests.

This is intentionally only one inclusion.  It is exactly sufficient for the
evolution identity because both actual evolution terms have already been shown
to lie in the Leray-fixed submodule. -/
def H3PreterminalTailCanonicalPhysicalL2LerayFixedSubmoduleContainedInAdmissibleWeakTestClosedSpan
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail) : Prop :=
  h3PhysicalRealFinVectorL2HilbertLerayFixedSubmodule
    ≤
  h3PreterminalTailCanonicalAdmissibleWeakTestPhysicalL2ClosedSpan
    hNS ht htau hEnd hE hTail hEndpoint

/-- The single Leray-subspace inclusion implies the old two-term admissible
closed-span membership frontier. -/
theorem h3PreterminalTailCanonicalPhysicalL2EvolutionTermsInAdmissibleWeakTestClosedSpan_of_lerayFixedSubmoduleContained
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail)
    (hContained :
      H3PreterminalTailCanonicalPhysicalL2LerayFixedSubmoduleContainedInAdmissibleWeakTestClosedSpan
        hNS ht htau hEnd hE hTail hEndpoint) :
    H3PreterminalTailCanonicalPhysicalL2EvolutionTermsInAdmissibleWeakTestClosedSpan
      hNS ht htau hEnd hE hTail hEndpoint := by
  constructor

  · exact
      hContained
        (h3PreterminalTailCanonicalVelocityIncrementPhysicalL2Hilbert_mem_lerayFixedSubmodule
          hNS ht htau hEnd hTail)

  · exact
      hContained
        (h3PreterminalTailCanonicalProjectedRHSPhysicalL2BochnerIntegralHilbert_mem_lerayFixedSubmodule
          hNS ht htau hEnd hE hTail hEndpoint)

/-- Conditional vector evolution identity reduced to the single exact
Leray-density inclusion frontier. -/
theorem h3PreterminalTailCanonicalVelocityIncrementPhysicalL2Hilbert_eq_BochnerProjectedRHS_of_lerayFixedSubmoduleContained
    {E : ℝ}
    {u : SpaceTimeVectorField ℝ ℝ MulReal Depth.three}
    {T t tau : ℝ}
    (hNS : LoggedPreterminalNavierStokesAdmissible u T)
    (ht : t ∈ Set.Ioo (0 : ℝ) T)
    (htau : 0 < tau)
    (hEnd : t + tau < T)
    (hE : 1 ≤ E)
    (hTail : CanonicalH3TailDataFrom u t T E)
    (hEndpoint :
      H3PreterminalCanonicalL2EndpointContinuousOnElapsed
        hNS ht hEnd hTail)
    (hContained :
      H3PreterminalTailCanonicalPhysicalL2LerayFixedSubmoduleContainedInAdmissibleWeakTestClosedSpan
        hNS ht htau hEnd hE hTail hEndpoint) :
    h3PreterminalTailCanonicalVelocityIncrementPhysicalL2Hilbert
        hNS ht htau hEnd hTail
      =
    h3PreterminalTailCanonicalProjectedRHSPhysicalL2BochnerIntegralHilbert
      hNS ht htau hEnd hE hTail hEndpoint := by
  exact
    h3PreterminalTailCanonicalVelocityIncrementPhysicalL2Hilbert_eq_BochnerProjectedRHS_of_terms_mem_admissibleWeakTestClosedSpan
      hNS ht htau hEnd hE hTail hEndpoint
      (h3PreterminalTailCanonicalPhysicalL2EvolutionTermsInAdmissibleWeakTestClosedSpan_of_lerayFixedSubmoduleContained
        hNS ht htau hEnd hE hTail hEndpoint hContained)

end

end Euclidean
end Bridge
end PrimeTensor
