import PrimeTensor.Fluid.Vorticity.Continuation.Restart.Mild.Sobolev.Schwartz.Spectral.Nonlinear.Forcing.Duhamel.Frechet.Second.Endpoint.Quarter.Forcing.MajorantIntegral

/-!
# Selected quarter-Hölder forcing: integrated second-moment majorant

`Forcing.MajorantIntegral` evaluates the universal quarter-cancellation
majorant for an arbitrary endpoint coefficient.  The selected restart path
already carries the explicit coefficient
`h3NonlinearForcingQuarterSelectedRestartLocalCoefficient`.

This file specializes the scalar endpoint budget to that coefficient.  The
result is the exact time-integrated majorant that will dominate the selected
second-Fourier-moment forcing term on every positive terminal interval.
-/

namespace PrimeTensor
namespace Bridge
namespace Euclidean

open MeasureTheory Set
open scoped ENNReal NNReal Interval

noncomputable section

/-- Exact time integral of the quarter-cancellation majorant with the
coefficient generated by the Banach-selected restart path. -/
theorem h3NonlinearForcingHeatSecondDerivativeQuarterCancellationMajorant_integral_selectedRestart
    {ν A a t : ℝ}
    (hat : a ≤ t) :
    (∫ s in a..t,
        h3NonlinearForcingHeatSecondDerivativeQuarterCancellationMajorant
          ν t
          (h3NonlinearForcingQuarterSelectedRestartLocalCoefficient ν A a t)
          s)
      =
    12 * ν⁻¹ *
        h3NonlinearForcingQuarterSelectedRestartLocalCoefficient ν A a t *
        (t - a) ^ ((1 : ℝ) / 4) := by
  exact
    h3NonlinearForcingHeatSecondDerivativeQuarterCancellationMajorant_integral_on
      hat

/-- The selected quarter-cancellation majorant is interval-integrable on the
same terminal interval. -/
theorem h3NonlinearForcingHeatSecondDerivativeQuarterCancellationMajorant_intervalIntegrable_selectedRestart
    {ν A a t : ℝ} :
    IntervalIntegrable
      (h3NonlinearForcingHeatSecondDerivativeQuarterCancellationMajorant
        ν t
        (h3NonlinearForcingQuarterSelectedRestartLocalCoefficient ν A a t))
      volume
      a
      t := by
  exact
    h3NonlinearForcingHeatSecondDerivativeQuarterCancellationMajorant_intervalIntegrable

end

end Euclidean
end Bridge
end PrimeTensor
